#ifndef _Tpolymassexp_H_
#define _Tpolymassexp_H_

enum
{
	POLYMASS_VMAPTAGLINK	= 1000,
	POLYMASS_POLYTAGLINK	= 1001,
	POLYMASS_THRESHOLD		= 1002,
	POLYMASS_VERTTHRESH		= 1003,
	POLYMASS_MAPMODE		= 1004,
		MAPMODE_VMAPTOPOLY = 0,
		MAPMODE_POLYTOVMAP = 1,

	_PM_DUMMY
};

#endif



