#ifndef __VRAY_SYMBOLS_H
#define __VRAY_SYMBOLS_H

enum
{
	ID_VRAYBRIDGE			= 1019782,
	//ID_VRAYBITMAP			= 1020425,
	ID_VRAYCOMPOSITING		= 1021738,
	ID_VRAYBLENDMATERIAL	= 1022116,
	ID_VRAYBRDF_MATERIAL	= 1020295,
	ID_VRAYFASTSSS2MATERIAL = 1024192,
	ID_VRAY2SIDEDMATERIAL	= 1022115,
	ID_VRAYOVERRIDEMATERIAL = 1023126,
	ID_VRAYDISPLACEMATERIAL = 1022593,
	ID_VRAYCARPAINTMATERIAL = 1029457,
	ID_VRAYHAIRMATERIAL		= 1029537,
    ID_VRAYBUMPMATERIAL     = 1032210,

	ID_VRAYSHADERWRAPPER	= 1026701,

	ID_VRAY_BITMAP_CONVERTER= 1024462,
	ID_VRAY_MATCONVERTER	= 1021144,

	ID_AIX_ATTRIBUTE_TAG	= 1025866,
    ID_VRAY_IMAGERELOAD_CMD = 1032607,

	IDS_VRAYBRIDGE		 = 10000,
	IDS_VRAYMATERIAL			,
	IDS_VRAYBITMAP				,
	IDS_VRAYLIGHTTAG			,
	IDS_VRAYVERBOSE				,
	IDS_VRAYPHYSICALCAMERATAG	,
	IDS_VRAYDISPTAG				,
	IDS_VRAYMBLURTAG			,
	IDS_VRAYCOMPOSITINGTAG		,
	IDS_VRAYCAMERADOMETAG		,
	IDS_VRAY2SIDEDMATERIAL		,
	IDS_VRAYPROXY				,

	IDS_AIX_ATTRIBUTE_TAG		,

	// Dialog definitions of IDD_VRAYCONSOLE start here
	IDD_VRAYCONSOLE,
	VRAY_GUI,
	// Dialog definitions of IDD_VRAYCONSOLE end here

	IDS_FAST_FUR		,
	IDS_FAST_FUR_MAT	,

	IDS_PATCH,
	IDS_TEA_POT,
	IDS_TEA_SET,
	
	//PatchNames
	IDS_BODY,
	IDS_LID	,
	IDS_SPOUT,
	IDS_HANDLE,
	
	
	//VRAYCAMLISTER
	ID_VRAYCAMLISTER = 1032256, 

    // target IDs
    ID_VRAYCAMTAG = 1020898,

    // string table definitions
    IDS_VRAYCAMLISTER	= 20000,
    IDS_VRAYCAMLISTER_DLG_TITLE,
    IDS_STATUSBAR_HELPSTRING,
	
	IDC_MESSAGE_TEXT,

    IDC_TARGETS,
    IDC_TARGETS_SCROLLGROUP,

    // Vray Camera
    IDC_VRAY_CAM_ACTIVATE = 21000,
    IDC_VRAY_CAM_NAME = 22000,
    IDC_VRAY_CAM_TYPE = 23000, 
    IDC_VRAY_CAM_WBPRESET = 24000, 
    IDC_VRAY_CAM_WBCOLOR = 25000,
    IDC_VRAY_CAM_FILMISO = 26000,
    IDC_VRAY_CAM_FSTOP = 27000,
    IDC_VRAY_CAM_SPEEDANGLELAT = 28000,
    IDC_VRAY_CAM_MBLUR = 29000,
    IDC_VRAY_CAM_DOF = 30000,
    IDC_VRAY_CAM_RENDERCAM = 31000,
    
    //VRAYLIGHTLISTER
    ID_VRAYLIGHTLISTER = 1032257, 

    // string table definitions
    IDS_VRAYLIGHTLISTER	= 40000,
    IDS_VRAYLIGHTLISTER_DLG_TITLE,
    IDC_SHADOWS_HEADER_BUTTON,

    // C4D Lights
    IDC_C4D_LIGHT_NAME = 41000,
    IDC_C4D_LIGHT_BRIGHTNESS = 42000,

    // Vray Lights
    IDC_VRAY_LIGHT_ACTIVATE = 51000,
    IDC_VRAY_LIGHT_NAME = 52000,
    IDC_VRAY_LIGHT_TYPE = 53000,
    IDC_VRAY_LIGHT_INTENSITY = 54000,
    IDC_VRAY_LIGHT_INTENSITY_UNITS = 55000,
    IDC_VRAY_LIGHT_COLOR = 56000, 
    IDC_VRAY_LIGHT_SHADOWS = 57000,
    IDC_VRAY_LIGHT_SSUBDIV = 58000,
    IDC_VRAY_LIGHT_CSUBDIV = 59000,
    IDC_VRAY_LIGHT_DECAY = 60000,
    
    // DOMELIGHT VIEWER
  	ID_SW_FILE_4999 = 4999,               	// Filename of VRayAdvBitmap
  	ID_SW_EXPOSURE_107820122 = 107820122, 	// Exposure of VRayAdvBitmap
  
	IDD_DIALOG1				= 61000, 
	IDC_GRP_TABS,
	IDC_GRP_DOMELIGHTS,
	IDC_GRP_TEXPATH,
	IDC_LBL_TEXPATH,
	IDC_ST_TEXPATH,
	IDC_GRP_EXPADJ,
	IDC_LBL_EXPOSURE,
	IDC_EDIT_EXPOSURE,
	IDC_GRP_TEXRES,
	IDC_LBL_TEXRES,
	IDC_CBX_MATRES,
	IDC_GRP_BUTTON,
	IDC_BTN_VIEWTEX,
	IDC_BTN_CLEARTEX,
	IDC_GRP_BGENV,
	IDC_GRP_BE_TEXPATH,
	IDC_LBL_BE_TEXPATH,
	IDC_ST_BE_TEXPATH,
	IDC_GRP_BE_EXPADJ,
	IDC_LBL_BE_EXPOSURE,
	IDC_EDIT_BE_EXPOSURE,
	IDC_GRP_BE_TEXRES,
	IDC_LBL_BE_TEXRES,
	IDC_CBX_BE_MATRES,
	IDC_GRP_BE_BUTTON,
	IDC_BTN_BE_VIEWTEX,
	IDC_BTN_BE_CLEARTEX,

	IDS_VRAYDOMELIGHTTEXTUREVIEW = 62000,
	IDS_HELPSTRING,
	IDS_MSG_WRONGOBJ,
	IDS_MSG_MISSING_LIGHTTAG,

// End of symbol definition
  _DUMMY_ELEMENT_
};

#endif //__VRAY_SYMBOLS_H