/// Copyright (C) 2014  Niklas Rosenstein
/// All rights reserved.
/// Developed for LAUBLab KG

CONTAINER Fvrmesh
{
	NAME Fvrmesh;
	INCLUDE Fbase;

	GROUP ID_FILTERPROPERTIES
	{
		BOOL VRMESH_EXPORT_EXPORTSELECTED { DEFAULT 0; }
		BOOL VRMESH_EXPORT_EXPORTUVW { DEFAULT 1; }
		BOOL VRMESH_EXPORT_EXPORTNORMALS { DEFAULT 1; }
		BOOL VRMESH_EXPORT_EXPORTMATERIALS { DEFAULT 1; }
		LONG VRMESH_EXPORT_FACESPERVOXEL { DEFAULT 1024; MIN 1; }
		SEPARATOR { LINE; }
		BOOL VRMESH_EXPORT_GENERATEPREVIEW { DEFAULT 1; }
		REAL VRMESH_EXPORT_PREVIEWLOD { DEFAULT 20; MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
		SEPARATOR { LINE; }
		BOOL VRMESH_EXPORT_CREATEPROXY { DEFAULT 1; }
	}
}