 CONTAINER mVrayBlendMaterial
{
	NAME mVrayBlendMaterial;

	GROUP
	{
		MATPREVIEW VRAYBLENDMATERIAL_MAT_PREVIEW { OPEN; }
	}

	INCLUDE Mbase;

	GROUP Obaselist
	{
		SEPARATOR {LINE;}
		//BOOL VRAYBLENDMATERIAL_ANIMATEPREVIEW { }
		LONG VRAYBLENDMATERIAL_QUALITY
 		{
 			CYCLE
 			{
 				VRAYBLENDMATERIAL_QUALITY_0;
 				VRAYBLENDMATERIAL_QUALITY_1;
 				VRAYBLENDMATERIAL_QUALITY_2;
 			}
 		}
		LONG VRAYBLENDMATERIAL_PREVIEWSIZE
		{
			CYCLE
			{
				VRAYBLENDMATERIAL_PREVIEWSIZE_DEF;
				VRAYBLENDMATERIAL_PREVIEWSIZE_64;
				VRAYBLENDMATERIAL_PREVIEWSIZE_128;
				VRAYBLENDMATERIAL_PREVIEWSIZE_256;
				VRAYBLENDMATERIAL_PREVIEWSIZE_512;
				VRAYBLENDMATERIAL_PREVIEWSIZE_1024;
				VRAYBLENDMATERIAL_PREVIEWSIZE_2048;
			}
		}
		SEPARATOR { }

		REAL VRAYBLENDMATERIAL_GAMMA { HIDDEN; MIN 0; STEP 0.1; MAXSLIDER 2.2; CUSTOMGUI REALSLIDER; }

		SEPARATOR {LINE;}

		BOOL VRAYBLENDMATERIAL_OVERRIDABLE {}
		
		SEPARATOR { LINE; }
		
		COLOR VRAYBLENDMATERIAL_IDCOLOR {HIDDEN;}

 		SEPARATOR { LINE; }
 		
		GROUP
		{
			COLUMNS 2;
			
			BOOL VRAYBLENDMATERIAL_ISROUNDED {}
			REAL VRAYBLENDMATERIAL_ROUNDRADIUS {MIN 0;}
		}

 		SEPARATOR { LINE; }

		BOOL VRAYBLENDMATERIAL_PAGE_PARAMS	{ PAGE; HIDDEN; PARENTMSG ID_VRAYBLENDMATERIALGROUP_PARAMS; }
		BOOL VRAYBLENDMATERIAL_PAGE_ILLUMINATION	{ PAGE; HIDDEN; PARENTMSG ID_VRAYBLENDMATERIALGROUP_ILLUMINATION; }
	}


	GROUP ID_VRAYBLENDMATERIALGROUP_PARAMS
	{
		LONG VRAYBLENDMATERIAL_PARAMS_MATNUM {MIN 1; MAX 8; HIDDEN;}

		SEPARATOR {LINE;}

		BOOL VRAYBLENDMATERIAL_PARAMS_USELINK1 {}
		LINK VRAYBLENDMATERIAL_PARAMS_LINK1 {}

		SEPARATOR {LINE;}

		BOOL VRAYBLENDMATERIAL_PARAMS_USELINK2 {}
		LINK VRAYBLENDMATERIAL_PARAMS_LINK2 {}

		SEPARATOR {LINE;}

		BOOL VRAYBLENDMATERIAL_PARAMS_USELINK3 {}
		LINK VRAYBLENDMATERIAL_PARAMS_LINK3 {}

		SEPARATOR {LINE;}

		BOOL VRAYBLENDMATERIAL_PARAMS_USELINK4 {}
		LINK VRAYBLENDMATERIAL_PARAMS_LINK4 {}

		SEPARATOR {LINE;}

		BOOL VRAYBLENDMATERIAL_PARAMS_USELINK5 {}
		LINK VRAYBLENDMATERIAL_PARAMS_LINK5 {}

		SEPARATOR {LINE;}

		BOOL VRAYBLENDMATERIAL_PARAMS_USELINK6 {}
		LINK VRAYBLENDMATERIAL_PARAMS_LINK6 {}

		SEPARATOR {LINE;}

		BOOL VRAYBLENDMATERIAL_PARAMS_USELINK7 {}
		LINK VRAYBLENDMATERIAL_PARAMS_LINK7 {}

		SEPARATOR {LINE;}

		BOOL VRAYBLENDMATERIAL_PARAMS_USELINK8 {}
		LINK VRAYBLENDMATERIAL_PARAMS_LINK8 {}

		SEPARATOR {LINE;}

		BOOL VRAYBLENDMATERIAL_PARAMS_USELINK9 {}
		LINK VRAYBLENDMATERIAL_PARAMS_LINK9 {}

		SEPARATOR {LINE;}

		BOOL VRAYBLENDMATERIAL_PARAMS_USELINK10 {}
		LINK VRAYBLENDMATERIAL_PARAMS_LINK10 {}SEPARATOR {LINE;}

	}

	GROUP ID_VRAYBLENDMATERIALGROUP_ILLUMINATION
	{
		SEPARATOR { }



	}

	INCLUDE Massign;

	LONG VRAYBLENDMATERIAL_NODE {HIDDEN;}
}
