 CONTAINER mVray2SidedMaterial
{
	NAME mVray2SidedMaterial;

	GROUP
	{
		MATPREVIEW VRAY2SIDEDMATERIAL_MAT_PREVIEW { OPEN; }
	}

	INCLUDE Mbase;

	GROUP Obaselist
	{
		SEPARATOR {LINE;}
		//BOOL VRAY2SIDEDMATERIAL_ANIMATEPREVIEW { }
		LONG VRAY2SIDEDMATERIAL_QUALITY
 		{
 			CYCLE
 			{
 				VRAY2SIDEDMATERIAL_QUALITY_0;
 				VRAY2SIDEDMATERIAL_QUALITY_1;
 				VRAY2SIDEDMATERIAL_QUALITY_2;
 			}
 		}
		LONG VRAY2SIDEDMATERIAL_PREVIEWSIZE
		{
			CYCLE
			{
				VRAY2SIDEDMATERIAL_PREVIEWSIZE_DEF;
				VRAY2SIDEDMATERIAL_PREVIEWSIZE_64;
				VRAY2SIDEDMATERIAL_PREVIEWSIZE_128;
				VRAY2SIDEDMATERIAL_PREVIEWSIZE_256;
				VRAY2SIDEDMATERIAL_PREVIEWSIZE_512;
				VRAY2SIDEDMATERIAL_PREVIEWSIZE_1024;
				VRAY2SIDEDMATERIAL_PREVIEWSIZE_2048;
				//VRAYMATERIAL_PREVIEWSIZE_4096;
			}
		}
		SEPARATOR { }

		REAL VRAY2SIDEDMATERIAL_GAMMA { HIDDEN; MIN 0; STEP 0.1; MAXSLIDER 2.2; CUSTOMGUI REALSLIDER; }

		SEPARATOR {LINE;}

		BOOL VRAY2SIDEDMATERIAL_OVERRIDABLE {}

 		SEPARATOR { LINE; }
 		
		LONG VRAY2SIDEDMATERIAL_ID {HIDDEN; MIN 0;}
 		COLOR VRAY2SIDEDMATERIAL_IDCOLOR {HIDDEN;}

		SEPARATOR { LINE; }	
	
		GROUP
		{
			COLUMNS 2;
			
			BOOL VRAY2SIDEDMATERIAL_ISROUNDED {}
			REAL VRAY2SIDEDMATERIAL_ROUNDRADIUS {MIN 0;}

		}
 		
 		SEPARATOR { LINE; }

		BOOL VRAY2SIDEDMATERIAL_PAGE_PARAMS	{ PAGE; HIDDEN; PARENTMSG ID_VRAY2SIDEDMATERIALGROUP_PARAMS; }
		BOOL VRAY2SIDEDMATERIAL_PAGE_ILLUMINATION	{ PAGE; HIDDEN; PARENTMSG ID_VRAY2SIDEDMATERIALGROUP_ILLUMINATION; }
	}


	GROUP ID_VRAY2SIDEDMATERIALGROUP_PARAMS
	{
		LINK VRAY2SIDEDMATERIAL_PARAMS_LINK1 {}
		LINK VRAY2SIDEDMATERIAL_PARAMS_LINK2 {}

		SEPARATOR {LINE;}

		COLOR VRAY2SIDEDMATERIAL_PARAMS_TRANSLCOLOR { OPEN; }
		REAL VRAY2SIDEDMATERIAL_PARAMS_TRANSLCOLOR_MULT {MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
		SEPARATOR {}
		SHADERLINK VRAY2SIDEDMATERIAL_PARAMS_TRANSLSHADER { }
		LONG VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE {CYCLE{VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE_0; VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE_1; VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE_2; VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE_3; VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE_4; VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE_5; VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE_6; VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE_7; VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE_8; VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE_9; VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE_10; VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE_11; VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE_12;}}
		REAL VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
		SEPARATOR {}
		//BOOL VRAY2SIDEDMATERIAL_PARAMS_ONESIDED {}
	}

	GROUP ID_VRAY2SIDEDMATERIALGROUP_ILLUMINATION
	{
		SEPARATOR { }



	}

	INCLUDE Massign;

	LONG VRAY2SIDEDMATERIAL_NODE {HIDDEN;}
}
