 CONTAINER mVrayBumpMaterial
{
	NAME mVrayBumpMaterial;

	GROUP
	{
		MATPREVIEW VRAYBUMPMATERIAL_MAT_PREVIEW { OPEN; }
	}

	INCLUDE Mbase;

	GROUP Obaselist
	{
		SEPARATOR {LINE;}
		//BOOL VRAYBUMPMATERIAL_ANIMATEPREVIEW { }
		LONG VRAYBUMPMATERIAL_QUALITY
 		{
 			CYCLE
 			{
 				VRAYBUMPMATERIAL_QUALITY_0;
 				VRAYBUMPMATERIAL_QUALITY_1;
 				VRAYBUMPMATERIAL_QUALITY_2;
 			}
 		}

		LONG VRAYBUMPMATERIAL_PREVIEWSIZE
		{
			CYCLE
			{
				VRAYBUMPMATERIAL_PREVIEWSIZE_DEF;
				VRAYBUMPMATERIAL_PREVIEWSIZE_64;
				VRAYBUMPMATERIAL_PREVIEWSIZE_128;
				VRAYBUMPMATERIAL_PREVIEWSIZE_256;
				VRAYBUMPMATERIAL_PREVIEWSIZE_512;
				VRAYBUMPMATERIAL_PREVIEWSIZE_1024;
				VRAYBUMPMATERIAL_PREVIEWSIZE_2048;
			}
		}
		SEPARATOR { }

		REAL VRAYBUMPMATERIAL_GAMMA { HIDDEN; MIN 0; STEP 0.1; MAXSLIDER 2.2; CUSTOMGUI REALSLIDER; }

		SEPARATOR {LINE;}

		BOOL VRAYBUMPMATERIAL_OVERRIDABLE {}

 		SEPARATOR { LINE; }
		
		GROUP
		{
			COLUMNS 2;
			
			BOOL VRAYBUMPMATERIAL_ISROUNDED {}
			REAL VRAYBUMPMATERIAL_ROUNDRADIUS {MIN 0;}
		}

 		SEPARATOR { LINE; }

		BOOL VRAYBUMPMATERIAL_PAGE_PARAMS	{ PAGE; HIDDEN; PARENTMSG ID_VRAYBUMPMATERIALGROUP_PARAMS; }
		BOOL VRAYBUMPMATERIAL_PAGE_ILLUMINATION	{ PAGE; HIDDEN; PARENTMSG ID_VRAYBUMPMATERIALGROUP_ILLUMINATION; }
	}


	GROUP ID_VRAYBUMPMATERIALGROUP_PARAMS
	{
		LINK VRAYBUMPMATERIAL_BASEMTL {}
		
		LONG VRAYBUMPMATERIAL_TYPE
		{
			CYCLE
			{
				VRAYBUMPMATERIAL_TYPE_0;
				VRAYBUMPMATERIAL_TYPE_1;
				VRAYBUMPMATERIAL_TYPE_2;
				VRAYBUMPMATERIAL_TYPE_3;
				VRAYBUMPMATERIAL_TYPE_4;
			}
		}
		
		SEPARATOR {}
		
		SHADERLINK VRAYBUMPMATERIAL_SHADER { }
		BOOL VRAYBUMPMATERIAL_BUMPTEXINVERT {}
		
		SEPARATOR {}
		
		REAL VRAYBUMPMATERIAL_BUMPTEXMULT {UNIT METER; STEP 0.01;}
		REAL VRAYBUMPMATERIAL_DELTASCALE {MIN 0.001; MAX 2; STEP 0.01;}
	}

	GROUP ID_VRAYBUMPMATERIALGROUP_ILLUMINATION
	{
	
	}

	INCLUDE Massign;

	LONG VRAYBUMPMATERIAL_NODE {HIDDEN;}
}
