 CONTAINER mVrayCarPaintMaterial
{
	NAME mVrayCarPaintMaterial;

	GROUP
	{
		MATPREVIEW VRAYCARPAINTMATERIAL_MAT_PREVIEW { OPEN; }
	}

	INCLUDE Mbase;

	GROUP Obaselist
	{
		SEPARATOR {LINE;}
		LONG VRAYCARPAINTMATERIAL_QUALITY
 		{
 			CYCLE
 			{
 				VRAYCARPAINTMATERIAL_QUALITY_0;
 				VRAYCARPAINTMATERIAL_QUALITY_1;
 				VRAYCARPAINTMATERIAL_QUALITY_2;
 			}
 		}

 		SEPARATOR { }

		REAL VRAYCARPAINTMATERIAL_GAMMA { HIDDEN; MIN 0; STEP 0.1; MAXSLIDER 2.2; CUSTOMGUI REALSLIDER; }

		SEPARATOR {LINE;}

		BOOL VRAYCARPAINTMATERIAL_OVERRIDABLE {}

 		SEPARATOR { LINE; }
 		
		LONG VRAYCARPAINTMATERIAL_ID { MIN 0;}
 		COLOR VRAYCARPAINTMATERIAL_IDCOLOR { }


 		
 		GROUP
 		{
 			COLUMNS 2;
 			
 			BOOL VRAYCARPAINTMATERIAL_ISROUNDED {}
 			REAL VRAYCARPAINTMATERIAL_ROUNDRADIUS {MIN 0;}
 		}

 		SEPARATOR { LINE; }
 		
 		BOOL VRAYCARPAINTMATERIAL_PAGE_PARAMS	{ PAGE; HIDDEN; PARENTMSG ID_VRAYCARPAINTMATERIALGROUP_PARAMS; }
	}

 	GROUP ID_VRAYCARPAINTMATERIALGROUP_PARAMS
	{
	 	GROUP VRAYCARPAINTMATERIAL_BASEPANEL
		{
			DEFAULT 1;

			COLOR	VRAYCARPAINTMATERIAL_BASECOLOR {}
			SEPARATOR { }
			SHADERLINK VRAYCARPAINTMATERIAL_BASECOLORSHADER { }
			
			SEPARATOR {LINE;}
			
			SHADERLINK VRAYCARPAINTMATERIAL_BASEBUMPSHADER { }
			
			SEPARATOR {}
			
			REAL VRAYCARPAINTMATERIAL_BASEBUMPAMOUNT { MIN 0; STEP 0.01; CUSTOMGUI REALSLIDER;}
			SHADERLINK VRAYCARPAINTMATERIAL_BASEBUMPAMOUNTSHADER { }
			
			SEPARATOR {}
			
			LONG VRAYCARPAINTMATERIAL_BASEBUMPTYPE
 			{
 				CYCLE
 				{
 					VRAYCARPAINTMATERIAL_BASEBUMPTYPE_0;
 					VRAYCARPAINTMATERIAL_BASEBUMPTYPE_1;
 					VRAYCARPAINTMATERIAL_BASEBUMPTYPE_2;
 					VRAYCARPAINTMATERIAL_BASEBUMPTYPE_3;
 					VRAYCARPAINTMATERIAL_BASEBUMPTYPE_4;
 					VRAYCARPAINTMATERIAL_BASEBUMPTYPE_5;
 					VRAYCARPAINTMATERIAL_BASEBUMPTYPE_6;
 				}
 			}
 			
			SEPARATOR {LINE;}
			
			BOOL VRAYCARPAINTMATERIAL_BASETRACEREFLECTION {}
			SEPARATOR {}
			REAL VRAYCARPAINTMATERIAL_BASEREFLAMOUNT { MIN 0; STEP 0.01; MAX 1; CUSTOMGUI REALSLIDER;}
			SHADERLINK VRAYCARPAINTMATERIAL_BASEREFLAMOUNTSHADER { }
			
			SEPARATOR {}
			
			REAL VRAYCARPAINTMATERIAL_BASEREFLGLOSSINESS { MIN 0; STEP 0.01; MAX 1; CUSTOMGUI REALSLIDER;}
			SHADERLINK VRAYCARPAINTMATERIAL_BASEREFLGLOSSINESSSHADER { }
		}

		SEPARATOR { LINE; }
	 	
	 	GROUP VRAYCARPAINTMATERIAL_FLAKESPANEL
		{
			DEFAULT 1;
			
			COLOR VRAYCARPAINTMATERIAL_FLAKECOLOR {}
			SEPARATOR { }
			SHADERLINK VRAYCARPAINTMATERIAL_FLAKECOLORSHADER { }
			
			SEPARATOR {LINE;}
			
			REAL VRAYCARPAINTMATERIAL_FLAKEGLOSSINESS { MIN 0; STEP 0.01; MAX 1; CUSTOMGUI REALSLIDER;}
			SEPARATOR { }
			SHADERLINK VRAYCARPAINTMATERIAL_FLAKEGLOSSINESSSHADER { }
			
			SEPARATOR {LINE;}
			
			REAL VRAYCARPAINTMATERIAL_FLAKEORIENTATION { MIN 0; STEP 0.01; MAX 1; CUSTOMGUI REALSLIDER;}
			SEPARATOR { }
			SHADERLINK VRAYCARPAINTMATERIAL_FLAKEORIENTATIONSHADER { }
			
			SEPARATOR {LINE;}
			
			REAL VRAYCARPAINTMATERIAL_FLAKEDENSITY { MIN 0; STEP 0.01; MAX 5.0; CUSTOMGUI REALSLIDER;}
			REAL VRAYCARPAINTMATERIAL_FLAKESCALE { MIN 0; STEP 0.01; MAX 1; CUSTOMGUI REALSLIDER;}
			REAL VRAYCARPAINTMATERIAL_FLAKESIZE { MIN 0; STEP 0.01; MAX 1; CUSTOMGUI REALSLIDER;}
			LONG VRAYCARPAINTMATERIAL_FLAKEMAPSIZE { MIN 0; }
			LONG VRAYCARPAINTMATERIAL_FLAKESEED { MIN 0; }
			SEPARATOR {}
			LONG VRAYCARPAINTMATERIAL_FLAKEFILTERING
 			{
 				CYCLE
 				{
 					VRAYCARPAINTMATERIAL_FLAKEFILTERING_0;
 					VRAYCARPAINTMATERIAL_FLAKEFILTERING_1;
 				}
 			}
 			SEPARATOR {}
			LONG VRAYCARPAINTMATERIAL_FLAKEMAPTYPE
 			{
 				CYCLE
 				{
 					VRAYCARPAINTMATERIAL_FLAKEMAPTYPE_0;
 					VRAYCARPAINTMATERIAL_FLAKEMAPTYPE_1;
 				}
 			}
 			
 			SEPARATOR {}
 			
			BOOL VRAYCARPAINTMATERIAL_FLAKETRACEREFLECTION { }
		}
	
		SEPARATOR {LINE; }
		
		GROUP VRAYCARPAINTMATERIAL_COATPANEL
		{
			DEFAULT 1;
			
			COLOR VRAYCARPAINTMATERIAL_COATCOLOR {}
			SHADERLINK VRAYCARPAINTMATERIAL_COATCOLORSHADER { }
			
			SEPARATOR {LINE;}
			
			REAL VRAYCARPAINTMATERIAL_COATSTRENGTH { MIN 0; STEP 0.01; MAX 1; CUSTOMGUI REALSLIDER;}
			SHADERLINK VRAYCARPAINTMATERIAL_COATSTRENGTHSHADER { }
			
			SEPARATOR {LINE;}
			
			REAL VRAYCARPAINTMATERIAL_COATGLOSSINESS { MIN 0; STEP 0.01; MAX 1; CUSTOMGUI REALSLIDER; }
			SHADERLINK VRAYCARPAINTMATERIAL_COATGLOSSINESSSHADER { }
			
			SEPARATOR {LINE;}
			
			SHADERLINK VRAYCARPAINTMATERIAL_COATBUMPSHADER { }
			SEPARATOR {}
			REAL VRAYCARPAINTMATERIAL_COATBUMPAMOUNT { MIN 0; STEP 0.01; CUSTOMGUI REALSLIDER; }
			SHADERLINK VRAYCARPAINTMATERIAL_COATBUMPAMOUNTSHADER { }
			
			SEPARATOR {}
			
			LONG VRAYCARPAINTMATERIAL_COATBUMPTYPE
 			{
 				CYCLE
 				{
 					VRAYCARPAINTMATERIAL_COATBUMPTYPE_0;
 					VRAYCARPAINTMATERIAL_COATBUMPTYPE_1;
 					VRAYCARPAINTMATERIAL_COATBUMPTYPE_2;
 					VRAYCARPAINTMATERIAL_COATBUMPTYPE_3;
 					VRAYCARPAINTMATERIAL_COATBUMPTYPE_4;
 					VRAYCARPAINTMATERIAL_COATBUMPTYPE_5;
 					VRAYCARPAINTMATERIAL_COATBUMPTYPE_6;
 				}
 			}
 			
 			SEPARATOR {LINE;}
 			
			BOOL VRAYCARPAINTMATERIAL_COATTRACEREFLECTIONS { }
		}
		
		SEPARATOR { LINE; }
	
		GROUP VRAYCARPAINTMATERIAL_OPTIONSPANEL
		{
			DEFAULT 1;
			
			BOOL VRAYCARPAINTMATERIAL_TRACEREFLECTIONS { }
			BOOL VRAYCARPAINTMATERIAL_DOUBLESIDED { }
			LONG VRAYCARPAINTMATERIAL_SUBDIVS {MIN 0; MAXSLIDER 10; CUSTOMGUI LONGSLIDER;}
			REAL VRAYCARPAINTMATERIAL_CUTOFF {MIN 0; STEP 0.001; MAXSLIDER 0.1; CUSTOMGUI REALSLIDER;}
			
			SEPARATOR {LINE;}
			
			LONG VRAYCARPAINTMATERIAL_ENVPRIORITY {}
			SEPARATOR { }
			SHADERLINK VRAYCARPAINTMATERIAL_ENVOVERRIDESHADER { }
		}
	}
	
	INCLUDE Massign;
}
