#ifndef _MVrayDisplaceMaterial_H_
#define _MVrayDisplaceMaterial_H_

enum
{
	//ID_VRAYDISPLACEMATERIAL				= 1022593,

	VRAYDISPLACEMATERIAL_SKIPPAGL			= 6969,

	VRAYDISPLACEMATERIAL_MAT_PREVIEW		= 1001,

	// Presets
	VRAYDISPLACEMATERIAL_QUALITY							= 800,
	VRAYDISPLACEMATERIAL_QUALITY_0			= 0,
	VRAYDISPLACEMATERIAL_QUALITY_1			= 1,
	VRAYDISPLACEMATERIAL_QUALITY_2			= 2,

	//Disp on/off
	VRAYDISPLACEMATERIAL_USEDISP			= 1013,
	VRAYDISPLACEMATERIAL_USESUBD			= 1015,

	// Groups
	ID_VRAYDISPLACEMATERIALGROUP_PARAMS		= 850,
	VRAYDISPLACEMATERIAL_COMMON_PARAMS		= 900,
	VRAYDISPLACEMATERIAL_3D_PARAMS			= 901,
	VRAYDISPLACEMATERIAL_2D_PARAMS			= 902,

	// Use Bool Parameters
	VRAYDISPLACEMATERIAL_PAGE_PARAMS		= 2010,

	//VRAYDISPLACEMATERIAL_GLOBALS		= 800,
	//VRAYDISPLACEMATERIAL_COLOR		= 801,

	VRAYDISPLACEMATERIAL_ON				= 1006,
	VRAYDISPLACEMATERIAL_USEGLOBALS		= 1000,
	VRAYDISPLACEMATERIAL_TYPE			= 1030,
	VRAYDISPLACEMATERIAL_TYPE_0			= 0,
	VRAYDISPLACEMATERIAL_TYPE_1			= 1,
	VRAYDISPLACEMATERIAL_TEXTURE		= 1012,
	VRAYDISPLACEMATERIAL_TEXTURE_TYPE	= 1014,
	VRAYDISPLACEMATERIAL_TEXTURE_TYPE_0	= 0,
	VRAYDISPLACEMATERIAL_TEXTURE_TYPE_1	= 1,
	VRAYDISPLACEMATERIAL_FILTERTEX		= 1032,
	VRAYDISPLACEMATERIAL_FILTERBLUR		= 1033,
	VRAYDISPLACEMATERIAL_AMOUNT			= 1002,
	VRAYDISPLACEMATERIAL_SHIFT			= 1003,
	VRAYDISPLACEMATERIAL_VIEWDEP		= 1004,
	VRAYDISPLACEMATERIAL_EDGELENGTH		= 1010,
	VRAYDISPLACEMATERIAL_MAXSUBDIV		= 1005,
	VRAYDISPLACEMATERIAL_KEEP			= 1011,
	VRAYDISPLACEMATERIAL_USEWATERLEVEL  = 1019,
	VRAYDISPLACEMATERIAL_WATERLEVEL     = 1020,
	VRAYDISPLACEMATERIAL_VECTOR			= 1040,
	VRAYDISPLACEMATERIAL_TBOUNDS2D		= 1041,
	VRAYDISPLACEMATERIAL_TBOUNDS3D		= 1042,
	VRAYDISPLACEMATERIAL_RESOLUTION		= 1043,
	VRAYDISPLACEMATERIAL_PRECISION		= 1044,
	VRAYDISPLACEMATERIAL_USEMAPBOUNDS	= 1045,
	VRAYDISPLACEMATERIAL_TEXMIN			= 1046,
	VRAYDISPLACEMATERIAL_TEXMAX			= 1047,
	VRAYDISPLACEMATERIAL_TITLEBAR		= 1500,

	VRAYDISPLACEMATERIAL_USED = 5000,
	VRAYDISPLACEMATERIAL_NODE = 5200,
};

#endif
