 CONTAINER mVrayOverrideMaterial
{
	NAME mVrayOverrideMaterial;

	GROUP
	{
		MATPREVIEW VRAYOVERRIDEMATERIAL_MAT_PREVIEW { OPEN; }
	}

	INCLUDE Mbase;

	GROUP Obaselist
	{
		SEPARATOR {LINE;}
		//BOOL VRAYOVERRIDEMATERIAL_ANIMATEPREVIEW { }
		LONG VRAYOVERRIDEMATERIAL_QUALITY
 		{
 			CYCLE
 			{
 				VRAYOVERRIDEMATERIAL_QUALITY_0;
 				VRAYOVERRIDEMATERIAL_QUALITY_1;
 				VRAYOVERRIDEMATERIAL_QUALITY_2;
 			}
 		}

		LONG VRAYOVERRIDEMATERIAL_PREVIEWSIZE
		{
			CYCLE
			{
				VRAYOVERRIDEMATERIAL_PREVIEWSIZE_DEF;
				VRAYOVERRIDEMATERIAL_PREVIEWSIZE_64;
				VRAYOVERRIDEMATERIAL_PREVIEWSIZE_128;
				VRAYOVERRIDEMATERIAL_PREVIEWSIZE_256;
				VRAYOVERRIDEMATERIAL_PREVIEWSIZE_512;
				VRAYOVERRIDEMATERIAL_PREVIEWSIZE_1024;
				VRAYOVERRIDEMATERIAL_PREVIEWSIZE_2048;
			}
		}
		SEPARATOR { }

		REAL VRAYOVERRIDEMATERIAL_GAMMA { HIDDEN; MIN 0; STEP 0.1; MAXSLIDER 2.2; CUSTOMGUI REALSLIDER; }

		SEPARATOR {LINE;}

		BOOL VRAYOVERRIDEMATERIAL_OVERRIDABLE {}

 		SEPARATOR { LINE; }
		
		GROUP
		{
			COLUMNS 2;
			
			BOOL VRAYOVERRIDEMATERIAL_ISROUNDED {}
			REAL VRAYOVERRIDEMATERIAL_ROUNDRADIUS {MIN 0;}
		}

 		SEPARATOR { LINE; }

		BOOL VRAYOVERRIDEMATERIAL_PAGE_PARAMS	{ PAGE; HIDDEN; PARENTMSG ID_VRAYOVERRIDEMATERIALGROUP_PARAMS; }
		BOOL VRAYOVERRIDEMATERIAL_PAGE_ILLUMINATION	{ PAGE; HIDDEN; PARENTMSG ID_VRAYOVERRIDEMATERIALGROUP_ILLUMINATION; }
	}


	GROUP ID_VRAYOVERRIDEMATERIALGROUP_PARAMS
	{
		LINK VRAYOVERRIDEMATERIAL_PARAMS_LINK1 {}

		SEPARATOR {LINE;}

		LINK VRAYOVERRIDEMATERIAL_PARAMS_LINK2 {}

		SEPARATOR {LINE;}

		LINK VRAYOVERRIDEMATERIAL_PARAMS_LINK3 {}

		SEPARATOR {LINE;}

		LINK VRAYOVERRIDEMATERIAL_PARAMS_LINK4 {}

		SEPARATOR {LINE;}

		LINK VRAYOVERRIDEMATERIAL_PARAMS_LINK5 {}

        SEPARATOR {LINE;}

        SHADERLINK VRAYOVERRIDEMATERIAL_PARAMS_ENVTEX {}
        LONG VRAYOVERRIDEMATERIAL_PARAMS_ENVMAPTYPE
        {
        	CYCLE
        	{
        		VRAYOVERRIDEMATERIAL_PARAMS_ENVMAPTYPE_0;
        		VRAYOVERRIDEMATERIAL_PARAMS_ENVMAPTYPE_1;
        		VRAYOVERRIDEMATERIAL_PARAMS_ENVMAPTYPE_2;
        		VRAYOVERRIDEMATERIAL_PARAMS_ENVMAPTYPE_3;
        		VRAYOVERRIDEMATERIAL_PARAMS_ENVMAPTYPE_4;
        	}
        }
        GROUP
        {
        	LAYOUTGROUP; COLUMNS 2;
        	GROUP
        	{
        		REAL VRAYOVERRIDEMATERIAL_PARAMS_ENVROTU {UNIT DEGREE; MIN 0;}    		
        	}
        	GROUP
        	{
        		REAL VRAYOVERRIDEMATERIAL_PARAMS_ENVROTV {UNIT DEGREE; MIN 0;}
        	}
        }
        SEPARATOR {}
        LONG VRAYOVERRIDEMATERIAL_PARAMS_ENVPRIORITY {MIN 0;}
              

	}

	GROUP ID_VRAYOVERRIDEMATERIALGROUP_ILLUMINATION
	{
		SEPARATOR { }



	}

	INCLUDE Massign;

	LONG VRAYOVERRIDEMATERIAL_NODE {HIDDEN;}
}
