#ifndef _MVrayBlendMaterial_H_
#define _MVrayBlendMaterial_H_

enum
{
	//ID_VRAYBLENDMATERIAL								= 1022116,

	VRAYBLENDMATERIAL_SKIPPAGL							= 6969,

	// Preview
	VRAYBLENDMATERIAL_PREVIEWSIZE						= 500,
	VRAYBLENDMATERIAL_PREVIEWSIZE_DEF						= 0,
	VRAYBLENDMATERIAL_PREVIEWSIZE_64							= 6,
	VRAYBLENDMATERIAL_PREVIEWSIZE_128						= 7,
	VRAYBLENDMATERIAL_PREVIEWSIZE_256						= 8,
	VRAYBLENDMATERIAL_PREVIEWSIZE_512						= 9,
	VRAYBLENDMATERIAL_PREVIEWSIZE_1024						= 10,
	VRAYBLENDMATERIAL_PREVIEWSIZE_2048						= 11,

	VRAYBLENDMATERIAL_ANIMATEPREVIEW						= 501,

	ID_VRAYBLENDMATERIALGROUP_ILLUMINATION				= 820,
	VRAYBLENDMATERIAL_PAGE_ILLUMINATION					= 821,

	VRAYBLENDMATERIAL_MAT_PREVIEW						= 1001,

	// Presets
	VRAYBLENDMATERIAL_QUALITY							= 800,
	VRAYBLENDMATERIAL_QUALITY_0						= 0,
	VRAYBLENDMATERIAL_QUALITY_1						= 1,
	VRAYBLENDMATERIAL_QUALITY_2						= 2,

	VRAYBLENDMATERIAL_GAMMA							= 810,

	VRAYBLENDMATERIAL_OVERRIDABLE                  				= 811,
	VRAYBLENDMATERIAL_IDCOLOR						,
	VRAYBLENDMATERIAL_ISROUNDED						,
	VRAYBLENDMATERIAL_ROUNDRADIUS						,

	// Groups
	ID_VRAYBLENDMATERIALGROUP_PARAMS					= 850,

	// Use Bool Parameters
	VRAYBLENDMATERIAL_PAGE_PARAMS						= 3010,

	// Params
	VRAYBLENDMATERIAL_PARAMS_MATNUM						= 3100,
	VRAYBLENDMATERIAL_PARAMS_LINK1						,
	VRAYBLENDMATERIAL_PARAMS_LINK2						,
	VRAYBLENDMATERIAL_PARAMS_LINK3						,
	VRAYBLENDMATERIAL_PARAMS_LINK4						,
	VRAYBLENDMATERIAL_PARAMS_LINK5						,
	VRAYBLENDMATERIAL_PARAMS_LINK6						,
	VRAYBLENDMATERIAL_PARAMS_LINK7						,
	VRAYBLENDMATERIAL_PARAMS_LINK8						,
	VRAYBLENDMATERIAL_PARAMS_LINK9						,
	VRAYBLENDMATERIAL_PARAMS_LINK10						,

	VRAYBLENDMATERIAL_PARAMS_USELINK1					,
	VRAYBLENDMATERIAL_PARAMS_USELINK2					,
	VRAYBLENDMATERIAL_PARAMS_USELINK3					,
	VRAYBLENDMATERIAL_PARAMS_USELINK4					,
	VRAYBLENDMATERIAL_PARAMS_USELINK5					,
	VRAYBLENDMATERIAL_PARAMS_USELINK6					,
	VRAYBLENDMATERIAL_PARAMS_USELINK7					,
	VRAYBLENDMATERIAL_PARAMS_USELINK8					,
	VRAYBLENDMATERIAL_PARAMS_USELINK9					,
	VRAYBLENDMATERIAL_PARAMS_USELINK10					,

	VRAYBLENDMATERIAL_USED								= 5000,
	VRAYBLENDMATERIAL_NODE								= 5200,
};

#endif
