#ifndef _MVrayBumpMaterial_H_
#define _MVrayBumpMaterial_H_

enum
{
	//ID_VRAYBUMPMATERIAL								= 1032210,

	VRAYBUMPMATERIAL_SKIPPAGL							= 6969,

	// Preview
	VRAYBUMPMATERIAL_PREVIEWSIZE						= 500,
	VRAYBUMPMATERIAL_PREVIEWSIZE_DEF						= 0,
	VRAYBUMPMATERIAL_PREVIEWSIZE_64							= 6,
	VRAYBUMPMATERIAL_PREVIEWSIZE_128						= 7,
	VRAYBUMPMATERIAL_PREVIEWSIZE_256						= 8,
	VRAYBUMPMATERIAL_PREVIEWSIZE_512						= 9,
	VRAYBUMPMATERIAL_PREVIEWSIZE_1024						= 10,
	VRAYBUMPMATERIAL_PREVIEWSIZE_2048						= 11,

	VRAYBUMPMATERIAL_ANIMATEPREVIEW						= 501,

	ID_VRAYBUMPMATERIALGROUP_ILLUMINATION				= 820,
	VRAYBUMPMATERIAL_PAGE_ILLUMINATION					= 821,

	VRAYBUMPMATERIAL_MAT_PREVIEW						= 1001,

	// Presets
	VRAYBUMPMATERIAL_QUALITY							= 800,
	VRAYBUMPMATERIAL_QUALITY_0						= 0,
	VRAYBUMPMATERIAL_QUALITY_1						= 1,
	VRAYBUMPMATERIAL_QUALITY_2						= 2,

	VRAYBUMPMATERIAL_GAMMA							= 810,

	VRAYBUMPMATERIAL_OVERRIDABLE                    			= 811,
	VRAYBUMPMATERIAL_ISROUNDED						,
	VRAYBUMPMATERIAL_ROUNDRADIUS					,

	// Groups
	ID_VRAYBUMPMATERIALGROUP_PARAMS					= 850,

	// Use Bool Parameters
	VRAYBUMPMATERIAL_PAGE_PARAMS						= 4010,

	// Params
	VRAYBUMPMATERIAL_BASEMTL                            = 4100,
	VRAYBUMPMATERIAL_BUMPTEXMULT						,
	VRAYBUMPMATERIAL_BUMPTEXINVERT						,
	VRAYBUMPMATERIAL_DELTASCALE							,
	VRAYBUMPMATERIAL_TYPE								= 4150,
	VRAYBUMPMATERIAL_TYPE_0								= 0,
	VRAYBUMPMATERIAL_TYPE_1								= 1,
	VRAYBUMPMATERIAL_TYPE_2								= 2,
	VRAYBUMPMATERIAL_TYPE_3								= 3,
	VRAYBUMPMATERIAL_TYPE_4								= 4,
	
	VRAYBUMPMATERIAL_SHADER                             = 4500,

	VRAYBUMPMATERIAL_USED								= 5000,
	VRAYBUMPMATERIAL_NODE								= 5200,
};

#endif
