#ifndef _MVray2SidedMaterial_H_
#define _MVray2SidedMaterial_H_

enum
{
	//ID_VRAY2SIDEDMATERIAL								= 1022115,

	VRAY2SIDEDMATERIAL_SKIPPAGL							= 6969,

	// Preview
	VRAY2SIDEDMATERIAL_PREVIEWSIZE						= 500,
	VRAY2SIDEDMATERIAL_PREVIEWSIZE_DEF						= 0,
	VRAY2SIDEDMATERIAL_PREVIEWSIZE_64							= 6,
	VRAY2SIDEDMATERIAL_PREVIEWSIZE_128						= 7,
	VRAY2SIDEDMATERIAL_PREVIEWSIZE_256						= 8,
	VRAY2SIDEDMATERIAL_PREVIEWSIZE_512						= 9,
	VRAY2SIDEDMATERIAL_PREVIEWSIZE_1024						= 10,
	VRAY2SIDEDMATERIAL_PREVIEWSIZE_2048						= 11,

	VRAY2SIDEDMATERIAL_ANIMATEPREVIEW						= 501,

	ID_VRAY2SIDEDMATERIALGROUP_ILLUMINATION				= 820,
	VRAY2SIDEDMATERIAL_PAGE_ILLUMINATION					= 821,

	VRAY2SIDEDMATERIAL_MAT_PREVIEW						= 1001,

	// Presets
	VRAY2SIDEDMATERIAL_QUALITY							= 800,
	VRAY2SIDEDMATERIAL_QUALITY_0						= 0,
	VRAY2SIDEDMATERIAL_QUALITY_1						= 1,
	VRAY2SIDEDMATERIAL_QUALITY_2						= 2,

	VRAY2SIDEDMATERIAL_GAMMA					= 810,
	VRAY2SIDEDMATERIAL_OVERRIDABLE                      		,
	VRAY2SIDEDMATERIAL_IDCOLOR					,
	VRAY2SIDEDMATERIAL_ISROUNDED					,
	VRAY2SIDEDMATERIAL_ROUNDRADIUS					,
    VRAY2SIDEDMATERIAL_ID								,

	// Groups
	ID_VRAY2SIDEDMATERIALGROUP_PARAMS					= 850,

	// Use Bool Parameters
	VRAY2SIDEDMATERIAL_PAGE_PARAMS						= 2010,

	// Params
	VRAY2SIDEDMATERIAL_PARAMS_LINK1						= 2100,
	VRAY2SIDEDMATERIAL_PARAMS_LINK2						,
	VRAY2SIDEDMATERIAL_PARAMS_TRANSLCOLOR				,
	VRAY2SIDEDMATERIAL_PARAMS_TRANSLCOLOR_MULT			,
	VRAY2SIDEDMATERIAL_PARAMS_TRANSLSHADER				,
	VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMULT				,
	VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE			,
	VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE_0		= 0,
	VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE_1		= 1,
	VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE_2		= 2,
	VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE_3		= 3,
	VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE_4		= 4,
	VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE_5		= 5,
	VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE_6		= 6,
	VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE_7		= 7,
	VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE_8		= 8,
	VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE_9		= 9,
	VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE_10		= 10,
	VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE_11		= 11,
	VRAY2SIDEDMATERIAL_PARAMS_TRANSLTEXMIXMODE_12		= 12,
	//VRAY2SIDEDMATERIAL_PARAMS_ONESIDED					,


	VRAY2SIDEDMATERIAL_USED = 5000,
	VRAY2SIDEDMATERIAL_NODE = 5200,
};

#endif
