#ifndef _MVrayOverrideMaterial_H_
#define _MVrayOverrideMaterial_H_

enum
{
	//ID_VRAYOVERRIDEMATERIAL								= 1023126,

	VRAYOVERRIDEMATERIAL_SKIPPAGL							= 6969,

	// Preview
	VRAYOVERRIDEMATERIAL_PREVIEWSIZE						= 500,
	VRAYOVERRIDEMATERIAL_PREVIEWSIZE_DEF						= 0,
	VRAYOVERRIDEMATERIAL_PREVIEWSIZE_64							= 6,
	VRAYOVERRIDEMATERIAL_PREVIEWSIZE_128						= 7,
	VRAYOVERRIDEMATERIAL_PREVIEWSIZE_256						= 8,
	VRAYOVERRIDEMATERIAL_PREVIEWSIZE_512						= 9,
	VRAYOVERRIDEMATERIAL_PREVIEWSIZE_1024						= 10,
	VRAYOVERRIDEMATERIAL_PREVIEWSIZE_2048						= 11,

	VRAYOVERRIDEMATERIAL_ANIMATEPREVIEW						= 501,

	ID_VRAYOVERRIDEMATERIALGROUP_ILLUMINATION				= 820,
	VRAYOVERRIDEMATERIAL_PAGE_ILLUMINATION					= 821,

	VRAYOVERRIDEMATERIAL_MAT_PREVIEW						= 1001,

	// Presets
	VRAYOVERRIDEMATERIAL_QUALITY							= 800,
	VRAYOVERRIDEMATERIAL_QUALITY_0						= 0,
	VRAYOVERRIDEMATERIAL_QUALITY_1						= 1,
	VRAYOVERRIDEMATERIAL_QUALITY_2						= 2,

	VRAYOVERRIDEMATERIAL_GAMMA							= 810,

	VRAYOVERRIDEMATERIAL_OVERRIDABLE                    			= 811,
	VRAYOVERRIDEMATERIAL_ISROUNDED						,
	VRAYOVERRIDEMATERIAL_ROUNDRADIUS					,

	// Groups
	ID_VRAYOVERRIDEMATERIALGROUP_PARAMS					= 850,

	// Use Bool Parameters
	VRAYOVERRIDEMATERIAL_PAGE_PARAMS						= 4010,

	// Params
	VRAYOVERRIDEMATERIAL_PARAMS_LINK1						= 4100,
	VRAYOVERRIDEMATERIAL_PARAMS_LINK2						,
	VRAYOVERRIDEMATERIAL_PARAMS_LINK3						,
	VRAYOVERRIDEMATERIAL_PARAMS_LINK4						,
	VRAYOVERRIDEMATERIAL_PARAMS_LINK5						,



	VRAYOVERRIDEMATERIAL_PARAMS_ENVMAPTYPE					= 4150,
	VRAYOVERRIDEMATERIAL_PARAMS_ENVMAPTYPE_0				= 0,
	VRAYOVERRIDEMATERIAL_PARAMS_ENVMAPTYPE_1				= 1,
	VRAYOVERRIDEMATERIAL_PARAMS_ENVMAPTYPE_2				= 2,
	VRAYOVERRIDEMATERIAL_PARAMS_ENVMAPTYPE_3				= 3,
	VRAYOVERRIDEMATERIAL_PARAMS_ENVMAPTYPE_4				= 4,
	VRAYOVERRIDEMATERIAL_PARAMS_ENVROTU						= 4160,
	VRAYOVERRIDEMATERIAL_PARAMS_ENVROTV						,
	VRAYOVERRIDEMATERIAL_PARAMS_ENVPRIORITY					= 4170,

	VRAYOVERRIDEMATERIAL_PARAMS_ENVTEX						= 4500,

	VRAYOVERRIDEMATERIAL_USED								= 5000,
	VRAYOVERRIDEMATERIAL_NODE								= 5200,
};

#endif
