 CONTAINER mVrayDisplaceMaterial
{
	NAME mVrayDisplaceMaterial;

	GROUP
	{
		MATPREVIEW VRAYDISPLACEMATERIAL_MAT_PREVIEW { OPEN; }
	}

	INCLUDE MBase;

	GROUP Obaselist
	{
		SEPARATOR {LINE;}
		LONG VRAYDISPLACEMATERIAL_QUALITY
 		{
 			CYCLE
 			{
 				VRAYDISPLACEMATERIAL_QUALITY_0;
 				VRAYDISPLACEMATERIAL_QUALITY_1;
 				VRAYDISPLACEMATERIAL_QUALITY_2;
 			}
 		}

 		BOOL VRAYDISPLACEMATERIAL_USEDISP {}
 		BOOL VRAYDISPLACEMATERIAL_USESUBD {}

 		BOOL VRAYDISPLACEMATERIAL_PAGE_PARAMS	{ PAGE; HIDDEN; PARENTMSG ID_VRAYDISPLACEMATERIALGROUP_PARAMS; }
 	}

 	GROUP ID_VRAYDISPLACEMATERIALGROUP_PARAMS
	{
		//BOOL VRAYDISPLACEMATERIAL_ON {}
		
		GROUP VRAYDISPLACEMATERIAL_COMMON_PARAMS
		{
			DEFAULT 1;

			GROUP
			{		
				LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					LONG VRAYDISPLACEMATERIAL_TYPE
					{
						CYCLE
						{
							VRAYDISPLACEMATERIAL_TYPE_0;
							VRAYDISPLACEMATERIAL_TYPE_1;
						}
					}
					
					REAL VRAYDISPLACEMATERIAL_AMOUNT {UNIT METER; STEP 0.01;}			
					REAL VRAYDISPLACEMATERIAL_SHIFT { UNIT METER; STEP 0.01;}
					BOOL VRAYDISPLACEMATERIAL_USEWATERLEVEL {}
					REAL VRAYDISPLACEMATERIAL_WATERLEVEL {UNIT METER; STEP 0.01;}
				}
				GROUP
				{
					SHADERLINK VRAYDISPLACEMATERIAL_TEXTURE {}
					LONG VRAYDISPLACEMATERIAL_TEXTURE_TYPE
					{
						CYCLE
						{
							VRAYDISPLACEMATERIAL_TEXTURE_TYPE_0;
							VRAYDISPLACEMATERIAL_TEXTURE_TYPE_1;
						}
					}
					//BOOL VRAYDISPLACEMATERIAL_FILTERTEX {}
					//REAL VRAYDISPLACEMATERIAL_FILTERBLUR {MIN 0.001; MAX 1.0; STEP 0.001; CUSTOMGUI REALSLIDER;}				
				}
			}
		}
		
		GROUP VRAYDISPLACEMATERIAL_2D_PARAMS
		{
			DEFAULT 1;
	
			LONG VRAYDISPLACEMATERIAL_RESOLUTION {MIN 1; MAXSLIDER 512;}
			LONG VRAYDISPLACEMATERIAL_PRECISION {MIN 0; MAXSLIDER 10;}
			BOOL VRAYDISPLACEMATERIAL_TBOUNDS2D {}
		}

		GROUP VRAYDISPLACEMATERIAL_3D_PARAMS
		{
			DEFAULT 1;
			
			BOOL VRAYDISPLACEMATERIAL_USEGLOBALS {}
	
			SEPARATOR {}
	
			BOOL VRAYDISPLACEMATERIAL_VIEWDEP {}
			REAL VRAYDISPLACEMATERIAL_EDGELENGTH {MIN 0; STEP 0.1;}
			LONG VRAYDISPLACEMATERIAL_MAXSUBDIV {MIN 2;}
			BOOL VRAYDISPLACEMATERIAL_KEEP {}
			BOOL VRAYDISPLACEMATERIAL_TBOUNDS3D {}
			BOOL VRAYDISPLACEMATERIAL_VECTOR {}
			BOOL VRAYDISPLACEMATERIAL_USEMAPBOUNDS {}
			REAL VRAYDISPLACEMATERIAL_TEXMIN { MIN -1; MAX 1; STEP 0.1; }
			REAL VRAYDISPLACEMATERIAL_TEXMAX { MIN -1; MAX 1; STEP 0.1; }
		}
	}
	
	INCLUDE Massign;
}
