#ifndef _MVrayHairMaterial_H_
#define _MVrayHairMaterial_H_

enum
{
	//ID_VRAYHAIRMATERIAL = 1029537,

	VRAYHAIRMATERIAL_SKIPPAGL = 6969,

	// Preview
	VRAYHAIRMATERIAL_PREVIEWSIZE = 500,
	VRAYHAIRMATERIAL_PREVIEWSIZE_DEF = 0,
	VRAYHAIRMATERIAL_PREVIEWSIZE_64 = 6,
	VRAYHAIRMATERIAL_PREVIEWSIZE_128 = 7,
	VRAYHAIRMATERIAL_PREVIEWSIZE_256 = 8,
	VRAYHAIRMATERIAL_PREVIEWSIZE_512 = 9,
	VRAYHAIRMATERIAL_PREVIEWSIZE_1024 = 10,
	VRAYHAIRMATERIAL_PREVIEWSIZE_2048 = 11,

	VRAYHAIRMATERIAL_ANIMATEPREVIEW = 501,

	ID_VRAYHAIRMATERIALGROUP_ILLUMINATION = 820,
	VRAYHAIRMATERIAL_PAGE_ILLUMINATION = 821,

	VRAYHAIRMATERIAL_MAT_PREVIEW = 1001,

	// Groups
	ID_VRAYHAIRMATERIALGROUP_PARAMS = 850,

	// Use Bool Parameters
	VRAYHAIRMATERIAL_PAGE_PARAMS = 2010,

	// Presets
	VRAYHAIRMATERIAL_PRESETS = 800,
	VRAYHAIRMATERIAL_PRESETS00 = 0,
	VRAYHAIRMATERIAL_PRESETS01 = 1,
	VRAYHAIRMATERIAL_PRESETS02 = 2,
	VRAYHAIRMATERIAL_PRESETS03 = 3,
	VRAYHAIRMATERIAL_PRESETS04 = 4,
	VRAYHAIRMATERIAL_PRESETS05 = 5,
	VRAYHAIRMATERIAL_SAVEPRESET = 801,

	VRAYHAIRMATERIAL_QUALITY = 806,
	VRAYHAIRMATERIAL_QUALITY_0 = 0,
	VRAYHAIRMATERIAL_QUALITY_1 = 1,
	VRAYHAIRMATERIAL_QUALITY_2 = 2,
	VRAYHAIRMATERIAL_GAMMA = 810,
	VRAYHAIRMATERIAL_OVERRIDABLE = 	811,
	VRAYHAIRMATERIAL_IDCOLOR  		,
	VRAYHAIRMATERIAL_ISROUNDED		,
	VRAYHAIRMATERIAL_ROUNDRADIUS	,
    VRAYHAIRMATERIAL_ID             ,
    
    // PANELS IDs
	VRAYHAIRMATERIAL_BASEPANEL = 4040,
	VRAYHAIRMATERIAL_SPECULARPANEL,
	VRAYHAIRMATERIAL_TRANSMISSIONPANEL,
	VRAYHAIRMATERIAL_OPTIONSPANEL,

	// Hairs
	VRAYHAIRMATERIAL_OVERALLCOLOR = 4055,
	VRAYHAIRMATERIAL_TRANSPARENCY,
	VRAYHAIRMATERIAL_DIFFUSECOLOR,
	VRAYHAIRMATERIAL_DIFFUSEAMOUNT,
	VRAYHAIRMATERIAL_SPECULAR1COLOR,
	VRAYHAIRMATERIAL_SPECULAR1AMOUNT,
	VRAYHAIRMATERIAL_SPECULAR1GLOSSINESS,
	VRAYHAIRMATERIAL_SPECULAR2COLOR,
	VRAYHAIRMATERIAL_SPECULAR2AMOUNT,
	VRAYHAIRMATERIAL_SPECULAR2GLOSSINESS,
	VRAYHAIRMATERIAL_SPECULAR2LOCK,
	VRAYHAIRMATERIAL_TRANSMISSIONCOLOR,
	VRAYHAIRMATERIAL_TRANSMISSIONAMOUNT,
    VRAYHAIRMATERIAL_TRANSMISSIOGLOSSINESSLENGHT,
	VRAYHAIRMATERIAL_TRANSMISSIOGLOSSINESSWIDTH,
	VRAYHAIRMATERIAL_OPAQUEFORSHADOW,
	VRAYHAIRMATERIAL_OPAQUEFORGI,
	VRAYHAIRMATERIAL_SIMPLIFYFORGI,
	VRAYHAIRMATERIAL_USECACHEDGI,
	VRAYHAIRMATERIAL_USEHAIRCOLORDATA,

	// Shaders
	VRAYHAIRMATERIAL_OVERALLCOLORSHADER = 4100,
	VRAYHAIRMATERIAL_TRANSPARENCYSHADER,
	VRAYHAIRMATERIAL_DIFFUSECOLORSHADER,
	VRAYHAIRMATERIAL_DIFFUSEAMOUNTSHADER,
	VRAYHAIRMATERIAL_SPECULAR1COLORSHADER,
	VRAYHAIRMATERIAL_SPECULAR1AMOUNTSHADER,
	VRAYHAIRMATERIAL_SPECULAR1GLOSSINESSSHADER,
	VRAYHAIRMATERIAL_SPECULAR2COLORSHADER,
	VRAYHAIRMATERIAL_SPECULAR2AMOUNTSHADER,
    VRAYHAIRMATERIAL_SPECULAR2GLOSSINESSSHADER,
    VRAYHAIRMATERIAL_TRANSMISSIONCOLORSHADER,
    VRAYHAIRMATERIAL_TRANSMISSIONAMOUNTSHADER,
    VRAYHAIRMATERIAL_TRANSMISSIOGLOSSINESSLENGHTSHADER,
    VRAYHAIRMATERIAL_TRANSMISSIOGLOSSINESSWIDTHSHADER,

	VRAYHAIRMATERIAL_USED = 5000,
	VRAYHAIRMATERIAL_XREF_FILENAME = 5001,
	VRAYHAIRMATERIAL_NODE = 5200,

	// virtual ID
	VRAYHAIRMATERIAL_SPECULARPREVIEW = 8050
};

#endif
