 CONTAINER mVrayFastSSS2Material
{
	NAME mVrayFastSSS2Material;

	GROUP
	{
		MATPREVIEW VRAYFASTSSS2MATERIAL_MAT_PREVIEW { OPEN; }
	}

	INCLUDE Mbase;

	GROUP Obaselist
	{
		SEPARATOR {LINE;}
		LONG VRAYFASTSSS2MATERIAL_QUALITY
 		{
 			CYCLE
 			{
 				VRAYFASTSSS2MATERIAL_QUALITY_0;
 				VRAYFASTSSS2MATERIAL_QUALITY_1;
 				VRAYFASTSSS2MATERIAL_QUALITY_2;
 			}
 		}

 		SEPARATOR { }

		REAL VRAYFASTSSS2MATERIAL_GAMMA { HIDDEN; MIN 0; STEP 0.1; MAXSLIDER 2.2; CUSTOMGUI REALSLIDER; }

		SEPARATOR {LINE;}

		BOOL VRAYFASTSSS2MATERIAL_OVERRIDABLE {}

 		SEPARATOR { LINE; }
 		
		LONG VRAYFASTSSS2MATERIAL_ID {MIN 0;}
 		COLOR VRAYFASTSSS2MATERIAL_IDCOLOR { }

		GROUP
		{
			COLUMNS 2;
			
			BOOL VRAYFASTSSS2MATERIAL_ISROUNDED {}
			REAL VRAYFASTSSS2MATERIAL_ROUNDRADIUS {MIN 0;}
		}

 		SEPARATOR { LINE; }
 		
 		BOOL VRAYFASTSSS2MATERIAL_PAGE_PARAMS	{ PAGE; HIDDEN; PARENTMSG ID_VRAYFASTSSS2MATERIALGROUP_PARAMS; }
	}

 	GROUP ID_VRAYFASTSSS2MATERIALGROUP_PARAMS
	{
	 	GROUP VRAYFASTSSS2MATERIAL_SSS_GENPANEL
		{
			DEFAULT 1;

			BOOL VRAYFASTSSS2MATERIAL_SSS_GEOMSAMPLING {}
			LONG VRAYFASTSSS2MATERIAL_SSS_PREPASS {MINSLIDER -4; MAXSLIDER 4; CUSTOMGUI LONGSLIDER;}
			LONG VRAYFASTSSS2MATERIAL_SSS_PREPASSID {MIN 0;}
			REAL VRAYFASTSSS2MATERIAL_SSS_SCALE {MIN 0; MAXSLIDER 5; STEP 0.01; CUSTOMGUI REALSLIDER;}
            REAL VRAYFASTSSS2MATERIAL_SSS_IOR {MIN 1; STEP 0.01;}
            BOOL VRAYFASTSSS2MATERIAL_SSS_AUTODENSITY {}
            REAL VRAYFASTSSS2MATERIAL_SSS_SURFACEOFFSET {MIN 0.001; STEP 0.001;}
            REAL VRAYFASTSSS2MATERIAL_SSS_SAMPLESPERUNITAREA {MIN 0.1; STEP 0.1;}
            BOOL VRAYFASTSSS2MATERIAL_SSS_PREVIEWSAMPLES {}
            REAL VRAYFASTSSS2MATERIAL_SSS_MAXDISTANCE {MIN 0.01; STEP 0.01;}
            COLOR VRAYFASTSSS2MATERIAL_SSS_BGCOLOR {}
            COLOR VRAYFASTSSS2MATERIAL_SSS_SAMPLESCOLOR {}

		}

		SEPARATOR { LINE; }
	 	
	 	GROUP VRAYFASTSSS2MATERIAL_SSS_SCATTERPANEL
		{
			DEFAULT 1;
	
			COLOR	VRAYFASTSSS2MATERIAL_SSS_OVERALLCOLOR {}
			SEPARATOR { }
			SHADERLINK VRAYFASTSSS2MATERIAL_SSS_OVERALLCOLORSHADER { }
			SEPARATOR {LINE;}
			COLOR VRAYFASTSSS2MATERIAL_SSS_DIFFUSECOLOR {}
			SEPARATOR { }
			SHADERLINK VRAYFASTSSS2MATERIAL_SSS_DIFFUSECOLORSHADER { }
			SEPARATOR {LINE;}
			REAL VRAYFASTSSS2MATERIAL_SSS_DIFFUSEAMOUNT { MIN 0; STEP 0.01; MAX 1; CUSTOMGUI REALSLIDER;}
			SEPARATOR { }
			SHADERLINK VRAYFASTSSS2MATERIAL_SSS_DIFFUSEAMOUNTSHADER { }
			SEPARATOR {LINE;}
			COLOR VRAYFASTSSS2MATERIAL_SSS_SSSCOLOR {}
			SEPARATOR { }
			SHADERLINK VRAYFASTSSS2MATERIAL_SSS_SSSCOLORSHADER { }
			SEPARATOR {LINE;}
			COLOR VRAYFASTSSS2MATERIAL_SSS_SCATTERCOLOR {}
			SEPARATOR { }
			SHADERLINK VRAYFASTSSS2MATERIAL_SSS_SCATTERSHADER { }
			SEPARATOR {LINE;}
			REAL VRAYFASTSSS2MATERIAL_SSS_SCATTERMULT {MIN 0; STEP 0.01; MAXSLIDER 5; CUSTOMGUI REALSLIDER;}
			SEPARATOR { }
			SHADERLINK VRAYFASTSSS2MATERIAL_SSS_SCATTERMULTSHADER { }
			SEPARATOR {LINE;}
			REAL VRAYFASTSSS2MATERIAL_SSS_PHASE {MIN -1; MAX 1; STEP 0.01; MAXSLIDER 1; CUSTOMGUI REALSLIDER;}
		}
	
		SEPARATOR {LINE; }
		
		GROUP VRAYFASTSSS2MATERIAL_SSS_SPECULARPANEL
		{
			DEFAULT 1;
			
			COLOR VRAYFASTSSS2MATERIAL_SSS_SPECULARCOLOR {}
			SHADERLINK VRAYFASTSSS2MATERIAL_SSS_SPECULARCOLORSHADER { }
			SEPARATOR {LINE;}
			REAL VRAYFASTSSS2MATERIAL_SSS_SPECULARAMOUNT { MIN 0; STEP 0.01; MAX 1; CUSTOMGUI REALSLIDER;}
			SHADERLINK VRAYFASTSSS2MATERIAL_SSS_SPECULARAMOUNTSHADER { }
			SEPARATOR {LINE;}
			REAL VRAYFASTSSS2MATERIAL_SSS_SPECULARGLOSSINESS { MIN 0; STEP 0.01; MAX 1; CUSTOMGUI REALSLIDER; }
			SHADERLINK VRAYFASTSSS2MATERIAL_SSS_SPECULARGLOSSINESSSHADER { }
			SEPARATOR {LINE;}
			LONG VRAYFASTSSS2MATERIAL_SSS_SPECULARSUBDIVS { MIN 1; CUSTOMGUI LONGSLIDER;}
			BOOL VRAYFASTSSS2MATERIAL_SSS_SPECULARTRACE { }
			LONG VRAYFASTSSS2MATERIAL_SSS_SPECULARDEPTH { MIN 0; }
		}
		
		SEPARATOR { LINE; }
	
		GROUP VRAYFASTSSS2MATERIAL_SSS_OPTIONSPANEL
		{
			DEFAULT 1;

			LONG VRAYFASTSSS2MATERIAL_SSS_SINGLESCATTER { CYCLE { VRAYFASTSSS2MATERIAL_SSS_SINGLESCATTER_0; VRAYFASTSSS2MATERIAL_SSS_SINGLESCATTER_1; VRAYFASTSSS2MATERIAL_SSS_SINGLESCATTER_2; VRAYFASTSSS2MATERIAL_SSS_SINGLESCATTER_3;} }			
			LONG VRAYFASTSSS2MATERIAL_SSS_SUBDIVS {MIN 0; MAXSLIDER 10; CUSTOMGUI LONGSLIDER;}
			LONG VRAYFASTSSS2MATERIAL_SSS_REFRACTIONDEPTH { MIN 0; }
			BOOL VRAYFASTSSS2MATERIAL_SSS_FRONTSCATTER { }
			BOOL VRAYFASTSSS2MATERIAL_SSS_BACKSCATTER { }
			BOOL VRAYFASTSSS2MATERIAL_SSS_SCATTERGI {}
			REAL VRAYFASTSSS2MATERIAL_SSS_PREPASSLOD {MIN 0; STEP 0.01; MAXSLIDER 10; CUSTOMGUI REALSLIDER;}
			REAL VRAYFASTSSS2MATERIAL_SSS_PREPASSBLUR {MIN 0; STEP 0.01; MAXSLIDER 4; CUSTOMGUI REALSLIDER;}
			LONG VRAYFASTSSS2MATERIAL_SSS_PREPASSMODE { CYCLE { VRAYFASTSSS2MATERIAL_SSS_PREPASSMODE_0; VRAYFASTSSS2MATERIAL_SSS_PREPASSMODE_1; VRAYFASTSSS2MATERIAL_SSS_PREPASSMODE_2; VRAYFASTSSS2MATERIAL_SSS_PREPASSMODE_3; VRAYFASTSSS2MATERIAL_SSS_PREPASSMODE_4;} }
			FILENAME VRAYFASTSSS2MATERIAL_SSS_PREPASSFILENAMESAVE {SAVE; HIDDEN;}
			FILENAME VRAYFASTSSS2MATERIAL_SSS_PREPASSFILENAMEOPEN {HIDDEN;} 
		}
	}
	
	INCLUDE Massign;
}
