 CONTAINER mVrayAdvancedMaterial
{
	NAME mVrayAdvancedMaterial;

	GROUP
	{
		MATPREVIEW VRAYMATERIAL_MAT_PREVIEW { OPEN; }
	}

	INCLUDE Mbase;

	GROUP Obaselist
	{
		SEPARATOR {LINE;}
		//BOOL VRAYMATERIAL_ANIMATEPREVIEW { }
		//BOOL VRAYMATERIAL_SKIPPAGL {}
		LONG VRAYMATERIAL_QUALITY
 		{
 			CYCLE
 			{
 				VRAYMATERIAL_QUALITY_0;
 				VRAYMATERIAL_QUALITY_1;
 				VRAYMATERIAL_QUALITY_2;
 			}
 		}
		LONG VRAYMATERIAL_PREVIEWSIZE
		{
			CYCLE
			{
				VRAYMATERIAL_PREVIEWSIZE_DEF;
				VRAYMATERIAL_PREVIEWSIZE_64;
				VRAYMATERIAL_PREVIEWSIZE_128;
				VRAYMATERIAL_PREVIEWSIZE_256;
				VRAYMATERIAL_PREVIEWSIZE_512;
				VRAYMATERIAL_PREVIEWSIZE_1024;
				VRAYMATERIAL_PREVIEWSIZE_2048;
				VRAYMATERIAL_PREVIEWSIZE_4096;
			}
		}
 		SEPARATOR { LINE; }
		LONG VRAYMATERIAL_CONVERT_C4D_BITMAP {
			CYCLE {
				VRAYMATERIAL_CONVERT_C4D_BITMAP_0;
				VRAYMATERIAL_CONVERT_C4D_BITMAP_1;
				//VRAYMATERIAL_CONVERT_C4D_BITMAP_2;
			}
		}
		LONG VRAYMATERIAL_BACKE_C4D_SHADERS {
			CYCLE {
				VRAYMATERIAL_BACKE_C4D_SHADERS_0;
				VRAYMATERIAL_BACKE_C4D_SHADERS_1;
				//VRAYMATERIAL_BACKE_C4D_SHADERS_2;
			}
		}

		LONG VRAYMATERIAL_BACKE_RESOLUTION	{
			CYCLE {
				VRAYMATERIAL_BACKE_RESOLUTION_0;
				VRAYMATERIAL_BACKE_RESOLUTION_1;
				VRAYMATERIAL_BACKE_RESOLUTION_2;
				VRAYMATERIAL_BACKE_RESOLUTION_3;
				VRAYMATERIAL_BACKE_RESOLUTION_4;
				VRAYMATERIAL_BACKE_RESOLUTION_5;
				-1;
				VRAYMATERIAL_BACKE_RESOLUTION_10;
				VRAYMATERIAL_BACKE_RESOLUTION_11;
				VRAYMATERIAL_BACKE_RESOLUTION_12;
				VRAYMATERIAL_BACKE_RESOLUTION_13;
				VRAYMATERIAL_BACKE_RESOLUTION_14;
				VRAYMATERIAL_BACKE_RESOLUTION_15;
				-1;
				VRAYMATERIAL_BACKE_RESOLUTION_20;
				VRAYMATERIAL_BACKE_RESOLUTION_21;
				VRAYMATERIAL_BACKE_RESOLUTION_22;
				VRAYMATERIAL_BACKE_RESOLUTION_23;
				VRAYMATERIAL_BACKE_RESOLUTION_24;
				VRAYMATERIAL_BACKE_RESOLUTION_25;
			}
		}
 		SEPARATOR { LINE; }

		REAL VRAYMATERIAL_GAMMA { HIDDEN; MIN 0; STEP 0.1; MAXSLIDER 2.2; CUSTOMGUI REALSLIDER; }

		SEPARATOR {LINE;}

		BOOL VRAYMATERIAL_OVERRIDABLE {}

 		SEPARATOR { LINE; }
 		
 		LONG VRAYMATERIAL_ID { MIN 0;}
 		COLOR VRAYMATERIAL_IDCOLOR { }

		SEPARATOR { LINE; }

		GROUP
		{
			COLUMNS 2;
			
			BOOL VRAYMATERIAL_PREVIEWONLY_SPECULAR {}
			LONG VRAYMATERIAL_PREVIEWONLY_SPECULAR_SUBDIVS {MIN 0; MAX 512;}

		}

		SEPARATOR { LINE; }

		GROUP
		{
			COLUMNS 2;
			
			BOOL VRAYMATERIAL_ISROUNDED {}
			REAL VRAYMATERIAL_ROUNDRADIUS {MIN 0;}

		}
		 		
 		SEPARATOR { LINE; }

		GROUP
		{
			LAYOUTGROUP; COLUMNS 2; MATEDCOLUMNS 1;
			GROUP
			{
				BOOL VRAYMATERIAL_USE_MATTE			{ PARENTMSG ID_VRAYMATERIALGROUP_MATTE; }
				BOOL VRAYMATERIAL_USE_TRANSP		{ PARENTMSG ID_VRAYMATERIALGROUP_TRANSP; }
				BOOL VRAYMATERIAL_USE_BUMP			{ PARENTMSG ID_VRAYMATERIALGROUP_BUMP; }
				BOOL VRAYMATERIAL_USE_LUMINANCE		{ PARENTMSG ID_VRAYMATERIALGROUP_LUMINANCE; }
				BOOL VRAYMATERIAL_USE_FLAKES		{ PARENTMSG ID_VRAYMATERIALGROUP_FLAKES; }
				BOOL VRAYMATERIAL_USE_REFLECTION	{ PARENTMSG ID_VRAYMATERIALGROUP_REFLECTION; }
				BOOL VRAYMATERIAL_USE_SPECULAR5		{ PARENTMSG ID_VRAYMATERIALGROUP_SPECULAR5; }
				BOOL VRAYMATERIAL_USE_SPECULAR4		{ PARENTMSG ID_VRAYMATERIALGROUP_SPECULAR4; }
				BOOL VRAYMATERIAL_USE_SPECULAR3		{ PARENTMSG ID_VRAYMATERIALGROUP_SPECULAR3; }
				BOOL VRAYMATERIAL_USE_SPECULAR2		{ PARENTMSG ID_VRAYMATERIALGROUP_SPECULAR2; }
				BOOL VRAYMATERIAL_USE_SPECULAR1		{ PARENTMSG ID_VRAYMATERIALGROUP_SPECULAR1; }
				BOOL VRAYMATERIAL_USE_COLOR1 		{ PARENTMSG ID_VRAYMATERIALGROUP_COLOR; }
				BOOL VRAYMATERIAL_USE_COLOR2 		{ PARENTMSG ID_VRAYMATERIALGROUP_COLOR2; }
				BOOL VRAYMATERIAL_USE_TRANSPARENCY	{ PARENTMSG ID_VRAYMATERIALGROUP_TRANSPARENCY; }
				BOOL VRAYMATERIAL_USE_SSS			{ PARENTMSG ID_VRAYMATERIALGROUP_SSS; }
				BOOL VRAYMATERIAL_PAGE_ILLUMINATION	{ PAGE; HIDDEN; PARENTMSG ID_VRAYMATERIALGROUP_ILLUMINATION; }
			}
		}
	}

	GROUP ID_VRAYMATERIALGROUP_MATTE
	{
		HIDDEN;

		LONG VRAYMATERIAL_MATTE_MODE
		{
			CYCLE
			{
				VRAYMATERIAL_MATTE_MODE_0;
				VRAYMATERIAL_MATTE_MODE_1;
				VRAYMATERIAL_MATTE_MODE_2;
				VRAYMATERIAL_MATTE_MODE_3;
			}
		}

		SEPARATOR {}

		SHADERLINK VRAYMATERIAL_MATTE_OPSHADER { }
		BOOL VRAYMATERIAL_MATTE_OPTEXINVERT {}

		SEPARATOR {}

		SHADERLINK VRAYMATERIAL_MATTE_ALPHASHADER { }
		BOOL VRAYMATERIAL_MATTE_ALPHATEXINVERT {}
	}

	GROUP ID_VRAYMATERIALGROUP_TRANSP
	{
		HIDDEN;

		COLOR	VRAYMATERIAL_TRANSP_COLOR { OPEN; HIDDEN;}
		REAL VRAYMATERIAL_TRANSP_MULT {MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; HIDDEN;}
		SEPARATOR {}
		SHADERLINK VRAYMATERIAL_TRANSP_SHADER { }
		REAL VRAYMATERIAL_TRANSP_TEXTUREMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
		BOOL VRAYMATERIAL_TRANSP_TEXINVERT {}

		SEPARATOR {}

		BOOL VRAYMATERIAL_TRANSP_ADDITIVE {}

		LINK VRAYMATERIAL_TRANSP_LINK {HIDDEN;}
		COLOR VRAYMATERIAL_TRANSP_LINKCOL {HIDDEN;}
		SHADERLINK VRAYMATERIAL_TRANSP_LINKTEX {HIDDEN;}
		REAL VRAYMATERIAL_TRANSP_LINKTEXMULT {HIDDEN;}
	}


	GROUP ID_VRAYMATERIALGROUP_BUMP
	{
		HIDDEN;
		
		LONG VRAYMATERIAL_BUMP_TYPE
		{
			CYCLE
			{
				VRAYMATERIAL_BUMP_TYPE_0;
				VRAYMATERIAL_BUMP_TYPE_1;
				VRAYMATERIAL_BUMP_TYPE_2;
				VRAYMATERIAL_BUMP_TYPE_3;
				VRAYMATERIAL_BUMP_TYPE_4;
			}
		}
		
		SEPARATOR {}
		
		SHADERLINK VRAYMATERIAL_BUMP_SHADER { }
		BOOL VRAYMATERIAL_BUMP_BUMPTEXINVERT {}
		
		SEPARATOR {}
		
		REAL VRAYMATERIAL_BUMP_BUMPTEXMULT {UNIT METER; STEP 0.01;}
		BOOL VRAYMATERIAL_BUMP_SHADOWS {HIDDEN;}
		REAL VRAYMATERIAL_BUMP_DELTASCALE {MIN 0.001; MAX 2; STEP 0.01;}
	}


	GROUP ID_VRAYMATERIALGROUP_LUMINANCE
	{
		HIDDEN;

		GROUP VRAYMATERIAL_LUMINANCE_COLORPANEL
		{
			DEFAULT 1; HIDDEN;

			COLOR	VRAYMATERIAL_LUMINANCE_COLOR { OPEN; }
			REAL VRAYMATERIAL_LUMINANCE_COLOR_MULT {MIN 0; MAX 1000000; UNIT PERCENT; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER;}
			SEPARATOR {}
			SHADERLINK VRAYMATERIAL_LUMINANCE_SHADER { }
			REAL VRAYMATERIAL_LUMINANCE_SHADER_MULTIPLIER { MIN 0.0; STEP 0.01; MAX 1000.0; MAXSLIDER 1.0; CUSTOMGUI REALSLIDER;}
		}
		
		GROUP VRAYMATERIAL_LUMINANCE_VRAYDIRTPANEL
		{
			DEFAULT 1; HIDDEN;
			
			REAL VRAYMATERIAL_LUMINANCE_DIRTRADIUS {MIN 0; STEP 0.1;}
			SHADERLINK VRAYMATERIAL_LUMINANCE_DIRTRADIUSTEX {}
			SEPARATOR {}
			SHADERLINK VRAYMATERIAL_LUMINANCE_DIRTOCCLUDED {}
			SHADERLINK VRAYMATERIAL_LUMINANCE_DIRTUNOCCLUDED {}
			SEPARATOR {}
			REAL VRAYMATERIAL_LUMINANCE_DIRTDISTRIB {MIN 0; STEP 0.1;}
			REAL VRAYMATERIAL_LUMINANCE_DIRTFALLOFF {MIN 0; STEP 0.1;}
			LONG VRAYMATERIAL_LUMINANCE_DIRTSUBDIVS {MIN 1;}
			VECTOR VRAYMATERIAL_LUMINANCE_DIRTBIAS {MIN 0; MAX 1;}
			BOOL VRAYMATERIAL_LUMINANCE_DIRTIGNOREGI {}
			BOOL VRAYMATERIAL_LUMINANCE_DIRTSAMEOBJONLY {}
			BOOL VRAYMATERIAL_LUMINANCE_DIRTINVERTNML {}
			BOOL VRAYMATERIAL_LUMINANCE_DIRTWORKTRANSP {}
			BOOL VRAYMATERIAL_LUMINANCE_DIRTIGNORESELFOCCLUSION {}
		}

		SEPARATOR {LINE;}

		GROUP VRAYMATERIAL_LUMINANCE_TRANSPPANEL
		{
			DEFAULT 1;

			COLOR	VRAYMATERIAL_LUMINANCE_TRANSP { OPEN; }
			REAL VRAYMATERIAL_LUMINANCE_TRANSP_MULT {MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
			SEPARATOR {}
			SHADERLINK VRAYMATERIAL_LUMINANCE_TRANSPSHADER { }
			BOOL VRAYMATERIAL_LUMINANCE_TRANSP_TEXINVERT {}
		}

		SEPARATOR {LINE;}

		GROUP VRAYMATERIAL_LUMINANCE_OPTIONSPANEL
		{
			DEFAULT 1;

			BOOL VRAYMATERIAL_LUMINANCE_DOUBLE {}
			BOOL VRAYMATERIAL_LUMINANCE_EMITBACK {}
			BOOL VRAYMATERIAL_LUMINANCE_COMPENSATE {}
			BOOL VRAYMATERIAL_LUMINANCE_DIRECTILLUM {}
			
			SEPARATOR {}
			BOOL VRAYMATERIAL_LUMINANCE_USEDIRT {}	
			BOOL VRAYMATERIAL_LUMINANCE_USEDIRT2 {}
			LONG VRAYMATERIAL_LUMINANCE_DIRTCOMP
			{
				CYCLE
				{
					VRAYMATERIAL_LUMINANCE_DIRTCOMP_0;
					VRAYMATERIAL_LUMINANCE_DIRTCOMP_1;
					VRAYMATERIAL_LUMINANCE_DIRTCOMP_2;
					VRAYMATERIAL_LUMINANCE_DIRTCOMP_3;
					VRAYMATERIAL_LUMINANCE_DIRTCOMP_4;
					VRAYMATERIAL_LUMINANCE_DIRTCOMP_5;
					VRAYMATERIAL_LUMINANCE_DIRTCOMP_6;
				}
			}
		}
		
		GROUP VRAYMATERIAL_LUMINANCE_MESHLIGHTPANEL
		{
			DEFAULT 1; HIDDEN;
			
			REAL VRAYMATERIAL_LUMINANCE_INTENSITY {MIN 0; STEP 0.1;}
			//SHADERLINK VRAYMATERIAL_LUMINANCE_INTENSITYTEX {}
			
			SEPARATOR {}
			
			LONG VRAYMATERIAL_LUMINANCE_UNITS
			{
				CYCLE
				{
					VRAYMATERIAL_LUMINANCE_UNITS_0;
					VRAYMATERIAL_LUMINANCE_UNITS_1;
					VRAYMATERIAL_LUMINANCE_UNITS_2;
					VRAYMATERIAL_LUMINANCE_UNITS_3;
					VRAYMATERIAL_LUMINANCE_UNITS_4;
				}
			}
			
			SEPARATOR {}
			
			BOOL VRAYMATERIAL_LUMINANCE_AFFECTDIFF {}
			REAL VRAYMATERIAL_LUMINANCE_DIFFCONTR {MIN 0; STEP 0.01;}
			SEPARATOR {}
			BOOL VRAYMATERIAL_LUMINANCE_AFFECTSPEC {}
			REAL VRAYMATERIAL_LUMINANCE_SPECCONTR {MIN 0; STEP 0.01;}
			
			SEPARATOR {}
			
			BOOL VRAYMATERIAL_LUMINANCE_SHDON	{}
			COLOR VRAYMATERIAL_LUMINANCE_SHDCOLOR {}
			//SHADERLINK VRAYMATERIAL_LUMINANCE_SHDCOLORTEX {}
			REAL VRAYMATERIAL_LUMINANCE_SHDBIAS {UNIT METER; MIN 0; STEP 0.01;}
			
			SEPARATOR {}
			
			BOOL VRAYMATERIAL_LUMINANCE_AFFECTREFL {}
			BOOL VRAYMATERIAL_LUMINANCE_INVISIBLE {}
			LONG VRAYMATERIAL_LUMINANCE_SUBDIVS {MIN 0;}
			BOOL VRAYMATERIAL_LUMINANCE_NODECAY {}
			BOOL VRAYMATERIAL_LUMINANCE_STORE {}
			LONG VRAYMATERIAL_LUMINANCE_PORTAL
			{
				CYCLE
				{
					VRAYMATERIAL_LUMINANCE_PORTAL_0;
					VRAYMATERIAL_LUMINANCE_PORTAL_1;
					VRAYMATERIAL_LUMINANCE_PORTAL_2;
				}
			}
			BOOL VRAYMATERIAL_LUMINANCE_NONORMALS {}
		}
	}
	
	
	GROUP ID_VRAYMATERIALGROUP_FLAKES
		{
			HIDDEN;
			
			COLOR VRAYMATERIAL_FLAKES_COLOR {}
			SEPARATOR { }
			SHADERLINK VRAYMATERIAL_FLAKES_COLORSHADER { }
			
			SEPARATOR {LINE;}
			
			REAL VRAYMATERIAL_FLAKES_GLOSSINESS { MIN 0; STEP 0.01; MAX 1; CUSTOMGUI REALSLIDER;}
			SEPARATOR { }
			SHADERLINK VRAYMATERIAL_FLAKES_GLOSSINESSSHADER { }
			
			SEPARATOR {LINE;}
			
			REAL VRAYMATERIAL_FLAKES_ORIENTATION { MIN 0; STEP 0.01; MAX 1; CUSTOMGUI REALSLIDER;}
			SEPARATOR { }
			SHADERLINK VRAYMATERIAL_FLAKES_ORIENTATIONSHADER { }
			
			SEPARATOR {LINE;}
			
			REAL VRAYMATERIAL_FLAKES_DENSITY { MIN 0; STEP 0.01; MAX 10; MAXSLIDER 10; CUSTOMGUI REALSLIDER;}
			REAL VRAYMATERIAL_FLAKES_SCALE { MIN 0; STEP 0.01; MAX 1; CUSTOMGUI REALSLIDER;}
			REAL VRAYMATERIAL_FLAKES_SIZE { MIN 0; STEP 0.01; MAX 1; CUSTOMGUI REALSLIDER;}
			LONG VRAYMATERIAL_FLAKES_MAPSIZE { MIN 0; }
			LONG VRAYMATERIAL_FLAKES_SEED { MIN 0; }
			SEPARATOR {}
			LONG VRAYMATERIAL_FLAKES_FILTERING
 			{
 				CYCLE
 				{
 					VRAYMATERIAL_FLAKES_FILTERING_0;
 					VRAYMATERIAL_FLAKES_FILTERING_1;
 				}
 			}
 			SEPARATOR {}
			LONG VRAYMATERIAL_FLAKES_MAPTYPE
 			{
 				CYCLE
 				{
 					VRAYMATERIAL_FLAKES_MAPTYPE_0;
 					VRAYMATERIAL_FLAKES_MAPTYPE_1;
 				}
 			}
 			
 			SEPARATOR {}
 			
			BOOL VRAYMATERIAL_FLAKES_TRACEREFLECTION { }
		}


	GROUP ID_VRAYMATERIALGROUP_REFLECTION
	{
			HIDDEN;

			GROUP VRAYMATERIAL_REFLECTION_COLORPANEL
			{
				DEFAULT 1;

				COLOR VRAYMATERIAL_REFLECTION_COLOR { OPEN; }
				REAL VRAYMATERIAL_REFLECTION_COLOR_MULT {MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
				SEPARATOR {}
				SHADERLINK VRAYMATERIAL_REFLECTION_SHADER { }
				LONG VRAYMATERIAL_REFLECTION_TEXTUREMIXMODE {CYCLE{VRAYMATERIAL_REFLECTION_TEXTUREMIXMODE_0; VRAYMATERIAL_REFLECTION_TEXTUREMIXMODE_1; VRAYMATERIAL_REFLECTION_TEXTUREMIXMODE_2; VRAYMATERIAL_REFLECTION_TEXTUREMIXMODE_3; VRAYMATERIAL_REFLECTION_TEXTUREMIXMODE_4; VRAYMATERIAL_REFLECTION_TEXTUREMIXMODE_5; VRAYMATERIAL_REFLECTION_TEXTUREMIXMODE_6; VRAYMATERIAL_REFLECTION_TEXTUREMIXMODE_7; VRAYMATERIAL_REFLECTION_TEXTUREMIXMODE_8; VRAYMATERIAL_REFLECTION_TEXTUREMIXMODE_9; VRAYMATERIAL_REFLECTION_TEXTUREMIXMODE_10; VRAYMATERIAL_REFLECTION_TEXTUREMIXMODE_11; VRAYMATERIAL_REFLECTION_TEXTUREMIXMODE_12;}}
				REAL VRAYMATERIAL_REFLECTION_TEXTUREMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
			}

			SEPARATOR {LINE; }

			GROUP VRAYMATERIAL_REFLECTION_TRANSPPANEL
			{
				DEFAULT 1;

				COLOR	VRAYMATERIAL_REFLECTION_TRANSP { OPEN; }
				REAL VRAYMATERIAL_REFLECTION_TRANSP_MULT {MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
				SEPARATOR { }
				SHADERLINK VRAYMATERIAL_REFLECTION_TRANSPSHADER { }
				LONG VRAYMATERIAL_REFLECTION_TRANSPTEXMIXMODE {CYCLE{VRAYMATERIAL_REFLECTION_TRANSPTEXMIXMODE_0; VRAYMATERIAL_REFLECTION_TRANSPTEXMIXMODE_1; VRAYMATERIAL_REFLECTION_TRANSPTEXMIXMODE_2; VRAYMATERIAL_REFLECTION_TRANSPTEXMIXMODE_3; VRAYMATERIAL_REFLECTION_TRANSPTEXMIXMODE_4; VRAYMATERIAL_REFLECTION_TRANSPTEXMIXMODE_5; VRAYMATERIAL_REFLECTION_TRANSPTEXMIXMODE_6; VRAYMATERIAL_REFLECTION_TRANSPTEXMIXMODE_7; VRAYMATERIAL_REFLECTION_TRANSPTEXMIXMODE_8; VRAYMATERIAL_REFLECTION_TRANSPTEXMIXMODE_9; VRAYMATERIAL_REFLECTION_TRANSPTEXMIXMODE_10; VRAYMATERIAL_REFLECTION_TRANSPTEXMIXMODE_11; VRAYMATERIAL_REFLECTION_TRANSPTEXMIXMODE_12;}}
				REAL VRAYMATERIAL_REFLECTION_TRANSPTEXMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				BOOL VRAYMATERIAL_REFLECTION_TRANSP_TEXINVERT {}

			}

			SEPARATOR {LINE;}

			GROUP VRAYMATERIAL_REFLECTION_OPTIONSPANEL
			{
				DEFAULT 1;

				GROUP
				{
					COLUMNS 3;
					
					//First group
					REAL VRAYMATERIAL_REFLECTION_CUTOFF {MIN 0; MAX 1; STEP 0.01;}
					BOOL VRAYMATERIAL_REFLECTION_BACKSIDE { }
					LONG VRAYMATERIAL_REFLECTION_DEPTH {MIN -1;}
					
					//Second group
					BOOL VRAYMATERIAL_REFLECTION_REFLECTDIMDISTON {}
					REAL VRAYMATERIAL_REFLECTION_REFLECTDIMDISTANCE {MIN 0; STEP 0.1;}
					REAL VRAYMATERIAL_REFLECTION_REFLECTDIMDISTFALLOFF {MIN 0; MAX 1.0; STEP 0.01;}
				}
				
				SEPARATOR {}
				
				COLOR VRAYMATERIAL_REFLECTION_EXITCOLOR { }
				
				SEPARATOR {}
				
				LONG VRAYMATERIAL_REFLECTION_DOALPHA
				{
					CYCLE
					{
						VRAYMATERIAL_REFLECTION_DOALPHA_0;
						VRAYMATERIAL_REFLECTION_DOALPHA_1;
						VRAYMATERIAL_REFLECTION_DOALPHA_2;
					}
				}
			}

			SEPARATOR {LINE;}

			GROUP VRAYMATERIAL_REFLECTION_FRESNELPANEL
			{
				DEFAULT 1;

				BOOL VRAYMATERIAL_REFLECTION_USEFRESNEL { }
				SEPARATOR {}
				REAL VRAYMATERIAL_REFLECTION_FRESNELIOR1 {MIN 0; STEP 0.01;}
				//REAL VRAYMATERIAL_REFLECTION_FRESNELIOR2 {MIN 0; STEP 0.01;}
				SEPARATOR {}
				COLOR VRAYMATERIAL_REFLECTION_FRESNELREFLCOL { }
				COLOR VRAYMATERIAL_REFLECTION_FRESNELREFRCOL { }
			}

	}


	/// SPECULAR 5 ///
	GROUP ID_VRAYMATERIALGROUP_SPECULAR5
	{
			HIDDEN;

			GROUP VRAYMATERIAL_SPECULAR5_BRDFMODE
			{
				DEFAULT 1;

				LONG VRAYMATERIAL_SPECULAR5_MODE	{ CYCLE { VRAYMATERIAL_SPECULAR5_MODE_PHONG; VRAYMATERIAL_SPECULAR5_MODE_BLINN; VRAYMATERIAL_SPECULAR5_MODE_WARD;} }
			}

			SEPARATOR {LINE;}

			GROUP VRAYMATERIAL_SPECULAR5_COLORPANEL
			{
				DEFAULT 1;

				COLOR VRAYMATERIAL_SPECULAR5_COLOR { OPEN; }
				REAL VRAYMATERIAL_SPECULAR5_COLOR_MULT {MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
				SEPARATOR {}
				SHADERLINK VRAYMATERIAL_SPECULAR5_SHADER { }
				LONG VRAYMATERIAL_SPECULAR5_TEXTUREMIXMODE {CYCLE{VRAYMATERIAL_SPECULAR5_TEXTUREMIXMODE_0; VRAYMATERIAL_SPECULAR5_TEXTUREMIXMODE_1; VRAYMATERIAL_SPECULAR5_TEXTUREMIXMODE_2; VRAYMATERIAL_SPECULAR5_TEXTUREMIXMODE_3; VRAYMATERIAL_SPECULAR5_TEXTUREMIXMODE_4; VRAYMATERIAL_SPECULAR5_TEXTUREMIXMODE_5; VRAYMATERIAL_SPECULAR5_TEXTUREMIXMODE_6; VRAYMATERIAL_SPECULAR5_TEXTUREMIXMODE_7; VRAYMATERIAL_SPECULAR5_TEXTUREMIXMODE_8; VRAYMATERIAL_SPECULAR5_TEXTUREMIXMODE_9; VRAYMATERIAL_SPECULAR5_TEXTUREMIXMODE_10; VRAYMATERIAL_SPECULAR5_TEXTUREMIXMODE_11; VRAYMATERIAL_SPECULAR5_TEXTUREMIXMODE_12;}}
				REAL VRAYMATERIAL_SPECULAR5_TEXTUREMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
			}

			SEPARATOR {LINE; }

			GROUP VRAYMATERIAL_SPECULAR5_TRANSPPANEL
			{
				DEFAULT 1;

				COLOR	VRAYMATERIAL_SPECULAR5_TRANSP { OPEN; }
				REAL VRAYMATERIAL_SPECULAR5_TRANSP_MULT {MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
				SEPARATOR { }
				SHADERLINK VRAYMATERIAL_SPECULAR5_TRANSPSHADER { }
				LONG VRAYMATERIAL_SPECULAR5_TRANSPTEXMIXMODE {CYCLE{VRAYMATERIAL_SPECULAR5_TRANSPTEXMIXMODE_0; VRAYMATERIAL_SPECULAR5_TRANSPTEXMIXMODE_1; VRAYMATERIAL_SPECULAR5_TRANSPTEXMIXMODE_2; VRAYMATERIAL_SPECULAR5_TRANSPTEXMIXMODE_3; VRAYMATERIAL_SPECULAR5_TRANSPTEXMIXMODE_4; VRAYMATERIAL_SPECULAR5_TRANSPTEXMIXMODE_5; VRAYMATERIAL_SPECULAR5_TRANSPTEXMIXMODE_6; VRAYMATERIAL_SPECULAR5_TRANSPTEXMIXMODE_7; VRAYMATERIAL_SPECULAR5_TRANSPTEXMIXMODE_8; VRAYMATERIAL_SPECULAR5_TRANSPTEXMIXMODE_9; VRAYMATERIAL_SPECULAR5_TRANSPTEXMIXMODE_10; VRAYMATERIAL_SPECULAR5_TRANSPTEXMIXMODE_11; VRAYMATERIAL_SPECULAR5_TRANSPTEXMIXMODE_12;}}
				REAL VRAYMATERIAL_SPECULAR5_TRANSPTEXMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				BOOL VRAYMATERIAL_SPECULAR5_TRANSP_TEXINVERT {}
			}

			SEPARATOR {LINE; }

			GROUP VRAYMATERIAL_SPECULAR5_FRESNELPANEL
			{
				DEFAULT 1;

				REAL VRAYMATERIAL_SPECULAR5_FRESNELIOR1 {MIN 0; STEP 0.01;}
				//REAL VRAYMATERIAL_SPECULAR5_FRESNELIOR2 {MIN 1; STEP 0.01;}
				SEPARATOR {}
				COLOR VRAYMATERIAL_SPECULAR5_FRESNELREFLCOL { }
				SHADERLINK VRAYMATERIAL_SPECULAR5_FRESNELREFLSHADER { }
				BOOL VRAYMATERIAL_SPECULAR5_FRESNELREFL_TEXINVERT { }

				SEPARATOR {}

				COLOR VRAYMATERIAL_SPECULAR5_FRESNELREFRCOL { }
				SHADERLINK VRAYMATERIAL_SPECULAR5_FRESNELREFRSHADER { }
				BOOL VRAYMATERIAL_SPECULAR5_FRESNELREFR_TEXINVERT { }
			}
			
			SEPARATOR {LINE; }

			GROUP VRAYMATERIAL_SPECULAR5_OPTIONSPANEL
			{
				DEFAULT 1;

				GROUP
				{
					COLUMNS 3;
					
					BOOL VRAYMATERIAL_SPECULAR5_USEFRESNEL { }
					BOOL VRAYMATERIAL_SPECULAR5_FIXDARKEDGES {}
					BOOL VRAYMATERIAL_SPECULAR5_LINKGLOSSINESS {}
				}
				
				SEPARATOR {LINE; }
				
				REAL VRAYMATERIAL_SPECULAR5_HIGHLIGHTGLOSS {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				SEPARATOR {}
				SHADERLINK VRAYMATERIAL_SPECULAR5_HIGHLIGHTGLOSSSHADER { }
				REAL VRAYMATERIAL_SPECULAR5_HIGHLIGHTGLOSSTEXMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				BOOL VRAYMATERIAL_SPECULAR5_HIGLOSS_TEXINVERT {}
				SEPARATOR {LINE; }
				REAL VRAYMATERIAL_SPECULAR5_REFLECTIONGLOSS {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				SEPARATOR {}
				SHADERLINK VRAYMATERIAL_SPECULAR5_REFLECTIONGLOSSSHADER { }
				REAL VRAYMATERIAL_SPECULAR5_REFLECTIONGLOSSTEXMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				BOOL VRAYMATERIAL_SPECULAR5_REFLGLOSS_TEXINVERT {}
				
				SEPARATOR {LINE;}
				
				LONG VRAYMATERIAL_SPECULAR5_SUBDIV {MIN 0; MAX 512;}
			}
				
				SEPARATOR {LINE;}
				
			GROUP VRAYMATERIAL_SPECULAR5_EXPERTPANEL
			{
				DEFAULT 0;
				
				GROUP
				{
					COLUMNS 3;
					
					//First group
					BOOL VRAYMATERIAL_SPECULAR5_TRACEREFL { }
					BOOL VRAYMATERIAL_SPECULAR5_TRACESPEC { }
					LONG VRAYMATERIAL_SPECULAR5_TRACEDEPTH {MIN -1;}
					
					//Second group
					BOOL VRAYMATERIAL_SPECULAR5_BACKSIDE { }
					REAL VRAYMATERIAL_SPECULAR5_SOFTENEDGES {MIN -1; MAX 1; STEP 0.01;}
					REAL VRAYMATERIAL_SPECULAR5_CUTOFF {MIN 0; MAX 1; STEP 0.001;}
					
					//Third group
					BOOL VRAYMATERIAL_SPECULAR5_REFLECTDIMDISTON {}
					REAL VRAYMATERIAL_SPECULAR5_REFLECTDIMDISTANCE {MIN 0; STEP 0.1;}
					REAL VRAYMATERIAL_SPECULAR5_REFLECTDIMDISTFALLOFF {MIN 0; MAX 1.0; STEP 0.01;}
				}
				
				SEPARATOR { LINE; }
				
				LONG VRAYMATERIAL_SPECULAR5_GIGLOSSY
				{
					CYCLE
					{
						VRAYMATERIAL_SPECULAR5_GIGLOSSY_0;
						VRAYMATERIAL_SPECULAR5_GIGLOSSY_1;
						VRAYMATERIAL_SPECULAR5_GIGLOSSY_2;
					}
				}

				SEPARATOR {}
					
				LONG VRAYMATERIAL_SPECULAR5_DOALPHA
				{
					CYCLE
					{
						VRAYMATERIAL_SPECULAR5_DOALPHA_0;
						VRAYMATERIAL_SPECULAR5_DOALPHA_1;
						VRAYMATERIAL_SPECULAR5_DOALPHA_2;
					}
				}			
								
				SEPARATOR {}
				
				COLOR VRAYMATERIAL_SPECULAR5_EXITCOLOR { }

				SEPARATOR {LINE; }
				
				GROUP
				{
					COLUMNS 3;
					
					//First group
					BOOL VRAYMATERIAL_SPECULAR5_INTERPOLATION { }
					LONG VRAYMATERIAL_SPECULAR5_IMAPMIN { }
					LONG VRAYMATERIAL_SPECULAR5_IMAPMAX { }
					
					//Second group
					REAL VRAYMATERIAL_SPECULAR5_CLRTHRESHOLD { MIN 0.0; MAX 1.0; }
					REAL VRAYMATERIAL_SPECULAR5_NMLTHRESHOLD { MIN 0.0; MAX 1.0; }
					LONG VRAYMATERIAL_SPECULAR5_IMAPSAMPLES { MIN 0; MAX 100; }
				
				}		
			}
			
			SEPARATOR {LINE; }

			GROUP VRAYMATERIAL_SPECULAR5_ANISOTROPYPANEL
			{
				DEFAULT 0;
				
				REAL VRAYMATERIAL_SPECULAR5_ANISOTROPY {MIN -1; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				SHADERLINK VRAYMATERIAL_SPECULAR5_ANISOTROPYSHADER { }
				BOOL VRAYMATERIAL_SPECULAR5_ANISO_TEXINVERT {}
				
				SEPARATOR {}
				
				REAL VRAYMATERIAL_SPECULAR5_ANISOTROPYROT {UNIT DEGREE; MIN 0; MAX 360; STEP 0.1; CUSTOMGUI REALSLIDER;}
				LONG VRAYMATERIAL_SPECULAR5_ANISOTROPYAXIS
				{
					CYCLE
					{
						VRAYMATERIAL_SPECULAR5_ANISOTROPYAXIS_0;
						VRAYMATERIAL_SPECULAR5_ANISOTROPYAXIS_1;
						VRAYMATERIAL_SPECULAR5_ANISOTROPYAXIS_2;
					}
				}
				
				SHADERLINK VRAYMATERIAL_SPECULAR5_ANISOTROPYROTSHADER { }
				BOOL VRAYMATERIAL_SPECULAR5_ANISOROT_TEXINVERT {}
			}
	}

	
	/// SPECULAR 4 ///
	GROUP ID_VRAYMATERIALGROUP_SPECULAR4
	{
			HIDDEN;

			GROUP VRAYMATERIAL_SPECULAR4_BRDFMODE
			{
				DEFAULT 1;

				LONG VRAYMATERIAL_SPECULAR4_MODE	{ CYCLE { VRAYMATERIAL_SPECULAR4_MODE_PHONG; VRAYMATERIAL_SPECULAR4_MODE_BLINN; VRAYMATERIAL_SPECULAR4_MODE_WARD;} }
			}

			SEPARATOR {LINE;}

			GROUP VRAYMATERIAL_SPECULAR4_COLORPANEL
			{
				DEFAULT 1;

				COLOR VRAYMATERIAL_SPECULAR4_COLOR { OPEN; }
				REAL VRAYMATERIAL_SPECULAR4_COLOR_MULT {MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
				SEPARATOR {}
				SHADERLINK VRAYMATERIAL_SPECULAR4_SHADER { }
				LONG VRAYMATERIAL_SPECULAR4_TEXTUREMIXMODE {CYCLE{VRAYMATERIAL_SPECULAR4_TEXTUREMIXMODE_0; VRAYMATERIAL_SPECULAR4_TEXTUREMIXMODE_1; VRAYMATERIAL_SPECULAR4_TEXTUREMIXMODE_2; VRAYMATERIAL_SPECULAR4_TEXTUREMIXMODE_3; VRAYMATERIAL_SPECULAR4_TEXTUREMIXMODE_4; VRAYMATERIAL_SPECULAR4_TEXTUREMIXMODE_5; VRAYMATERIAL_SPECULAR4_TEXTUREMIXMODE_6; VRAYMATERIAL_SPECULAR4_TEXTUREMIXMODE_7; VRAYMATERIAL_SPECULAR4_TEXTUREMIXMODE_8; VRAYMATERIAL_SPECULAR4_TEXTUREMIXMODE_9; VRAYMATERIAL_SPECULAR4_TEXTUREMIXMODE_10; VRAYMATERIAL_SPECULAR4_TEXTUREMIXMODE_11; VRAYMATERIAL_SPECULAR4_TEXTUREMIXMODE_12;}}
				REAL VRAYMATERIAL_SPECULAR4_TEXTUREMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
			}

			SEPARATOR {LINE; }

			GROUP VRAYMATERIAL_SPECULAR4_TRANSPPANEL
			{
				DEFAULT 1;

				COLOR	VRAYMATERIAL_SPECULAR4_TRANSP { OPEN; }
				REAL VRAYMATERIAL_SPECULAR4_TRANSP_MULT {MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
				SEPARATOR { }
				SHADERLINK VRAYMATERIAL_SPECULAR4_TRANSPSHADER { }
				LONG VRAYMATERIAL_SPECULAR4_TRANSPTEXMIXMODE {CYCLE{VRAYMATERIAL_SPECULAR4_TRANSPTEXMIXMODE_0; VRAYMATERIAL_SPECULAR4_TRANSPTEXMIXMODE_1; VRAYMATERIAL_SPECULAR4_TRANSPTEXMIXMODE_2; VRAYMATERIAL_SPECULAR4_TRANSPTEXMIXMODE_3; VRAYMATERIAL_SPECULAR4_TRANSPTEXMIXMODE_4; VRAYMATERIAL_SPECULAR4_TRANSPTEXMIXMODE_5; VRAYMATERIAL_SPECULAR4_TRANSPTEXMIXMODE_6; VRAYMATERIAL_SPECULAR4_TRANSPTEXMIXMODE_7; VRAYMATERIAL_SPECULAR4_TRANSPTEXMIXMODE_8; VRAYMATERIAL_SPECULAR4_TRANSPTEXMIXMODE_9; VRAYMATERIAL_SPECULAR4_TRANSPTEXMIXMODE_10; VRAYMATERIAL_SPECULAR4_TRANSPTEXMIXMODE_11; VRAYMATERIAL_SPECULAR4_TRANSPTEXMIXMODE_12;}}
				REAL VRAYMATERIAL_SPECULAR4_TRANSPTEXMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				BOOL VRAYMATERIAL_SPECULAR4_TRANSP_TEXINVERT {}
			}

			SEPARATOR {LINE; }

			GROUP VRAYMATERIAL_SPECULAR4_FRESNELPANEL
			{
				DEFAULT 1;

				REAL VRAYMATERIAL_SPECULAR4_FRESNELIOR1 {MIN 0; STEP 0.01;}
				//REAL VRAYMATERIAL_SPECULAR4_FRESNELIOR2 {MIN 1; STEP 0.01;}
				SEPARATOR {}
				COLOR VRAYMATERIAL_SPECULAR4_FRESNELREFLCOL { }
				SHADERLINK VRAYMATERIAL_SPECULAR4_FRESNELREFLSHADER { }
				BOOL VRAYMATERIAL_SPECULAR4_FRESNELREFL_TEXINVERT { }

				SEPARATOR {}

				COLOR VRAYMATERIAL_SPECULAR4_FRESNELREFRCOL { }
				SHADERLINK VRAYMATERIAL_SPECULAR4_FRESNELREFRSHADER { }
				BOOL VRAYMATERIAL_SPECULAR4_FRESNELREFR_TEXINVERT	{ }
			}
			
			SEPARATOR {LINE; }
			
			GROUP VRAYMATERIAL_SPECULAR4_OPTIONSPANEL
			{
				DEFAULT 1;

				GROUP
				{
					COLUMNS 3;
					
					BOOL VRAYMATERIAL_SPECULAR4_USEFRESNEL { }
					BOOL VRAYMATERIAL_SPECULAR4_FIXDARKEDGES {}
					BOOL VRAYMATERIAL_SPECULAR4_LINKGLOSSINESS {}
				}
				
				SEPARATOR {LINE; }
				
				REAL VRAYMATERIAL_SPECULAR4_HIGHLIGHTGLOSS {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				SEPARATOR {}
				SHADERLINK VRAYMATERIAL_SPECULAR4_HIGHLIGHTGLOSSSHADER { }
				REAL VRAYMATERIAL_SPECULAR4_HIGHLIGHTGLOSSTEXMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				BOOL VRAYMATERIAL_SPECULAR4_HIGLOSS_TEXINVERT {}
				SEPARATOR {LINE; }
				REAL VRAYMATERIAL_SPECULAR4_REFLECTIONGLOSS {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				SEPARATOR {}
				SHADERLINK VRAYMATERIAL_SPECULAR4_REFLECTIONGLOSSSHADER { }
				REAL VRAYMATERIAL_SPECULAR4_REFLECTIONGLOSSTEXMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				BOOL VRAYMATERIAL_SPECULAR4_REFLGLOSS_TEXINVERT {}
				
				SEPARATOR {LINE;}
				
				LONG VRAYMATERIAL_SPECULAR4_SUBDIV {MIN 0; MAX 512;}
			}
				
				SEPARATOR {LINE;}
				
			GROUP VRAYMATERIAL_SPECULAR4_EXPERTPANEL
			{
				DEFAULT 0;
				
				GROUP
				{
					COLUMNS 3;
					
					//First group
					BOOL VRAYMATERIAL_SPECULAR4_TRACEREFL { }
					BOOL VRAYMATERIAL_SPECULAR4_TRACESPEC { }
					LONG VRAYMATERIAL_SPECULAR4_TRACEDEPTH {MIN -1;}
					
					//Second group
					BOOL VRAYMATERIAL_SPECULAR4_BACKSIDE { }
					REAL VRAYMATERIAL_SPECULAR4_SOFTENEDGES {MIN -1; MAX 1; STEP 0.01;}
					REAL VRAYMATERIAL_SPECULAR4_CUTOFF {MIN 0; MAX 1; STEP 0.001;}
					
					//Third group
					BOOL VRAYMATERIAL_SPECULAR4_REFLECTDIMDISTON {}
					REAL VRAYMATERIAL_SPECULAR4_REFLECTDIMDISTANCE {MIN 0; STEP 0.1;}
					REAL VRAYMATERIAL_SPECULAR4_REFLECTDIMDISTFALLOFF {MIN 0; MAX 1.0; STEP 0.01;}
				}
				
				SEPARATOR { LINE; }
				
				LONG VRAYMATERIAL_SPECULAR4_GIGLOSSY
				{
					CYCLE
					{
						VRAYMATERIAL_SPECULAR4_GIGLOSSY_0;
						VRAYMATERIAL_SPECULAR4_GIGLOSSY_1;
						VRAYMATERIAL_SPECULAR4_GIGLOSSY_2;
					}
				}

				SEPARATOR {}
					
				LONG VRAYMATERIAL_SPECULAR4_DOALPHA
				{
					CYCLE
					{
						VRAYMATERIAL_SPECULAR4_DOALPHA_0;
						VRAYMATERIAL_SPECULAR4_DOALPHA_1;
						VRAYMATERIAL_SPECULAR4_DOALPHA_2;
					}
				}			
								
				SEPARATOR {}
				
				COLOR VRAYMATERIAL_SPECULAR4_EXITCOLOR { }

				SEPARATOR {LINE; }
				
				GROUP
				{
					COLUMNS 3;
					
					//First group
					BOOL VRAYMATERIAL_SPECULAR4_INTERPOLATION { }
					LONG VRAYMATERIAL_SPECULAR4_IMAPMIN { }
					LONG VRAYMATERIAL_SPECULAR4_IMAPMAX { }
					
					//Second group
					REAL VRAYMATERIAL_SPECULAR4_CLRTHRESHOLD { MIN 0.0; MAX 1.0; }
					REAL VRAYMATERIAL_SPECULAR4_NMLTHRESHOLD { MIN 0.0; MAX 1.0; }
					LONG VRAYMATERIAL_SPECULAR4_IMAPSAMPLES { MIN 0; MAX 100; }
				
				}
			}
			
			SEPARATOR {LINE; }
			
			GROUP VRAYMATERIAL_SPECULAR4_ANISOTROPYPANEL
			{
				DEFAULT 0;
			
				REAL VRAYMATERIAL_SPECULAR4_ANISOTROPY {MIN -1; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				SHADERLINK VRAYMATERIAL_SPECULAR4_ANISOTROPYSHADER { }
				BOOL VRAYMATERIAL_SPECULAR4_ANISO_TEXINVERT {}
				
				SEPARATOR {}
				
				REAL VRAYMATERIAL_SPECULAR4_ANISOTROPYROT {UNIT DEGREE; MIN 0; MAX 360; STEP 0.1; CUSTOMGUI REALSLIDER;}
				LONG VRAYMATERIAL_SPECULAR4_ANISOTROPYAXIS
				{
					CYCLE
					{
						VRAYMATERIAL_SPECULAR4_ANISOTROPYAXIS_0;
						VRAYMATERIAL_SPECULAR4_ANISOTROPYAXIS_1;
						VRAYMATERIAL_SPECULAR4_ANISOTROPYAXIS_2;
					}
				}
						
				SHADERLINK VRAYMATERIAL_SPECULAR4_ANISOTROPYROTSHADER { }
				BOOL VRAYMATERIAL_SPECULAR4_ANISOROT_TEXINVERT {}
			}
	}


	/// SPECULAR 3 ///
	GROUP ID_VRAYMATERIALGROUP_SPECULAR3
	{
			HIDDEN;

			GROUP VRAYMATERIAL_SPECULAR3_BRDFMODE
			{
				DEFAULT 1;

				LONG VRAYMATERIAL_SPECULAR3_MODE	{ CYCLE { VRAYMATERIAL_SPECULAR3_MODE_PHONG; VRAYMATERIAL_SPECULAR3_MODE_BLINN; VRAYMATERIAL_SPECULAR3_MODE_WARD;} }
			}

			SEPARATOR {LINE;}

			GROUP VRAYMATERIAL_SPECULAR3_COLORPANEL
			{
				DEFAULT 1;

				COLOR VRAYMATERIAL_SPECULAR3_COLOR { OPEN; }
				REAL VRAYMATERIAL_SPECULAR3_COLOR_MULT {MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
				SEPARATOR {}
				SHADERLINK VRAYMATERIAL_SPECULAR3_SHADER { }
				LONG VRAYMATERIAL_SPECULAR3_TEXTUREMIXMODE {CYCLE{VRAYMATERIAL_SPECULAR3_TEXTUREMIXMODE_0; VRAYMATERIAL_SPECULAR3_TEXTUREMIXMODE_1; VRAYMATERIAL_SPECULAR3_TEXTUREMIXMODE_2; VRAYMATERIAL_SPECULAR3_TEXTUREMIXMODE_3; VRAYMATERIAL_SPECULAR3_TEXTUREMIXMODE_4; VRAYMATERIAL_SPECULAR3_TEXTUREMIXMODE_5; VRAYMATERIAL_SPECULAR3_TEXTUREMIXMODE_6; VRAYMATERIAL_SPECULAR3_TEXTUREMIXMODE_7; VRAYMATERIAL_SPECULAR3_TEXTUREMIXMODE_8; VRAYMATERIAL_SPECULAR3_TEXTUREMIXMODE_9; VRAYMATERIAL_SPECULAR3_TEXTUREMIXMODE_10; VRAYMATERIAL_SPECULAR3_TEXTUREMIXMODE_11; VRAYMATERIAL_SPECULAR3_TEXTUREMIXMODE_12;}}
				REAL VRAYMATERIAL_SPECULAR3_TEXTUREMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
			}

			SEPARATOR {LINE; }

			GROUP VRAYMATERIAL_SPECULAR3_TRANSPPANEL
			{
				DEFAULT 1;

				COLOR	VRAYMATERIAL_SPECULAR3_TRANSP { OPEN; }
				REAL VRAYMATERIAL_SPECULAR3_TRANSP_MULT {MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
				SEPARATOR { }
				SHADERLINK VRAYMATERIAL_SPECULAR3_TRANSPSHADER { }
				LONG VRAYMATERIAL_SPECULAR3_TRANSPTEXMIXMODE {CYCLE{VRAYMATERIAL_SPECULAR3_TRANSPTEXMIXMODE_0; VRAYMATERIAL_SPECULAR3_TRANSPTEXMIXMODE_1; VRAYMATERIAL_SPECULAR3_TRANSPTEXMIXMODE_2; VRAYMATERIAL_SPECULAR3_TRANSPTEXMIXMODE_3; VRAYMATERIAL_SPECULAR3_TRANSPTEXMIXMODE_4; VRAYMATERIAL_SPECULAR3_TRANSPTEXMIXMODE_5; VRAYMATERIAL_SPECULAR3_TRANSPTEXMIXMODE_6; VRAYMATERIAL_SPECULAR3_TRANSPTEXMIXMODE_7; VRAYMATERIAL_SPECULAR3_TRANSPTEXMIXMODE_8; VRAYMATERIAL_SPECULAR3_TRANSPTEXMIXMODE_9; VRAYMATERIAL_SPECULAR3_TRANSPTEXMIXMODE_10; VRAYMATERIAL_SPECULAR3_TRANSPTEXMIXMODE_11; VRAYMATERIAL_SPECULAR3_TRANSPTEXMIXMODE_12;}}
				REAL VRAYMATERIAL_SPECULAR3_TRANSPTEXMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				BOOL VRAYMATERIAL_SPECULAR3_TRANSP_TEXINVERT {}
			}

			SEPARATOR {LINE; }

			GROUP VRAYMATERIAL_SPECULAR3_FRESNELPANEL
			{
				DEFAULT 1;

				REAL VRAYMATERIAL_SPECULAR3_FRESNELIOR1 {MIN 0; STEP 0.01;}
				//REAL VRAYMATERIAL_SPECULAR3_FRESNELIOR2 {MIN 1; STEP 0.01;}
				SEPARATOR {}
				COLOR VRAYMATERIAL_SPECULAR3_FRESNELREFLCOL { }
				SHADERLINK VRAYMATERIAL_SPECULAR3_FRESNELREFLSHADER { }
				BOOL VRAYMATERIAL_SPECULAR3_FRESNELREFL_TEXINVERT { }

				SEPARATOR {}

				COLOR VRAYMATERIAL_SPECULAR3_FRESNELREFRCOL { }
				SHADERLINK VRAYMATERIAL_SPECULAR3_FRESNELREFRSHADER { }
				BOOL VRAYMATERIAL_SPECULAR3_FRESNELREFR_TEXINVERT { }
			}
			
			SEPARATOR {LINE; }

			GROUP VRAYMATERIAL_SPECULAR3_OPTIONSPANEL
			{
				DEFAULT 1;

				GROUP
				{
					COLUMNS 3;
					
					BOOL VRAYMATERIAL_SPECULAR3_USEFRESNEL { }
					BOOL VRAYMATERIAL_SPECULAR3_FIXDARKEDGES {}
					BOOL VRAYMATERIAL_SPECULAR3_LINKGLOSSINESS {}
				}
				
				SEPARATOR {LINE; }
				
				REAL VRAYMATERIAL_SPECULAR3_HIGHLIGHTGLOSS {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				SEPARATOR {}
				SHADERLINK VRAYMATERIAL_SPECULAR3_HIGHLIGHTGLOSSSHADER { }
				REAL VRAYMATERIAL_SPECULAR3_HIGHLIGHTGLOSSTEXMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				BOOL VRAYMATERIAL_SPECULAR3_HIGLOSS_TEXINVERT {}
				SEPARATOR {LINE; }
				REAL VRAYMATERIAL_SPECULAR3_REFLECTIONGLOSS {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				SEPARATOR {}
				SHADERLINK VRAYMATERIAL_SPECULAR3_REFLECTIONGLOSSSHADER { }
				REAL VRAYMATERIAL_SPECULAR3_REFLECTIONGLOSSTEXMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				BOOL VRAYMATERIAL_SPECULAR3_REFLGLOSS_TEXINVERT {}

				SEPARATOR {LINE; }

				LONG VRAYMATERIAL_SPECULAR3_SUBDIV {MIN 0; MAX 512;}
			}
				
				SEPARATOR {LINE;}
				
			GROUP VRAYMATERIAL_SPECULAR3_EXPERTPANEL
			{
				DEFAULT 0;
				
				GROUP
				{
					COLUMNS 3;
					
					//First group
					BOOL VRAYMATERIAL_SPECULAR3_TRACEREFL { }
					BOOL VRAYMATERIAL_SPECULAR3_TRACESPEC { }
					LONG VRAYMATERIAL_SPECULAR3_TRACEDEPTH {MIN -1;}
					
					//Second group
					BOOL VRAYMATERIAL_SPECULAR3_BACKSIDE { }
					REAL VRAYMATERIAL_SPECULAR3_SOFTENEDGES {MIN -1; MAX 1; STEP 0.01;}
					REAL VRAYMATERIAL_SPECULAR3_CUTOFF {MIN 0; MAX 1; STEP 0.001;}
					
					//Third group
					BOOL VRAYMATERIAL_SPECULAR3_REFLECTDIMDISTON {}
					REAL VRAYMATERIAL_SPECULAR3_REFLECTDIMDISTANCE {MIN 0; STEP 0.1;}
					REAL VRAYMATERIAL_SPECULAR3_REFLECTDIMDISTFALLOFF {MIN 0; MAX 1.0; STEP 0.01;}				
				}
				
				SEPARATOR { LINE; }
				
				LONG VRAYMATERIAL_SPECULAR3_GIGLOSSY
				{
					CYCLE
					{
						VRAYMATERIAL_SPECULAR3_GIGLOSSY_0;
						VRAYMATERIAL_SPECULAR3_GIGLOSSY_1;
						VRAYMATERIAL_SPECULAR3_GIGLOSSY_2;
					}
				}

				SEPARATOR {}
					
				LONG VRAYMATERIAL_SPECULAR3_DOALPHA
				{
					CYCLE
					{
						VRAYMATERIAL_SPECULAR3_DOALPHA_0;
						VRAYMATERIAL_SPECULAR3_DOALPHA_1;
						VRAYMATERIAL_SPECULAR3_DOALPHA_2;
					}
				}			
								
				SEPARATOR {}
				
				COLOR VRAYMATERIAL_SPECULAR3_EXITCOLOR { }

				SEPARATOR {LINE; }
				
				GROUP
				{
					COLUMNS 3;
					
					//First group
					BOOL VRAYMATERIAL_SPECULAR3_INTERPOLATION { }
					LONG VRAYMATERIAL_SPECULAR3_IMAPMIN { }
					LONG VRAYMATERIAL_SPECULAR3_IMAPMAX { }
					
					//Second group
					REAL VRAYMATERIAL_SPECULAR3_CLRTHRESHOLD { MIN 0.0; MAX 1.0; }
					REAL VRAYMATERIAL_SPECULAR3_NMLTHRESHOLD { MIN 0.0; MAX 1.0; }
					LONG VRAYMATERIAL_SPECULAR3_IMAPSAMPLES { MIN 0; MAX 100; }
				
				}
			}
			
			SEPARATOR {LINE; }

			GROUP VRAYMATERIAL_SPECULAR3_ANISOTROPYPANEL
			{
				DEFAULT 0;
				
				REAL VRAYMATERIAL_SPECULAR3_ANISOTROPY {MIN -1; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				SHADERLINK VRAYMATERIAL_SPECULAR3_ANISOTROPYSHADER { }
				BOOL VRAYMATERIAL_SPECULAR3_ANISO_TEXINVERT {}
				
				SEPARATOR {}
				
				REAL VRAYMATERIAL_SPECULAR3_ANISOTROPYROT {UNIT DEGREE; MIN 0; MAX 360; STEP 0.1; CUSTOMGUI REALSLIDER;}
				LONG VRAYMATERIAL_SPECULAR3_ANISOTROPYAXIS
				{
					CYCLE
					{
						VRAYMATERIAL_SPECULAR3_ANISOTROPYAXIS_0;
						VRAYMATERIAL_SPECULAR3_ANISOTROPYAXIS_1;
						VRAYMATERIAL_SPECULAR3_ANISOTROPYAXIS_2;
					}
				}
						
				SHADERLINK VRAYMATERIAL_SPECULAR3_ANISOTROPYROTSHADER { }
				BOOL VRAYMATERIAL_SPECULAR3_ANISOROT_TEXINVERT {}
			}
	}


	/// SPECULAR 2 ///
	GROUP ID_VRAYMATERIALGROUP_SPECULAR2
	{
			HIDDEN;

			GROUP VRAYMATERIAL_SPECULAR2_BRDFMODE
			{
				DEFAULT 1;

				LONG VRAYMATERIAL_SPECULAR2_MODE	{ CYCLE { VRAYMATERIAL_SPECULAR2_MODE_PHONG; VRAYMATERIAL_SPECULAR2_MODE_BLINN; VRAYMATERIAL_SPECULAR2_MODE_WARD;} }
			}

			SEPARATOR {LINE;}

			GROUP VRAYMATERIAL_SPECULAR2_COLORPANEL
			{
				DEFAULT 1;

				COLOR VRAYMATERIAL_SPECULAR2_COLOR { OPEN; }
				REAL VRAYMATERIAL_SPECULAR2_COLOR_MULT {MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
				SEPARATOR {}
				SHADERLINK VRAYMATERIAL_SPECULAR2_SHADER { }
				LONG VRAYMATERIAL_SPECULAR2_TEXTUREMIXMODE {CYCLE{VRAYMATERIAL_SPECULAR2_TEXTUREMIXMODE_0; VRAYMATERIAL_SPECULAR2_TEXTUREMIXMODE_1; VRAYMATERIAL_SPECULAR2_TEXTUREMIXMODE_2; VRAYMATERIAL_SPECULAR2_TEXTUREMIXMODE_3; VRAYMATERIAL_SPECULAR2_TEXTUREMIXMODE_4; VRAYMATERIAL_SPECULAR2_TEXTUREMIXMODE_5; VRAYMATERIAL_SPECULAR2_TEXTUREMIXMODE_6; VRAYMATERIAL_SPECULAR2_TEXTUREMIXMODE_7; VRAYMATERIAL_SPECULAR2_TEXTUREMIXMODE_8; VRAYMATERIAL_SPECULAR2_TEXTUREMIXMODE_9; VRAYMATERIAL_SPECULAR2_TEXTUREMIXMODE_10; VRAYMATERIAL_SPECULAR2_TEXTUREMIXMODE_11; VRAYMATERIAL_SPECULAR2_TEXTUREMIXMODE_12;}}
				REAL VRAYMATERIAL_SPECULAR2_TEXTUREMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
			}

			SEPARATOR {LINE; }

			GROUP VRAYMATERIAL_SPECULAR2_TRANSPPANEL
			{
				DEFAULT 1;

				COLOR	VRAYMATERIAL_SPECULAR2_TRANSP { OPEN; }
				REAL VRAYMATERIAL_SPECULAR2_TRANSP_MULT {MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
				SEPARATOR { }
				SHADERLINK VRAYMATERIAL_SPECULAR2_TRANSPSHADER { }
				LONG VRAYMATERIAL_SPECULAR2_TRANSPTEXMIXMODE {CYCLE{VRAYMATERIAL_SPECULAR2_TRANSPTEXMIXMODE_0; VRAYMATERIAL_SPECULAR2_TRANSPTEXMIXMODE_1; VRAYMATERIAL_SPECULAR2_TRANSPTEXMIXMODE_2; VRAYMATERIAL_SPECULAR2_TRANSPTEXMIXMODE_3; VRAYMATERIAL_SPECULAR2_TRANSPTEXMIXMODE_4; VRAYMATERIAL_SPECULAR2_TRANSPTEXMIXMODE_5; VRAYMATERIAL_SPECULAR2_TRANSPTEXMIXMODE_6; VRAYMATERIAL_SPECULAR2_TRANSPTEXMIXMODE_7; VRAYMATERIAL_SPECULAR2_TRANSPTEXMIXMODE_8; VRAYMATERIAL_SPECULAR2_TRANSPTEXMIXMODE_9; VRAYMATERIAL_SPECULAR2_TRANSPTEXMIXMODE_10; VRAYMATERIAL_SPECULAR2_TRANSPTEXMIXMODE_11; VRAYMATERIAL_SPECULAR2_TRANSPTEXMIXMODE_12;}}
				REAL VRAYMATERIAL_SPECULAR2_TRANSPTEXMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				BOOL VRAYMATERIAL_SPECULAR2_TRANSP_TEXINVERT {}
			}

			SEPARATOR {LINE; }

			GROUP VRAYMATERIAL_SPECULAR2_FRESNELPANEL
			{
				DEFAULT 1;

				REAL VRAYMATERIAL_SPECULAR2_FRESNELIOR1 {MIN 0; STEP 0.01;}
				//REAL VRAYMATERIAL_SPECULAR2_FRESNELIOR2 {MIN 1; STEP 0.01;}
				SEPARATOR {}
				COLOR VRAYMATERIAL_SPECULAR2_FRESNELREFLCOL { }
				SHADERLINK VRAYMATERIAL_SPECULAR2_FRESNELREFLSHADER { }
				BOOL VRAYMATERIAL_SPECULAR2_FRESNELREFL_TEXINVERT { }

				SEPARATOR { }

				COLOR VRAYMATERIAL_SPECULAR2_FRESNELREFRCOL { }
				SHADERLINK VRAYMATERIAL_SPECULAR2_FRESNELREFRSHADER { }
				BOOL VRAYMATERIAL_SPECULAR2_FRESNELREFR_TEXINVERT { }
			}

			SEPARATOR {LINE; }
			
			GROUP VRAYMATERIAL_SPECULAR2_OPTIONSPANEL
			{
				DEFAULT 1;

				GROUP
				{
					COLUMNS 3;
					
					BOOL VRAYMATERIAL_SPECULAR2_USEFRESNEL { }
					BOOL VRAYMATERIAL_SPECULAR2_FIXDARKEDGES {}
					BOOL VRAYMATERIAL_SPECULAR2_LINKGLOSSINESS {}
				}
				
				SEPARATOR {LINE; }
				
				REAL VRAYMATERIAL_SPECULAR2_HIGHLIGHTGLOSS {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				SEPARATOR {}
				SHADERLINK VRAYMATERIAL_SPECULAR2_HIGHLIGHTGLOSSSHADER { }
				REAL VRAYMATERIAL_SPECULAR2_HIGHLIGHTGLOSSTEXMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				BOOL VRAYMATERIAL_SPECULAR2_HIGLOSS_TEXINVERT {}
				SEPARATOR {LINE; }
				REAL VRAYMATERIAL_SPECULAR2_REFLECTIONGLOSS {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				SEPARATOR {}
				SHADERLINK VRAYMATERIAL_SPECULAR2_REFLECTIONGLOSSSHADER { }
				REAL VRAYMATERIAL_SPECULAR2_REFLECTIONGLOSSTEXMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				BOOL VRAYMATERIAL_SPECULAR2_REFLGLOSS_TEXINVERT {}

				SEPARATOR {LINE; }

				LONG VRAYMATERIAL_SPECULAR2_SUBDIV {MIN 0; MAX 512;}
			}
				
				SEPARATOR {LINE;}
				
			GROUP VRAYMATERIAL_SPECULAR2_EXPERTPANEL
			{
				DEFAULT 0;
				
				GROUP
				{
					COLUMNS 3;
					
					//First group
					BOOL VRAYMATERIAL_SPECULAR2_TRACEREFL { }
					BOOL VRAYMATERIAL_SPECULAR2_TRACESPEC { }
					LONG VRAYMATERIAL_SPECULAR2_TRACEDEPTH {MIN -1;}
					
					//Second group
					BOOL VRAYMATERIAL_SPECULAR2_BACKSIDE { }
					REAL VRAYMATERIAL_SPECULAR2_SOFTENEDGES {MIN -1; MAX 1; STEP 0.01;}
					REAL VRAYMATERIAL_SPECULAR2_CUTOFF {MIN 0; MAX 1; STEP 0.001;}
					
					//Third group
					BOOL VRAYMATERIAL_SPECULAR2_REFLECTDIMDISTON {}
					REAL VRAYMATERIAL_SPECULAR2_REFLECTDIMDISTANCE {MIN 0; STEP 0.1;}
					REAL VRAYMATERIAL_SPECULAR2_REFLECTDIMDISTFALLOFF {MIN 0; MAX 1.0; STEP 0.01;}
				}
				
				SEPARATOR { LINE; }
				
				LONG VRAYMATERIAL_SPECULAR2_GIGLOSSY
				{
					CYCLE
					{
						VRAYMATERIAL_SPECULAR2_GIGLOSSY_0;
						VRAYMATERIAL_SPECULAR2_GIGLOSSY_1;
						VRAYMATERIAL_SPECULAR2_GIGLOSSY_2;
					}
				}

				SEPARATOR {}
					
				LONG VRAYMATERIAL_SPECULAR2_DOALPHA
				{
					CYCLE
					{
						VRAYMATERIAL_SPECULAR2_DOALPHA_0;
						VRAYMATERIAL_SPECULAR2_DOALPHA_1;
						VRAYMATERIAL_SPECULAR2_DOALPHA_2;
					}
				}			
								
				SEPARATOR {}
				
				COLOR VRAYMATERIAL_SPECULAR2_EXITCOLOR { }

				SEPARATOR {LINE; }
				
				GROUP
				{
					COLUMNS 3;
					
					//First group
					BOOL VRAYMATERIAL_SPECULAR2_INTERPOLATION { }
					LONG VRAYMATERIAL_SPECULAR2_IMAPMIN { }
					LONG VRAYMATERIAL_SPECULAR2_IMAPMAX { }
					
					//Second group
					REAL VRAYMATERIAL_SPECULAR2_CLRTHRESHOLD { MIN 0.0; MAX 1.0; }
					REAL VRAYMATERIAL_SPECULAR2_NMLTHRESHOLD { MIN 0.0; MAX 1.0; }
					LONG VRAYMATERIAL_SPECULAR2_IMAPSAMPLES { MIN 0; MAX 100; }
				
				}
			}
			
			SEPARATOR {LINE; }
			
			GROUP VRAYMATERIAL_SPECULAR2_ANISOTROPYPANEL
			{	
				DEFAULT 0;
				
				REAL VRAYMATERIAL_SPECULAR2_ANISOTROPY {MIN -1; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				SHADERLINK VRAYMATERIAL_SPECULAR2_ANISOTROPYSHADER { }
				BOOL VRAYMATERIAL_SPECULAR2_ANISO_TEXINVERT {}
				
				SEPARATOR {}
				
				REAL VRAYMATERIAL_SPECULAR2_ANISOTROPYROT {UNIT DEGREE; MIN 0; MAX 360; STEP 0.1; CUSTOMGUI REALSLIDER;}
				LONG VRAYMATERIAL_SPECULAR2_ANISOTROPYAXIS
				{
					CYCLE
					{
						VRAYMATERIAL_SPECULAR2_ANISOTROPYAXIS_0;
						VRAYMATERIAL_SPECULAR2_ANISOTROPYAXIS_1;
						VRAYMATERIAL_SPECULAR2_ANISOTROPYAXIS_2;
					}
				}
						
				SHADERLINK VRAYMATERIAL_SPECULAR2_ANISOTROPYROTSHADER { }
				BOOL VRAYMATERIAL_SPECULAR2_ANISOROT_TEXINVERT {}
			}
	}


	/// SPECULAR 1 ///
	GROUP ID_VRAYMATERIALGROUP_SPECULAR1
	{
			HIDDEN;

			GROUP VRAYMATERIAL_SPECULAR1_BRDFMODE
			{
				DEFAULT 1;

				LONG VRAYMATERIAL_SPECULAR1_MODE	{ CYCLE { VRAYMATERIAL_SPECULAR1_MODE_PHONG; VRAYMATERIAL_SPECULAR1_MODE_BLINN; VRAYMATERIAL_SPECULAR1_MODE_WARD;} }
			}

			SEPARATOR {LINE;}

			GROUP VRAYMATERIAL_SPECULAR1_COLORPANEL
			{
				DEFAULT 1;

				COLOR VRAYMATERIAL_SPECULAR1_COLOR { OPEN; }
				REAL VRAYMATERIAL_SPECULAR1_COLOR_MULT {MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
				SEPARATOR {}
				SHADERLINK VRAYMATERIAL_SPECULAR1_SHADER { }
				LONG VRAYMATERIAL_SPECULAR1_TEXTUREMIXMODE {CYCLE{VRAYMATERIAL_SPECULAR1_TEXTUREMIXMODE_0; VRAYMATERIAL_SPECULAR1_TEXTUREMIXMODE_1; VRAYMATERIAL_SPECULAR1_TEXTUREMIXMODE_2; VRAYMATERIAL_SPECULAR1_TEXTUREMIXMODE_3; VRAYMATERIAL_SPECULAR1_TEXTUREMIXMODE_4; VRAYMATERIAL_SPECULAR1_TEXTUREMIXMODE_5; VRAYMATERIAL_SPECULAR1_TEXTUREMIXMODE_6; VRAYMATERIAL_SPECULAR1_TEXTUREMIXMODE_7; VRAYMATERIAL_SPECULAR1_TEXTUREMIXMODE_8; VRAYMATERIAL_SPECULAR1_TEXTUREMIXMODE_9; VRAYMATERIAL_SPECULAR1_TEXTUREMIXMODE_10; VRAYMATERIAL_SPECULAR1_TEXTUREMIXMODE_11; VRAYMATERIAL_SPECULAR1_TEXTUREMIXMODE_12;}}
				REAL VRAYMATERIAL_SPECULAR1_TEXTUREMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
			}

			SEPARATOR {LINE; }

			GROUP VRAYMATERIAL_SPECULAR1_TRANSPPANEL
			{
				DEFAULT 1;

				COLOR	VRAYMATERIAL_SPECULAR1_TRANSP { OPEN; }
				REAL VRAYMATERIAL_SPECULAR1_TRANSP_MULT {MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
				SEPARATOR { }
				SHADERLINK VRAYMATERIAL_SPECULAR1_TRANSPSHADER { }
				LONG VRAYMATERIAL_SPECULAR1_TRANSPTEXMIXMODE {CYCLE{VRAYMATERIAL_SPECULAR1_TRANSPTEXMIXMODE_0; VRAYMATERIAL_SPECULAR1_TRANSPTEXMIXMODE_1; VRAYMATERIAL_SPECULAR1_TRANSPTEXMIXMODE_2; VRAYMATERIAL_SPECULAR1_TRANSPTEXMIXMODE_3; VRAYMATERIAL_SPECULAR1_TRANSPTEXMIXMODE_4; VRAYMATERIAL_SPECULAR1_TRANSPTEXMIXMODE_5; VRAYMATERIAL_SPECULAR1_TRANSPTEXMIXMODE_6; VRAYMATERIAL_SPECULAR1_TRANSPTEXMIXMODE_7; VRAYMATERIAL_SPECULAR1_TRANSPTEXMIXMODE_8; VRAYMATERIAL_SPECULAR1_TRANSPTEXMIXMODE_9; VRAYMATERIAL_SPECULAR1_TRANSPTEXMIXMODE_10; VRAYMATERIAL_SPECULAR1_TRANSPTEXMIXMODE_11; VRAYMATERIAL_SPECULAR1_TRANSPTEXMIXMODE_12;}}
				REAL VRAYMATERIAL_SPECULAR1_TRANSPTEXMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				BOOL VRAYMATERIAL_SPECULAR1_TRANSP_TEXINVERT {}
			}

			SEPARATOR {LINE; }

			GROUP VRAYMATERIAL_SPECULAR1_FRESNELPANEL
			{
				DEFAULT 1;

				REAL VRAYMATERIAL_SPECULAR1_FRESNELIOR1 {MIN 0; STEP 0.01;}
				//REAL VRAYMATERIAL_SPECULAR1_FRESNELIOR2 {MIN 1; STEP 0.01;}
				SEPARATOR {}
				COLOR VRAYMATERIAL_SPECULAR1_FRESNELREFLCOL { }
				SHADERLINK VRAYMATERIAL_SPECULAR1_FRESNELREFLSHADER { }
				BOOL VRAYMATERIAL_SPECULAR1_FRESNELREFL_TEXINVERT { }

				SEPARATOR { }

				COLOR VRAYMATERIAL_SPECULAR1_FRESNELREFRCOL { }
				SHADERLINK VRAYMATERIAL_SPECULAR1_FRESNELREFRSHADER { }
				BOOL VRAYMATERIAL_SPECULAR1_FRESNELREFR_TEXINVERT { }
			}

			SEPARATOR {LINE; }
			
			GROUP VRAYMATERIAL_SPECULAR1_OPTIONSPANEL
			{
				DEFAULT 1;

				GROUP
				{
					COLUMNS 3;
					
					BOOL VRAYMATERIAL_SPECULAR1_USEFRESNEL { }
					BOOL VRAYMATERIAL_SPECULAR1_FIXDARKEDGES {}
					BOOL VRAYMATERIAL_SPECULAR1_LINKGLOSSINESS {}
				}
				
				SEPARATOR {LINE; }
				
				REAL VRAYMATERIAL_SPECULAR1_HIGHLIGHTGLOSS {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				SEPARATOR {}
				SHADERLINK VRAYMATERIAL_SPECULAR1_HIGHLIGHTGLOSSSHADER { }
				REAL VRAYMATERIAL_SPECULAR1_HIGHLIGHTGLOSSTEXMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				BOOL VRAYMATERIAL_SPECULAR1_HIGLOSS_TEXINVERT {}
				SEPARATOR {LINE; }
				REAL VRAYMATERIAL_SPECULAR1_REFLECTIONGLOSS {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				SEPARATOR {}
				SHADERLINK VRAYMATERIAL_SPECULAR1_REFLECTIONGLOSSSHADER { }
				REAL VRAYMATERIAL_SPECULAR1_REFLECTIONGLOSSTEXMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				BOOL VRAYMATERIAL_SPECULAR1_REFLGLOSS_TEXINVERT {}

				SEPARATOR {LINE; }

				LONG VRAYMATERIAL_SPECULAR1_SUBDIV {MIN 0; MAX 512;}
			}
				
				SEPARATOR {LINE;}
				
			GROUP VRAYMATERIAL_SPECULAR1_EXPERTPANEL
			{
				DEFAULT 0;
				
				GROUP
				{
					COLUMNS 3;
					
					//First group
					BOOL VRAYMATERIAL_SPECULAR1_TRACEREFL { }
					BOOL VRAYMATERIAL_SPECULAR1_TRACESPEC { }
					LONG VRAYMATERIAL_SPECULAR1_TRACEDEPTH {MIN -1;}
					
					//Second group
					BOOL VRAYMATERIAL_SPECULAR1_BACKSIDE { }
					REAL VRAYMATERIAL_SPECULAR1_SOFTENEDGES {MIN -1; MAX 1; STEP 0.01;}
					REAL VRAYMATERIAL_SPECULAR1_CUTOFF {MIN 0; MAX 1; STEP 0.001;}
					
					//Third group
					BOOL VRAYMATERIAL_SPECULAR1_REFLECTDIMDISTON {}
					REAL VRAYMATERIAL_SPECULAR1_REFLECTDIMDISTANCE {MIN 0; STEP 0.1;}
					REAL VRAYMATERIAL_SPECULAR1_REFLECTDIMDISTFALLOFF {MIN 0; MAX 1.0; STEP 0.01;}
				}
				
				SEPARATOR { LINE; }
				
				LONG VRAYMATERIAL_SPECULAR1_GIGLOSSY
				{
					CYCLE
					{
						VRAYMATERIAL_SPECULAR1_GIGLOSSY_0;
						VRAYMATERIAL_SPECULAR1_GIGLOSSY_1;
						VRAYMATERIAL_SPECULAR1_GIGLOSSY_2;
					}
				}

				SEPARATOR {}
					
				LONG VRAYMATERIAL_SPECULAR1_DOALPHA
				{
					CYCLE
					{
						VRAYMATERIAL_SPECULAR1_DOALPHA_0;
						VRAYMATERIAL_SPECULAR1_DOALPHA_1;
						VRAYMATERIAL_SPECULAR1_DOALPHA_2;
					}
				}			
								
				SEPARATOR {}
				
				COLOR VRAYMATERIAL_SPECULAR1_EXITCOLOR { }

				SEPARATOR {LINE; }
				
				GROUP
				{
					COLUMNS 3;
					
					//First group
					BOOL VRAYMATERIAL_SPECULAR1_INTERPOLATION { }
					LONG VRAYMATERIAL_SPECULAR1_IMAPMIN { }
					LONG VRAYMATERIAL_SPECULAR1_IMAPMAX { }
					
					//Second group
					REAL VRAYMATERIAL_SPECULAR1_CLRTHRESHOLD { MIN 0.0; MAX 1.0; }
					REAL VRAYMATERIAL_SPECULAR1_NMLTHRESHOLD { MIN 0.0; MAX 1.0; }
					LONG VRAYMATERIAL_SPECULAR1_IMAPSAMPLES { MIN 0; MAX 100; }
				
				}
			}
			
			SEPARATOR {LINE; }
			
			GROUP VRAYMATERIAL_SPECULAR1_ANISOTROPYPANEL
			{
				DEFAULT 0;
				
				REAL VRAYMATERIAL_SPECULAR1_ANISOTROPY {MIN -1; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				SHADERLINK VRAYMATERIAL_SPECULAR1_ANISOTROPYSHADER { }
				BOOL VRAYMATERIAL_SPECULAR1_ANISO_TEXINVERT {}
				
				SEPARATOR {}
				
				REAL VRAYMATERIAL_SPECULAR1_ANISOTROPYROT {UNIT DEGREE; MIN 0; MAX 360; STEP 0.1; CUSTOMGUI REALSLIDER;}
				LONG VRAYMATERIAL_SPECULAR1_ANISOTROPYAXIS
				{
					CYCLE
					{
						VRAYMATERIAL_SPECULAR1_ANISOTROPYAXIS_0;
						VRAYMATERIAL_SPECULAR1_ANISOTROPYAXIS_1;
						VRAYMATERIAL_SPECULAR1_ANISOTROPYAXIS_2;
					}
				}
						
				SHADERLINK VRAYMATERIAL_SPECULAR1_ANISOTROPYROTSHADER { }
				BOOL VRAYMATERIAL_SPECULAR1_ANISOROT_TEXINVERT {}
			}
	}


	GROUP ID_VRAYMATERIALGROUP_COLOR
	{
		DEFAULT 1;

		GROUP VRAYMATERIAL_COLOR1_COLORPANEL
		{
			DEFAULT 1; HIDDEN;

			COLOR VRAYMATERIAL_COLOR1_COLOR { OPEN; }
			REAL VRAYMATERIAL_COLOR1_MULT {MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
			SEPARATOR {}
			SHADERLINK VRAYMATERIAL_COLOR1_SHADER { }
			LONG VRAYMATERIAL_COLOR1_TEXTUREMIXMODE {CYCLE{VRAYMATERIAL_COLOR1_TEXTUREMIXMODE_0; VRAYMATERIAL_COLOR1_TEXTUREMIXMODE_1; VRAYMATERIAL_COLOR1_TEXTUREMIXMODE_2; VRAYMATERIAL_COLOR1_TEXTUREMIXMODE_3; VRAYMATERIAL_COLOR1_TEXTUREMIXMODE_4; VRAYMATERIAL_COLOR1_TEXTUREMIXMODE_5; VRAYMATERIAL_COLOR1_TEXTUREMIXMODE_6; VRAYMATERIAL_COLOR1_TEXTUREMIXMODE_7; VRAYMATERIAL_COLOR1_TEXTUREMIXMODE_8; VRAYMATERIAL_COLOR1_TEXTUREMIXMODE_9; VRAYMATERIAL_COLOR1_TEXTUREMIXMODE_10; VRAYMATERIAL_COLOR1_TEXTUREMIXMODE_11; VRAYMATERIAL_COLOR1_TEXTUREMIXMODE_12;}}
			REAL VRAYMATERIAL_COLOR1_TEXTUREMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}		
		}
		
		GROUP VRAYMATERIAL_COLOR1_VRAYDIRTPANEL
		{
			DEFAULT 1; HIDDEN;
			REAL VRAYMATERIAL_COLOR1_DIRTRADIUS {MIN 0; STEP 0.1;}
			SHADERLINK VRAYMATERIAL_COLOR1_DIRTRADIUSTEX {}
			SEPARATOR {}
			SHADERLINK VRAYMATERIAL_COLOR1_DIRTOCCLUDED {}
			SHADERLINK VRAYMATERIAL_COLOR1_DIRTUNOCCLUDED {}
			SEPARATOR {}
			REAL VRAYMATERIAL_COLOR1_DIRTDISTRIB {MIN 0; STEP 0.1;}
			REAL VRAYMATERIAL_COLOR1_DIRTFALLOFF {MIN 0; STEP 0.1;}
			LONG VRAYMATERIAL_COLOR1_DIRTSUBDIVS {MIN 1;}
			VECTOR VRAYMATERIAL_COLOR1_DIRTBIAS {MIN -100; MAX 100;}
			BOOL VRAYMATERIAL_COLOR1_DIRTIGNOREGI {}
			BOOL VRAYMATERIAL_COLOR1_DIRTSAMEOBJONLY {}
			BOOL VRAYMATERIAL_COLOR1_DIRTINVERTNML {}
			BOOL VRAYMATERIAL_COLOR1_DIRTWORKTRANSP {}
			BOOL VRAYMATERIAL_COLOR1_DIRTIGNORESELFOCCLUSION {}
		}

		SEPARATOR {LINE; }

		GROUP VRAYMATERIAL_COLOR1_TRANSPPANEL
		{
			DEFAULT 1;

			COLOR	VRAYMATERIAL_COLOR1_TRANSP { OPEN; }
			REAL VRAYMATERIAL_COLOR1_TRANSP_MULT {MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
			SEPARATOR {}
			SHADERLINK VRAYMATERIAL_COLOR1_TRANSPSHADER { }
			LONG VRAYMATERIAL_COLOR1_TRANSPTEXMIXMODE {CYCLE{VRAYMATERIAL_COLOR1_TRANSPTEXMIXMODE_0; VRAYMATERIAL_COLOR1_TRANSPTEXMIXMODE_1; VRAYMATERIAL_COLOR1_TRANSPTEXMIXMODE_2; VRAYMATERIAL_COLOR1_TRANSPTEXMIXMODE_3; VRAYMATERIAL_COLOR1_TRANSPTEXMIXMODE_4; VRAYMATERIAL_COLOR1_TRANSPTEXMIXMODE_5; VRAYMATERIAL_COLOR1_TRANSPTEXMIXMODE_6; VRAYMATERIAL_COLOR1_TRANSPTEXMIXMODE_7; VRAYMATERIAL_COLOR1_TRANSPTEXMIXMODE_8; VRAYMATERIAL_COLOR1_TRANSPTEXMIXMODE_9; VRAYMATERIAL_COLOR1_TRANSPTEXMIXMODE_10; VRAYMATERIAL_COLOR1_TRANSPTEXMIXMODE_11; VRAYMATERIAL_COLOR1_TRANSPTEXMIXMODE_12;}}
			REAL VRAYMATERIAL_COLOR1_TRANSPTEXMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
			BOOL VRAYMATERIAL_COLOR1_TRANSP_TEXINVERT {}
		}
		
		GROUP VRAYMATERIAL_COLOR1_OPTIONSPANEL
		{
			DEFAULT 1;
			
			REAL VRAYMATERIAL_COLOR1_ROUGHNESS {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
			SHADERLINK VRAYMATERIAL_COLOR1_ROUGHNESSTEX {}
			SEPARATOR {}
			BOOL VRAYMATERIAL_COLOR1_USEIRMAP {}
			SEPARATOR {}
			BOOL VRAYMATERIAL_COLOR1_USEDIRT {}
			BOOL VRAYMATERIAL_COLOR1_USEDIRT2 {}
			LONG VRAYMATERIAL_COLOR1_DIRTCOMP
			{
				CYCLE
				{
					VRAYMATERIAL_COLOR1_DIRTCOMP_0;
					VRAYMATERIAL_COLOR1_DIRTCOMP_1;
					VRAYMATERIAL_COLOR1_DIRTCOMP_2;
					VRAYMATERIAL_COLOR1_DIRTCOMP_3;
					VRAYMATERIAL_COLOR1_DIRTCOMP_4;
					VRAYMATERIAL_COLOR1_DIRTCOMP_5;
					VRAYMATERIAL_COLOR1_DIRTCOMP_6;
				}
			}
		}
	}


	GROUP ID_VRAYMATERIALGROUP_COLOR2
	{
		HIDDEN;

		GROUP VRAYMATERIAL_COLOR2_COLORPANEL
		{
			DEFAULT 1; HIDDEN;

			COLOR	VRAYMATERIAL_COLOR2_COLOR { OPEN; }
			REAL VRAYMATERIAL_COLOR2_MULT {MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
			SEPARATOR {}
			SHADERLINK VRAYMATERIAL_COLOR2_SHADER { }
			LONG VRAYMATERIAL_COLOR2_TEXTUREMIXMODE {CYCLE{VRAYMATERIAL_COLOR2_TEXTUREMIXMODE_0; VRAYMATERIAL_COLOR2_TEXTUREMIXMODE_1; VRAYMATERIAL_COLOR2_TEXTUREMIXMODE_2; VRAYMATERIAL_COLOR2_TEXTUREMIXMODE_3; VRAYMATERIAL_COLOR2_TEXTUREMIXMODE_4; VRAYMATERIAL_COLOR2_TEXTUREMIXMODE_5; VRAYMATERIAL_COLOR2_TEXTUREMIXMODE_6; VRAYMATERIAL_COLOR2_TEXTUREMIXMODE_7; VRAYMATERIAL_COLOR2_TEXTUREMIXMODE_8; VRAYMATERIAL_COLOR2_TEXTUREMIXMODE_9; VRAYMATERIAL_COLOR2_TEXTUREMIXMODE_10; VRAYMATERIAL_COLOR2_TEXTUREMIXMODE_11; VRAYMATERIAL_COLOR2_TEXTUREMIXMODE_12;}}
			REAL VRAYMATERIAL_COLOR2_TEXTUREMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
		}
		
		GROUP VRAYMATERIAL_COLOR2_VRAYDIRTPANEL
		{
			DEFAULT 1; HIDDEN;
			
			REAL VRAYMATERIAL_COLOR2_DIRTRADIUS {MIN 0; STEP 0.1;}
			SHADERLINK VRAYMATERIAL_COLOR2_DIRTRADIUSTEX {}
			SEPARATOR {}
			SHADERLINK VRAYMATERIAL_COLOR2_DIRTOCCLUDED {}
			SHADERLINK VRAYMATERIAL_COLOR2_DIRTUNOCCLUDED {}
			SEPARATOR {}
			REAL VRAYMATERIAL_COLOR2_DIRTDISTRIB {MIN 0; STEP 0.1;}
			REAL VRAYMATERIAL_COLOR2_DIRTFALLOFF {MIN 0; STEP 0.1;}
			LONG VRAYMATERIAL_COLOR2_DIRTSUBDIVS {MIN 1;}
			VECTOR VRAYMATERIAL_COLOR2_DIRTBIAS {MIN -100; MAX 100;}
			BOOL VRAYMATERIAL_COLOR2_DIRTIGNOREGI {}
			BOOL VRAYMATERIAL_COLOR2_DIRTSAMEOBJONLY {}
			BOOL VRAYMATERIAL_COLOR2_DIRTINVERTNML {}
			BOOL VRAYMATERIAL_COLOR2_DIRTWORKTRANSP {}
			BOOL VRAYMATERIAL_COLOR2_DIRTIGNORESELFOCCLUSION {}
		}

		SEPARATOR {LINE; }

		GROUP VRAYMATERIAL_COLOR2_TRANSPPANEL
		{
			DEFAULT 1;

			COLOR	VRAYMATERIAL_COLOR2_TRANSP { OPEN; }
			REAL VRAYMATERIAL_COLOR2_TRANSP_MULT {MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
			SEPARATOR { }
			SHADERLINK VRAYMATERIAL_COLOR2_TRANSPSHADER { }
			LONG VRAYMATERIAL_COLOR2_TRANSPTEXMIXMODE {CYCLE{VRAYMATERIAL_COLOR2_TRANSPTEXMIXMODE_0; VRAYMATERIAL_COLOR2_TRANSPTEXMIXMODE_1; VRAYMATERIAL_COLOR2_TRANSPTEXMIXMODE_2; VRAYMATERIAL_COLOR2_TRANSPTEXMIXMODE_3; VRAYMATERIAL_COLOR2_TRANSPTEXMIXMODE_4; VRAYMATERIAL_COLOR2_TRANSPTEXMIXMODE_5; VRAYMATERIAL_COLOR2_TRANSPTEXMIXMODE_6; VRAYMATERIAL_COLOR2_TRANSPTEXMIXMODE_7; VRAYMATERIAL_COLOR2_TRANSPTEXMIXMODE_8; VRAYMATERIAL_COLOR2_TRANSPTEXMIXMODE_9; VRAYMATERIAL_COLOR2_TRANSPTEXMIXMODE_10; VRAYMATERIAL_COLOR2_TRANSPTEXMIXMODE_11; VRAYMATERIAL_COLOR2_TRANSPTEXMIXMODE_12;}}
			REAL VRAYMATERIAL_COLOR2_TRANSPTEXMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
			BOOL VRAYMATERIAL_COLOR2_TRANSP_TEXINVERT {}
		}
		
		GROUP VRAYMATERIAL_COLOR2_OPTIONSPANEL
		{
			DEFAULT 1;
			
			REAL VRAYMATERIAL_COLOR2_ROUGHNESS {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
			SHADERLINK VRAYMATERIAL_COLOR2_ROUGHNESSTEX {}
			SEPARATOR {}		
			BOOL VRAYMATERIAL_COLOR2_USEIRMAP {}
			SEPARATOR {}
			BOOL VRAYMATERIAL_COLOR2_USEDIRT {}
			BOOL VRAYMATERIAL_COLOR2_USEDIRT2 {}
			LONG VRAYMATERIAL_COLOR2_DIRTCOMP
			{
				CYCLE
				{
					VRAYMATERIAL_COLOR2_DIRTCOMP_0;
					VRAYMATERIAL_COLOR2_DIRTCOMP_1;
					VRAYMATERIAL_COLOR2_DIRTCOMP_2;
					VRAYMATERIAL_COLOR2_DIRTCOMP_3;
					VRAYMATERIAL_COLOR2_DIRTCOMP_4;
					VRAYMATERIAL_COLOR2_DIRTCOMP_5;
					VRAYMATERIAL_COLOR2_DIRTCOMP_6;
				}
			}
		}
	}


	GROUP ID_VRAYMATERIALGROUP_TRANSPARENCY
	{
		HIDDEN;

		GROUP	VRAYMATERIAL_TRANSPARENCY_COLORPANEL
		{
			DEFAULT 1;

			COLOR	VRAYMATERIAL_TRANSPARENCY_COLOR { OPEN; }
			REAL VRAYMATERIAL_TRANSPARENCY_COLOR_MULT {MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
			SEPARATOR {}
			SHADERLINK VRAYMATERIAL_TRANSPARENCY_SHADER { }
			LONG VRAYMATERIAL_TRANSPARENCY_TEXTUREMIXMODE {CYCLE{VRAYMATERIAL_TRANSPARENCY_TEXTUREMIXMODE_0; VRAYMATERIAL_TRANSPARENCY_TEXTUREMIXMODE_1; VRAYMATERIAL_TRANSPARENCY_TEXTUREMIXMODE_2; VRAYMATERIAL_TRANSPARENCY_TEXTUREMIXMODE_3; VRAYMATERIAL_TRANSPARENCY_TEXTUREMIXMODE_4; VRAYMATERIAL_TRANSPARENCY_TEXTUREMIXMODE_5; VRAYMATERIAL_TRANSPARENCY_TEXTUREMIXMODE_6; VRAYMATERIAL_TRANSPARENCY_TEXTUREMIXMODE_7; VRAYMATERIAL_TRANSPARENCY_TEXTUREMIXMODE_8; VRAYMATERIAL_TRANSPARENCY_TEXTUREMIXMODE_9; VRAYMATERIAL_TRANSPARENCY_TEXTUREMIXMODE_10; VRAYMATERIAL_TRANSPARENCY_TEXTUREMIXMODE_11; VRAYMATERIAL_TRANSPARENCY_TEXTUREMIXMODE_12;}}
			REAL VRAYMATERIAL_TRANSPARENCY_TEXTUREMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
		}

		SEPARATOR {LINE;}

		//GROUP VRAYMATERIAL_TRANSPARENCY_TRANSPPANEL
		//{
			//DEFAULT 1;

			//COLOR	VRAYMATERIAL_TRANSPARENCY_TRANSP { OPEN; }
			//REAL VRAYMATERIAL_TRANSPARENCY_TRANSP_MULT {MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
			//SEPARATOR {}
			//SHADERLINK VRAYMATERIAL_TRANSPARENCY_TRANSPSHADER { }
			//LONG VRAYMATERIAL_TRANSPARENCY_TRANSPTEXMIXMODE {CYCLE{VRAYMATERIAL_TRANSPARENCY_TRANSPTEXMIXMODE_0; VRAYMATERIAL_TRANSPARENCY_TRANSPTEXMIXMODE_1; VRAYMATERIAL_TRANSPARENCY_TRANSPTEXMIXMODE_2; VRAYMATERIAL_TRANSPARENCY_TRANSPTEXMIXMODE_3; VRAYMATERIAL_TRANSPARENCY_TRANSPTEXMIXMODE_4; VRAYMATERIAL_TRANSPARENCY_TRANSPTEXMIXMODE_5; VRAYMATERIAL_TRANSPARENCY_TRANSPTEXMIXMODE_6; VRAYMATERIAL_TRANSPARENCY_TRANSPTEXMIXMODE_7; VRAYMATERIAL_TRANSPARENCY_TRANSPTEXMIXMODE_8; VRAYMATERIAL_TRANSPARENCY_TRANSPTEXMIXMODE_9; VRAYMATERIAL_TRANSPARENCY_TRANSPTEXMIXMODE_10; VRAYMATERIAL_TRANSPARENCY_TRANSPTEXMIXMODE_11; VRAYMATERIAL_TRANSPARENCY_TRANSPTEXMIXMODE_12;}}
			//REAL VRAYMATERIAL_TRANSPARENCY_TRANSPTEXMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
		//}

		//SEPARATOR {LINE;}

		GROUP VRAYMATERIAL_TRANSPARENCY_REFRACTPANEL
		{
			DEFAULT 1;

			REAL VRAYMATERIAL_TRANSPARENCY_IOR {MIN 0; STEP 0.01;}
			REAL VRAYMATERIAL_TRANSPARENCY_CUTOFF {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
			BOOL VRAYMATERIAL_TRANSPARENCY_DOSHADOW { }

			LONG VRAYMATERIAL_TRANSPARENCY_DOALPHA
			{
				CYCLE
				{
					VRAYMATERIAL_TRANSPARENCY_DOALPHA_0;
					VRAYMATERIAL_TRANSPARENCY_DOALPHA_1;
					VRAYMATERIAL_TRANSPARENCY_DOALPHA_2;
				}
			}

			BOOL VRAYMATERIAL_TRANSPARENCY_TRACEREFR { }
           		LONG VRAYMATERIAL_TRANSPARENCY_TRACEDEPTH {MIN -1;}
            
            SEPARATOR {}
			
			BOOL  VRAYMATERIAL_TRANSPARENCY_EXITCOLORON { }	
			COLOR VRAYMATERIAL_TRANSPARENCY_REFLEXITCOLOR { }
			COLOR VRAYMATERIAL_TRANSPARENCY_REFREXITCOLOR { }
			
			SEPARATOR {}
			
			GROUP
			{
				COLUMNS 2;
				BOOL VRAYMATERIAL_TRANSPARENCY_DISPERSIONON {}
				REAL VRAYMATERIAL_TRANSPARENCY_DISPERSION {MIN 0; STEP 0.01;}
			}
			
			SEPARATOR {LINE;}

			REAL VRAYMATERIAL_TRANSPARENCY_GLOSSINESS {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
			LONG VRAYMATERIAL_TRANSPARENCY_SUBDIV {MIN 0; MAX 512;}
			SEPARATOR {}
			SHADERLINK VRAYMATERIAL_TRANSPARENCY_GLOSSINESSSHADER { }
			REAL VRAYMATERIAL_TRANSPARENCY_GLOSSINESSTEXMULT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
			BOOL VRAYMATERIAL_TRANSPARENCY_GLOSS_TEXINVERT {}

			SEPARATOR {LINE; }
				
			GROUP
			{
				COLUMNS 3;
					
				//First group
				BOOL VRAYMATERIAL_TRANSPARENCY_INTERPOLATION { }
				LONG VRAYMATERIAL_TRANSPARENCY_IMAPMIN { }
				LONG VRAYMATERIAL_TRANSPARENCY_IMAPMAX { }
					
				//Second group
				REAL VRAYMATERIAL_TRANSPARENCY_CLRTHRESHOLD { MIN 0.0; MAX 1.0; }
				REAL VRAYMATERIAL_TRANSPARENCY_NMLTHRESHOLD { MIN 0.0; MAX 1.0; }
				LONG VRAYMATERIAL_TRANSPARENCY_IMAPSAMPLES { MIN 0; MAX 100; }
				
			}
		}

		SEPARATOR {LINE; }

		GROUP VRAYMATERIAL_TRANSPARENCY_FOGPANEL
		{
			DEFAULT 1;

			BOOL VRAYMATERIAL_USE_VOLUME	{ }
			SEPARATOR {}
			REAL VRAYMATERIAL_VOLUME_IOR {MIN 0; STEP 0.01;}
			SEPARATOR { }
			COLOR VRAYMATERIAL_VOLUME_EMISSIONCOLOR {OPEN;}
			SEPARATOR {}
			COLOR VRAYMATERIAL_VOLUME_COLOR {OPEN; }
            SHADERLINK VRAYMATERIAL_VOLUME_COLORTEX { }
			REAL VRAYMATERIAL_VOLUME_COLOR_BRIGHTNESS {MIN 0; STEP 0.01; MAXSLIDER 1; CUSTOMGUI REALSLIDER;}
			SEPARATOR {}
			REAL VRAYMATERIAL_VOLUME_BIAS {MIN -1; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
		}

		SEPARATOR {LINE; }

		GROUP VRAYMATERIAL_TRANSPARENCY_SSSPANEL
		{
			DEFAULT 1;

			BOOL VRAYMATERIAL_VOLUME_SSSON {}
			SEPARATOR {}
			COLOR VRAYMATERIAL_COLOR1_SSSBACK { }
			SHADERLINK VRAYMATERIAL_COLOR1_SSSBACKSHADER {}
			SEPARATOR {}
			LONG VRAYMATERIAL_VOLUME_SUBDIV { MIN 0; MAX 512; }
			REAL VRAYMATERIAL_VOLUME_LIGHTMULT {UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100; STEP 0.1;}
			REAL VRAYMATERIAL_VOLUME_THICKNESS {UNIT METER; MIN 0; STEP 0.1;}
			REAL VRAYMATERIAL_VOLUME_SCATTERCOEFF {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
			REAL VRAYMATERIAL_VOLUME_SCATTERDIR {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
			LONG VRAYMATERIAL_VOLUME_SCATTERLEVELS {MIN 0; MAX 256;}
			BOOL VRAYMATERIAL_VOLUME_ENVIRONMENTFOG {}
		}

	}


	GROUP ID_VRAYMATERIALGROUP_SSS
	{
		HIDDEN;

		GROUP	VRAYMATERIAL_SSS_GENPANEL
		{
			DEFAULT 1;

			BOOL VRAYMATERIAL_SSS_GEOMSAMPLING {}
			LONG VRAYMATERIAL_SSS_PREPASS {MINSLIDER -4; MAXSLIDER 4; CUSTOMGUI LONGSLIDER;}
			LONG VRAYMATERIAL_SSS_PREPASSID {MIN 0;}
			REAL VRAYMATERIAL_SSS_SCALE {MIN 0; MAXSLIDER 5; STEP 0.01; CUSTOMGUI REALSLIDER;}
            REAL VRAYMATERIAL_SSS_IOR {MIN 1; STEP 0.01;}
            BOOL VRAYMATERIAL_SSS_AUTODENSITY {}
            REAL VRAYMATERIAL_SSS_SURFACEOFFSET {MIN 0.001; STEP 0.001;}
            REAL VRAYMATERIAL_SSS_SAMPLESPERUNITAREA {MIN 0.1; STEP 0.1;}
            BOOL VRAYMATERIAL_SSS_PREVIEWSAMPLES {}
            REAL VRAYMATERIAL_SSS_MAXDISTANCE {MIN 0.01; STEP 0.01;}
            COLOR VRAYMATERIAL_SSS_BGCOLOR {}
            COLOR VRAYMATERIAL_SSS_SAMPLESCOLOR {}
		}

		SEPARATOR {LINE;}

		GROUP VRAYMATERIAL_SSS_SCATTERPANEL
		{
			DEFAULT 1;

			COLOR	VRAYMATERIAL_SSS_OVERALLCOLOR { OPEN; }
			SEPARATOR { }
			SHADERLINK VRAYMATERIAL_SSS_OVERALLCOLORSHADER { }
			
			SEPARATOR {LINE;}
			
			COLOR	VRAYMATERIAL_SSS_SSSCOLOR { OPEN; }
			SEPARATOR { }
			SHADERLINK VRAYMATERIAL_SSS_SSSCOLORSHADER { }
			
			SEPARATOR {LINE;}
			
			COLOR	VRAYMATERIAL_SSS_SCATTERCOLOR { OPEN; }
			SEPARATOR { }
			SHADERLINK VRAYMATERIAL_SSS_SCATTERSHADER { }
			
			SEPARATOR {LINE;}
			
			REAL VRAYMATERIAL_SSS_SCATTERMULT {MIN 0; STEP 0.01; MAXSLIDER 5; CUSTOMGUI REALSLIDER;}
			SEPARATOR { }
			SHADERLINK VRAYMATERIAL_SSS_SCATTERMULTSHADER { }
			
			SEPARATOR {LINE;}
			
			REAL VRAYMATERIAL_SSS_PHASE {MIN -1; MAX 1; STEP 0.01; MAXSLIDER 1; CUSTOMGUI REALSLIDER;}
		}

		SEPARATOR {LINE; }

		GROUP VRAYMATERIAL_SSS_OPTIONSPANEL
		{
			DEFAULT 1;

			LONG VRAYMATERIAL_SSS_SINGLESCATTER { CYCLE { VRAYMATERIAL_SSS_SINGLESCATTER_0; VRAYMATERIAL_SSS_SINGLESCATTER_1; VRAYMATERIAL_SSS_SINGLESCATTER_2; VRAYMATERIAL_SSS_SINGLESCATTER_3;} }			
			LONG VRAYMATERIAL_SSS_SUBDIVS {MIN 0; MAXSLIDER 10; CUSTOMGUI LONGSLIDER;}
			LONG VRAYMATERIAL_SSS_REFRACTIONDEPTH { MIN 0; }
			BOOL VRAYMATERIAL_SSS_FRONTSCATTER { }
			BOOL VRAYMATERIAL_SSS_BACKSCATTER { }
			BOOL VRAYMATERIAL_SSS_SCATTERGI {}
			REAL VRAYMATERIAL_SSS_PREPASSLOD {MIN 0; STEP 0.01; MAXSLIDER 10; CUSTOMGUI REALSLIDER;}
			REAL VRAYMATERIAL_SSS_PREPASSBLUR {MIN 0; STEP 0.01; MAXSLIDER 4; CUSTOMGUI REALSLIDER;}
			LONG VRAYMATERIAL_SSS_PREPASSMODE { CYCLE { VRAYMATERIAL_SSS_PREPASSMODE_0; VRAYMATERIAL_SSS_PREPASSMODE_1; VRAYMATERIAL_SSS_PREPASSMODE_2; VRAYMATERIAL_SSS_PREPASSMODE_3; VRAYMATERIAL_SSS_PREPASSMODE_4;} }
			FILENAME VRAYMATERIAL_SSS_PREPASSFILENAMESAVE {SAVE; HIDDEN;}
			FILENAME VRAYMATERIAL_SSS_PREPASSFILENAMEOPEN {HIDDEN;}
		}
	}

	//INCLUDE Millum;

	//GROUP ID_VRAYMATERIALGROUP_ILLUMINATION
	//{
		//SEPARATOR { }

		//BOOL VRAYMATERIAL_ANIMATEPREVIEW { }


	//}

	INCLUDE Massign;
	LONG VRAYMATERIAL_NODE {HIDDEN;}
}
