#ifndef _MVrayCarPaintMaterial_H_
#define _MVrayCarPaintMaterial_H_

enum
{
	//ID_VRAYCARPAINTMATERIAL = 1029457,

	VRAYCARPAINTMATERIAL_SKIPPAGL = 6969,

	// Preview
	VRAYCARPAINTMATERIAL_PREVIEWSIZE = 500,
	VRAYCARPAINTMATERIAL_PREVIEWSIZE_DEF = 0,
	VRAYCARPAINTMATERIAL_PREVIEWSIZE_64 = 6,
	VRAYCARPAINTMATERIAL_PREVIEWSIZE_128 = 7,
	VRAYCARPAINTMATERIAL_PREVIEWSIZE_256 = 8,
	VRAYCARPAINTMATERIAL_PREVIEWSIZE_512 = 9,
	VRAYCARPAINTMATERIAL_PREVIEWSIZE_1024 = 10,
	VRAYCARPAINTMATERIAL_PREVIEWSIZE_2048 = 11,

	VRAYCARPAINTMATERIAL_ANIMATEPREVIEW = 501,

	ID_VRAYCARPAINTMATERIALGROUP_ILLUMINATION = 820,
	VRAYCARPAINTMATERIAL_PAGE_ILLUMINATION = 821,

	VRAYCARPAINTMATERIAL_MAT_PREVIEW = 1001,

	// Groups
	ID_VRAYCARPAINTMATERIALGROUP_PARAMS = 850,

	// Use Bool Parameters
	VRAYCARPAINTMATERIAL_PAGE_PARAMS = 2010,

	// Presets
	VRAYCARPAINTMATERIAL_PRESETS = 800,
	VRAYCARPAINTMATERIAL_PRESETS00 = 0,
	VRAYCARPAINTMATERIAL_PRESETS01 = 1,
	VRAYCARPAINTMATERIAL_PRESETS02 = 2,
	VRAYCARPAINTMATERIAL_PRESETS03 = 3,
	VRAYCARPAINTMATERIAL_PRESETS04 = 4,
	VRAYCARPAINTMATERIAL_PRESETS05 = 5,
	VRAYCARPAINTMATERIAL_SAVEPRESET = 801,

	VRAYCARPAINTMATERIAL_QUALITY = 806,
	VRAYCARPAINTMATERIAL_QUALITY_0 = 0,
	VRAYCARPAINTMATERIAL_QUALITY_1 = 1,
	VRAYCARPAINTMATERIAL_QUALITY_2 = 2,
	VRAYCARPAINTMATERIAL_GAMMA = 810,
	VRAYCARPAINTMATERIAL_OVERRIDABLE = 	811,
	VRAYCARPAINTMATERIAL_IDCOLOR  		,
	VRAYCARPAINTMATERIAL_ISROUNDED		,
	VRAYCARPAINTMATERIAL_ROUNDRADIUS	,
    VRAYCARPAINTMATERIAL_ID             ,
    
    // PANELS IDs
	VRAYCARPAINTMATERIAL_BASEPANEL = 4040,
	VRAYCARPAINTMATERIAL_FLAKESPANEL,
	VRAYCARPAINTMATERIAL_COATPANEL,
	VRAYCARPAINTMATERIAL_OPTIONSPANEL,

	// CarPaint
	VRAYCARPAINTMATERIAL_BASEBUMPTYPE = 4050,
	VRAYCARPAINTMATERIAL_BASEBUMPTYPE_0 = 0,
	VRAYCARPAINTMATERIAL_BASEBUMPTYPE_1 = 1,
	VRAYCARPAINTMATERIAL_BASEBUMPTYPE_2 = 2,
	VRAYCARPAINTMATERIAL_BASEBUMPTYPE_3 = 3,
    VRAYCARPAINTMATERIAL_BASEBUMPTYPE_4 = 4,
    VRAYCARPAINTMATERIAL_BASEBUMPTYPE_5 = 5,
    VRAYCARPAINTMATERIAL_BASEBUMPTYPE_6 = 6,
	VRAYCARPAINTMATERIAL_FLAKEFILTERING = 4051,
    VRAYCARPAINTMATERIAL_FLAKEFILTERING_0 = 0,
    VRAYCARPAINTMATERIAL_FLAKEFILTERING_1 = 1,
    VRAYCARPAINTMATERIAL_FLAKEMAPTYPE = 4052,
    VRAYCARPAINTMATERIAL_FLAKEMAPTYPE_0 = 0,
    VRAYCARPAINTMATERIAL_FLAKEMAPTYPE_1 = 1,
    VRAYCARPAINTMATERIAL_COATBUMPTYPE = 4053,
	VRAYCARPAINTMATERIAL_COATBUMPTYPE_0 = 0,
	VRAYCARPAINTMATERIAL_COATBUMPTYPE_1 = 1,
	VRAYCARPAINTMATERIAL_COATBUMPTYPE_2 = 2,
	VRAYCARPAINTMATERIAL_COATBUMPTYPE_3 = 3,
    VRAYCARPAINTMATERIAL_COATBUMPTYPE_4 = 4,
    VRAYCARPAINTMATERIAL_COATBUMPTYPE_5 = 5,
    VRAYCARPAINTMATERIAL_COATBUMPTYPE_6 = 6,
	VRAYCARPAINTMATERIAL_BASECOLOR = 4055,
	VRAYCARPAINTMATERIAL_BASEBUMPAMOUNT,
	VRAYCARPAINTMATERIAL_BASETRACEREFLECTION,
	VRAYCARPAINTMATERIAL_BASEREFLAMOUNT,
	VRAYCARPAINTMATERIAL_BASEREFLGLOSSINESS,
	VRAYCARPAINTMATERIAL_FLAKECOLOR,
	VRAYCARPAINTMATERIAL_FLAKEGLOSSINESS,
	VRAYCARPAINTMATERIAL_FLAKEORIENTATION,
	VRAYCARPAINTMATERIAL_FLAKEDENSITY,
	VRAYCARPAINTMATERIAL_FLAKESCALE,
	VRAYCARPAINTMATERIAL_FLAKESIZE,
	VRAYCARPAINTMATERIAL_FLAKEMAPSIZE,
	VRAYCARPAINTMATERIAL_FLAKESEED,
    VRAYCARPAINTMATERIAL_FLAKETRACEREFLECTION,
	VRAYCARPAINTMATERIAL_COATCOLOR,
	VRAYCARPAINTMATERIAL_COATSTRENGTH,
	VRAYCARPAINTMATERIAL_COATGLOSSINESS,
	VRAYCARPAINTMATERIAL_COATBUMPAMOUNT,
	VRAYCARPAINTMATERIAL_COATTRACEREFLECTIONS,
	VRAYCARPAINTMATERIAL_TRACEREFLECTIONS,
	VRAYCARPAINTMATERIAL_DOUBLESIDED,
	VRAYCARPAINTMATERIAL_SUBDIVS,
	VRAYCARPAINTMATERIAL_CUTOFF,
    VRAYCARPAINTMATERIAL_ENVPRIORITY,

	// Shaders
	VRAYCARPAINTMATERIAL_BASECOLORSHADER = 4100,
	VRAYCARPAINTMATERIAL_BASEBUMPSHADER,
	VRAYCARPAINTMATERIAL_BASEBUMPAMOUNTSHADER,
	VRAYCARPAINTMATERIAL_BASEREFLAMOUNTSHADER,
	VRAYCARPAINTMATERIAL_BASEREFLGLOSSINESSSHADER,
	VRAYCARPAINTMATERIAL_FLAKECOLORSHADER,
	VRAYCARPAINTMATERIAL_FLAKEGLOSSINESSSHADER,
	VRAYCARPAINTMATERIAL_FLAKEORIENTATIONSHADER,
	VRAYCARPAINTMATERIAL_COATCOLORSHADER,
    VRAYCARPAINTMATERIAL_COATSTRENGTHSHADER,
    VRAYCARPAINTMATERIAL_COATGLOSSINESSSHADER,
    VRAYCARPAINTMATERIAL_COATBUMPSHADER,
    VRAYCARPAINTMATERIAL_COATBUMPAMOUNTSHADER,
    VRAYCARPAINTMATERIAL_ENVOVERRIDESHADER,

	VRAYCARPAINTMATERIAL_USED = 5000,
	VRAYCARPAINTMATERIAL_XREF_FILENAME = 5001,
	VRAYCARPAINTMATERIAL_NODE = 5200,

	// virtual ID
	VRAYCARPAINTMATERIAL_SPECULARPREVIEW = 8050
};

#endif
