CONTAINER OMpNode
{
	NAME OMpNode;

	//INCLUDE Obaselist;
	
	GROUP OMpNode
	{
		//STRING MPNODE_BASELIST_NAME { ANIM OFF; MATEDNOTEXT; }
		//SEPARATOR { LINE; }

		LONG MPNODE_TYPE {MIN 0; HIDDEN;}
		
		BOOL MPNODE_ISENABLED { HIDDEN; }

		//POSITION PASS
		LONG VRAYRE_POSPASSSPACE
		{
			CYCLE
			{
				VRAYRE_POSPASSSPACE_0;
				VRAYRE_POSPASSSPACE_1;
				VRAYRE_POSPASSSPACE_2;
			}
		}

		//IDs
		LONG VRAYRE_OBJID { HIDDEN; MIN 0; }
		LONG VRAYRE_REDID {HIDDEN; MIN 0; }

		LONG VRAYRE_GREENID {HIDDEN; MIN 0; }

		LONG VRAYRE_BLUEID {HIDDEN; MIN 0; }

		BOOL VRAYRE_USEMATID {HIDDEN; MIN 0; }


		
		LONG VRAYRE_TEXALIGN {HIDDEN;}
		
		
		REAL VRAYRE_MAXVEL {MIN 0; HIDDEN;}
		REAL VRAYRE_MAXVELLAST {MIN 0; HIDDEN;}
		BOOL VRAYRE_CLAMPVEL {HIDDEN;}
		BOOL VRAYRE_IGNOREZ {HIDDEN;}


		
		REAL VRAYRE_DEPTHBLK {MIN 0; HIDDEN; }
		REAL VRAYRE_DEPTHWHT {MIN 0; HIDDEN;}
        BOOL VRAYRE_DEPTHINV { }
		BOOL VRAYRE_DEPTHFROMCAM {HIDDEN;}
		BOOL VRAYRE_DEPTHCLAMP {HIDDEN;}	

		LONG VRAYRE_ALIAS {MIN 0; HIDDEN;}

		
		BOOL VRAYRE_COLORMAPPING { HIDDEN;}
		BOOL VRAYRE_AA { HIDDEN;}


		
		BOOL VRAYRE_AFFECTMATTE {HIDDEN;}

		
		SHADERLINK VRAYRE_TEXMAP {HIDDEN;}
		
		
		////COMMON INTERFACE
		BOOL VRAYRE_FILTERING {HIDDEN;}
		
	}
}


