CONTAINER Oteaset
{
	NAME Oteaset;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL TEAPOTOBJECT_SIZE	{ UNIT METER; MIN 0.0; }
		LONG TEAPOTOBJECT_SUB	{ MIN 1; MAX 1000; }
		//BOOL TEAPOTOBJECT_BODY	{}
		//BOOL TEAPOTOBJECT_HANDLE{}	
		//BOOL TEAPOTOBJECT_SPOUT	{}	
		//BOOL TEAPOTOBJECT_LID	{}
		//BOOL TEAPOTOBJECT_STYLE	{}
	}

	INCLUDE Oprimitiveaxis;
}
