CONTAINER Ovrayproxy
{
	NAME Ovrayproxy;

	DEFAULT 1;
	GROUP
	{
		STRING VRAYPROXY_TITLEBAR		{ANIM OFF; CUSTOMGUI VRAYBAR_GUI;}
	}

	INCLUDE Obase;

	SEPARATOR {}

	GROUP ID_OBJECTPROPERTIES
	{
		//BOOL VRAYPROXY_ONLYFILE	{ }
		FILENAME	VRAYPROXY_FILE		{ }
		//LINK		VRAYPROXY_LINK	   	{ }
		//FILENAME	VRAYPROXY_FILE_TEMP {HIDDEN;}
		REAL VRAYPROXY_SCALE  { MIN 1; MAX 1000; UNIT PERCENT; }
	}
}


