#ifndef _OvrayproxyGen_H_
#define _OvrayproxyGen_H_

enum
{
	VRAYPROXYGEN_LINK	= 1500,
	VRAYPROXYGEN_OPTIMIZATION,
	VRAYPROXYGEN_DISTANCEOPT,
	VRAYPROXYGEN_ANGLEOPT,
	VRAYPROXYGEN_SINGLEBBOX,
	VRAYPROXYGEN_MESSAGE_TEXT,
	VRAYPROXYGEN_SKIPOBJ,
	VRAYPROXYGEN_CLONER,

	VRAYPROXYGEN_TITLEBAR = 1600
 };

#endif
