CONTAINER OVRayRenderSpline
{
	NAME OVRayRenderSpline;
	//INCLUDE Obase;
	INCLUDE Osplineprimitive;

	GROUP VRAYRENDERSPLINE_GROUP
	{
		REAL VRAYRENDERSPLINE_RADIUS			{ UNIT METER; MIN 0.0; STEP 0.01;}
		SPLINE VRAYRENDERSPLINE_SECTION	{ }
		REAL VRAYRENDERSPLINE_START			{MIN 0; STEP 0.01; MAXSLIDER 1; CUSTOMGUI REALSLIDER;}
		REAL VRAYRENDERSPLINE_END				{MIN 0; STEP 0.01; MAXSLIDER 1; CUSTOMGUI REALSLIDER;}

	}
}
					