CONTAINER OvrayproxyGen
{
	NAME OvrayproxyGen;

	DEFAULT 1;
	GROUP
	{
		STRING VRAYPROXYGEN_TITLEBAR		{ANIM OFF; CUSTOMGUI VRAYBAR_GUI;}
	}
	
	INCLUDE Obase;
	
	SEPARATOR {}
	
	GROUP ID_OBJECTPROPERTIES
	{
		LINK		VRAYPROXYGEN_LINK			{ }
		//STATICTEXT  VRAYPROXYGEN_MESSAGE_TEXT	{ }
		REAL		VRAYPROXYGEN_OPTIMIZATION	{UNIT PERCENT; MIN 0; MAX 100; STEP 0.1; CUSTOMGUI REALSLIDER;}
		SEPARATOR {}
		REAL		VRAYPROXYGEN_DISTANCEOPT	{ MIN 0.001; STEP 0.1; MAXSLIDER 5000; CUSTOMGUI REALSLIDER;}
		REAL		VRAYPROXYGEN_ANGLEOPT		{ MIN 0; MAX 360; STEP 0.1; UNIT DEGREE;}
		BOOL		VRAYPROXYGEN_SINGLEBBOX		{ }
		
		
	}
}


