CONTAINER tCustomData
{
	NAME tCustomData;
	INCLUDE Tbase;

	GROUP ID_TAGPROPERTIES
	{
		GROUP CDT_GROUP_OPTIONS {
			DEFAULT 0;
			LONG CDT_TYPE
			{
		 		CYCLE{   }
			}
			LONG CDT_ATTRIBUTE
			{
		 		CYCLE{  CDTA_0; CDTA_1; CDTA_2; CDTA_3; CDTA_4; }
			}
		}

		GROUP CDT_GROUP_VERTEX_MAP{
			DEFAULT 0;
			BUTTON CDT_CONVERT_TO_VMAP {}
			BUTTON CDT_CONVERT_FROM_VMAP {}
			SEPARATOR { LINE; }	
			BUTTON CDT_CONVERT_TO_NTAG {}
			//BUTTON CDT_CONVERT_FROM_NTAG{}
		}
		
		SEPARATOR { LINE; }	
		GROUP {
			BOOL  CDT_DRAW_ALWAYS {}
			COLUMNS 1;
			LONG CDT_COUNT { MIN 0; MAX 100000000; }
			SEPARATOR { LINE; }	//SEPARATOR {}
			LONG CDT_INDEX { MIN 0; }
			
			COLOR CDT_VALUE_COLOR {  }
			LONG CDT_VALUE_LONG {  }
			REAL CDT_VALUE_REAL {  }
			VECTOR CDT_VALUE_VECTOR {  }
			MATRIX CDT_VALUE_MATRIX {  }
			STRING CDT_VALUE_STRING {  }
			BOOL CDT_VALUE_BOOL {  }
			NORMAL CDT_VALUE_NORMAL {  }
		}



	}
}
