#ifndef _tVrayCompositingTag_H_
#define _tVrayCompositingTag_H_

//#define  tVrayLightTag	20000

enum
{
	VRAYCOMPOSITINGTAG_GROUPTAG	 = 1000,
	VRAYCOMPOSITINGTAG_GROUPOBJBUFFER	,
	VRAYCOMPOSITINGTAG_GROUPOBJPROP		,
	VRAYCOMPOSITINGTAG_GROUPMATTEPROP	,
	VRAYCOMPOSITINGTAG_GROUPMISCPROP	,

	VRAYCOMPOSITINGTAG_CAMERAVIS = 1100,
	VRAYCOMPOSITINGTAG_SHADOWVIS	,
	VRAYCOMPOSITINGTAG_GIVIS		,
	VRAYCOMPOSITINGTAG_REFLVIS		,
	VRAYCOMPOSITINGTAG_REFRVIS		,
	VRAYCOMPOSITINGTAG_OBJVIS		,

	VRAYCOMPOSITINGTAG_ENABLECHN0	,	
	VRAYCOMPOSITINGTAG_ENABLECHN1	,
	VRAYCOMPOSITINGTAG_ENABLECHN2	,
	VRAYCOMPOSITINGTAG_ENABLECHN3	,
	VRAYCOMPOSITINGTAG_ENABLECHN4	,
	VRAYCOMPOSITINGTAG_ENABLECHN5	,
	VRAYCOMPOSITINGTAG_ENABLECHN6	,
	VRAYCOMPOSITINGTAG_ENABLECHN7	,
	VRAYCOMPOSITINGTAG_ENABLECHN8	,
	VRAYCOMPOSITINGTAG_ENABLECHN9	,
	VRAYCOMPOSITINGTAG_IDCHN0		,
	VRAYCOMPOSITINGTAG_IDCHN1		,
	VRAYCOMPOSITINGTAG_IDCHN2		,
	VRAYCOMPOSITINGTAG_IDCHN3		,
	VRAYCOMPOSITINGTAG_IDCHN4		,
	VRAYCOMPOSITINGTAG_IDCHN5		,
	VRAYCOMPOSITINGTAG_IDCHN6		,
	VRAYCOMPOSITINGTAG_IDCHN7		,
	VRAYCOMPOSITINGTAG_IDCHN8		,
	VRAYCOMPOSITINGTAG_IDCHN9		,

	VRAYCOMPOSITINGTAG_GENGI				,
	VRAYCOMPOSITINGTAG_RECGI				,
	VRAYCOMPOSITINGTAG_GENCAUST				,
	VRAYCOMPOSITINGTAG_RECCAUST				,
	VRAYCOMPOSITINGTAG_MATTE				,
	VRAYCOMPOSITINGTAG_MATTEALPHACONTRIB	,
	VRAYCOMPOSITINGTAG_MATTESHADOWS			,
	VRAYCOMPOSITINGTAG_MATTESHADOWALPHA		,
	VRAYCOMPOSITINGTAG_MATTESHADOWCOLOR		,
	VRAYCOMPOSITINGTAG_MATTESHADOWBRIGHT	,
	VRAYCOMPOSITINGTAG_MATTEREFLAMOUNT		,
	VRAYCOMPOSITINGTAG_MATTEREFRAMOUNT		,
	VRAYCOMPOSITINGTAG_MATTEGIAMOUNT		,
	VRAYCOMPOSITINGTAG_MATTENOGI			,
	VRAYCOMPOSITINGTAG_GIID					,
	VRAYCOMPOSITINGTAG_MATTEGIMULTIPLIER	,
	VRAYCOMPOSITINGTAG_MATTESECONDARYRAYS,
	VRAYCOMPOSITINGTAG_OBJID,




	VRAYCOMPOSITINGTAG_TITLEBAR		= 1500,
};

#endif



