CONTAINER tVrayCompositingTag
{
	NAME tVrayCompositingTag;
	
	
	GROUP
	{
		STRING VRAYCOMPOSITINGTAG_TITLEBAR {ANIM OFF; CUSTOMGUI VRAYBAR_GUI;}
	}
	
	INCLUDE TBase;
	SEPARATOR {}
	
	GROUP VRAYCOMPOSITINGTAG_GROUPTAG
	{
		DEFAULT 1;
		
		BOOL VRAYCOMPOSITINGTAG_CAMERAVIS { }
		BOOL VRAYCOMPOSITINGTAG_SHADOWVIS { }
		BOOL VRAYCOMPOSITINGTAG_GIVIS { }
		BOOL VRAYCOMPOSITINGTAG_REFLVIS { }
		BOOL VRAYCOMPOSITINGTAG_REFRVIS { }
		REAL VRAYCOMPOSITINGTAG_OBJVIS {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
		LONG VRAYCOMPOSITINGTAG_OBJID {MIN 0;}
	}
	
	GROUP VRAYCOMPOSITINGTAG_GROUPOBJPROP
	{
		REAL VRAYCOMPOSITINGTAG_GENGI { MIN 0; MAXSLIDER 1; STEP 0.01; CUSTOMGUI REALSLIDER; }
		REAL VRAYCOMPOSITINGTAG_RECGI { MIN 0; MAXSLIDER 1; STEP 0.01; CUSTOMGUI REALSLIDER; }
		REAL VRAYCOMPOSITINGTAG_GENCAUST { MIN 0; MAXSLIDER 1; STEP 0.01; CUSTOMGUI REALSLIDER; }
		REAL VRAYCOMPOSITINGTAG_RECCAUST { MIN 0; MAXSLIDER 1; STEP 0.01; CUSTOMGUI REALSLIDER; }
	}
	
	GROUP VRAYCOMPOSITINGTAG_GROUPMATTEPROP
	{
		BOOL VRAYCOMPOSITINGTAG_MATTE { }
		REAL VRAYCOMPOSITINGTAG_MATTEALPHACONTRIB {MIN -1; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
		BOOL VRAYCOMPOSITINGTAG_MATTESHADOWS { }
		BOOL VRAYCOMPOSITINGTAG_MATTESHADOWALPHA { }
		COLOR VRAYCOMPOSITINGTAG_MATTESHADOWCOLOR { }
		REAL VRAYCOMPOSITINGTAG_MATTESHADOWBRIGHT {MIN 0; MAXSLIDER 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
		REAL VRAYCOMPOSITINGTAG_MATTEREFLAMOUNT {MIN 0; MAXSLIDER 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
		REAL VRAYCOMPOSITINGTAG_MATTEREFRAMOUNT {MIN 0; MAXSLIDER 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
		REAL VRAYCOMPOSITINGTAG_MATTEGIAMOUNT {MIN 0; MAXSLIDER 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
		BOOL VRAYCOMPOSITINGTAG_MATTESECONDARYRAYS {}
		BOOL VRAYCOMPOSITINGTAG_MATTENOGI { }
	}
	
	GROUP VRAYCOMPOSITINGTAG_GROUPMISCPROP
	{
		REAL VRAYCOMPOSITINGTAG_MATTEGIMULTIPLIER {MIN 0; MAXSLIDER 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
		LONG VRAYCOMPOSITINGTAG_GIID {MIN 0; MAX 10000;}
	}
		
	GROUP VRAYCOMPOSITINGTAG_GROUPOBJBUFFER
	{
		HIDDEN;
		COLUMNS 2;
		BOOL VRAYCOMPOSITINGTAG_ENABLECHN0		{ }
		LONG VRAYCOMPOSITINGTAG_IDCHN0				{ MIN 1; MAX 10000; }
		BOOL VRAYCOMPOSITINGTAG_ENABLECHN1		{ }
		LONG VRAYCOMPOSITINGTAG_IDCHN1				{ MIN 1; MAX 10000; }
		BOOL VRAYCOMPOSITINGTAG_ENABLECHN2		{ }
		LONG VRAYCOMPOSITINGTAG_IDCHN2				{ MIN 1; MAX 10000; }
		BOOL VRAYCOMPOSITINGTAG_ENABLECHN3		{ }
		LONG VRAYCOMPOSITINGTAG_IDCHN3				{ MIN 1; MAX 10000; }
		BOOL VRAYCOMPOSITINGTAG_ENABLECHN4		{ }
		LONG VRAYCOMPOSITINGTAG_IDCHN4				{ MIN 1; MAX 10000; }
		BOOL VRAYCOMPOSITINGTAG_ENABLECHN5		{ }
		LONG VRAYCOMPOSITINGTAG_IDCHN5				{ MIN 1; MAX 10000; }
		BOOL VRAYCOMPOSITINGTAG_ENABLECHN6		{ }
		LONG VRAYCOMPOSITINGTAG_IDCHN6				{ MIN 1; MAX 10000; }
		BOOL VRAYCOMPOSITINGTAG_ENABLECHN7		{ }
		LONG VRAYCOMPOSITINGTAG_IDCHN7				{ MIN 1; MAX 10000; }
		BOOL VRAYCOMPOSITINGTAG_ENABLECHN8		{ }
		LONG VRAYCOMPOSITINGTAG_IDCHN8				{ MIN 1; MAX 10000; }
		BOOL VRAYCOMPOSITINGTAG_ENABLECHN9		{ }
		LONG VRAYCOMPOSITINGTAG_IDCHN9				{ MIN 1; MAX 10000; }
	}
}