#ifndef _tVrayPhysicalCameraTag_H_
#define _tVrayPhysicalCameraTag_H_

#define  ID_VRAYPHYSICALCAMERATAG	1020898

enum
{
	VRAYPHYSICALCAMERATAG_CAMERALENS	= 500,
	VRAYPHYSICALCAMERATAG_BOKEH			= 501,
	VRAYPHYSICALCAMERATAG_SAMPLING		= 502,

	VRAYPHYSICALCAMERATAG_ON			= 1099,

	VRAYPHYSICALCAMERATAG_TYPE			= 1100,
	VRAYPHYSICALCAMERATAG_TYPE_0		= 0,
	VRAYPHYSICALCAMERATAG_TYPE_1		= 1,
	VRAYPHYSICALCAMERATAG_TYPE_2		= 2,

	VRAYPHYSICALCAMERATAG_FILMWIDTH		= 1000,
	VRAYPHYSICALCAMERATAG_FOCAL			= 1001,
	VRAYPHYSICALCAMERATAG_ZOOM			= 1002,
	VRAYPHYSICALCAMERATAG_DISTORTION	= 1003,
	VRAYPHYSICALCAMERATAG_DISTORTION_TYPE = 1031,
	VRAYPHYSICALCAMERATAG_DISTORTION_TYPE_0 = 0,
	VRAYPHYSICALCAMERATAG_DISTORTION_TYPE_1 = 1,
	VRAYPHYSICALCAMERATAG_DISTORTION_TYPE_2 = 2,
    VRAYPHYSICALCAMERATAG_DISTORTION_TYPE_3 = 3,
	VRAYPHYSICALCAMERATAG_LENSFILE		= 1032,
    VRAYPHYSICALCAMERATAG_LENSDISTTEX   = 1033,
	VRAYPHYSICALCAMERATAG_FSTOP			= 1004,
	VRAYPHYSICALCAMERATAG_LSHIFT		= 1009,
	VRAYPHYSICALCAMERATAG_HSHIFT		= 1030,
	VRAYPHYSICALCAMERATAG_SHUTTERSPEED	= 1005,
	VRAYPHYSICALCAMERATAG_SHUTTERANGLE 	= 1006,
	VRAYPHYSICALCAMERATAG_SHUTTEROFFSET	= 1007,
	VRAYPHYSICALCAMERATAG_LATENCY		= 1008,
	VRAYPHYSICALCAMERATAG_ISO			= 1010,

	VRAYPHYSICALCAMERATAG_DOFON 		= 1011,
	VRAYPHYSICALCAMERATAG_DOFTHRESHOLD	= 1012,
	VRAYPHYSICALCAMERATAG_MBLURON 		= 1013,
	VRAYPHYSICALCAMERATAG_SUBDIVS 		= 1014,
	VRAYPHYSICALCAMERATAG_EXPOSURE		= 1015,
	VRAYPHYSICALCAMERATAG_VIGNETTING 	= 1016,
	VRAYPHYSICALCAMERATAG_WHITEBALANCE	= 1017,
	VRAYPHYSICALCAMERATAG_BLADES 		= 1018,
	VRAYPHYSICALCAMERATAG_BLADESNUM		= 1019,
	VRAYPHYSICALCAMERATAG_BLADESROT		= 1020,
	VRAYPHYSICALCAMERATAG_CENTERBIAS	= 1021,
	VRAYPHYSICALCAMERATAG_ANISOTROPY	= 1022,
	VRAYPHYSICALCAMERATAG_TITLEBAR		= 1500,
	VRAYPHYSICALCAMERATAG_FIXED_EXPOSURE= 1023,
	VRAYPHYSICALCAMERATAG_WB_PRESETS	= 1024,
	VRAYPHYSICALCAMERATAG_WB_PRESETS_0	= 0,
	VRAYPHYSICALCAMERATAG_WB_PRESETS_1	= 1,
	VRAYPHYSICALCAMERATAG_WB_PRESETS_2	= 2,
	VRAYPHYSICALCAMERATAG_WB_PRESETS_3	= 3,
	VRAYPHYSICALCAMERATAG_WB_PRESETS_4	= 4,
	VRAYPHYSICALCAMERATAG_WB_PRESETS_5	= 5,
	VRAYPHYSICALCAMERATAG_WB_PRESETS_6	= 6,

	VRAYPHYSICALCAMERATAG_EVSTOPS		= 1025,
	VRAYPHYSICALCAMERATAG_EVSTOPS2		= 1026,
	VRAYPHYSICALCAMERATAG_EVSTOPS3		= 1027,
	VRAYPHYSICALCAMERATAG_SHUTTERPRIORITY = 1028,

};	
	 
#endif



