#ifndef _tVraySelectionTag_H_
#define _tVraySelectionTag_H_

//#define  tVrayLightTag	20000

enum
{
	VRAYSELECTIONTAG_GROUPTAG						= 800,
	
	VRAYSELECTIONTAG_SORTMODE						= 1100,
			VRAYSELECTIONTAG_MODE_RANDOM			= 0,
			VRAYSELECTIONTAG_MODE_BOUND				= 1,
			VRAYSELECTIONTAG_MODE_NATURAL			= 2,
			VRAYSELECTIONTAG_MODE_CYCLIC				= 3,
			
	VRAYSELECTIONTAG_SEED							= 1101,						
	VRAYSELECTIONTAG_FACEID_MIN						,
	VRAYSELECTIONTAG_FACEID_MAX						,
	
	VRAYSELECTIONTAG_SKIPEVERY						,

	VRAYSELECTIONTAG_EXPORT_MODE 				,
   		VRAYSELECTIONTAG_FACEID_MODE			=0,
        VRAYSELECTIONTAG_OBJECTID_MODE		=1,
				
			
	VRAYSELECTIONTAG_TITLEBAR						= 1500,
};

#endif



