CONTAINER tVrayDispTag
{
	NAME tVrayDispTag;

	
	DEFAULT 1;
	GROUP
	{
		STRING VRAYDISPTAG_TITLEBAR {ANIM OFF; CUSTOMGUI VRAYBAR_GUI;}
	}

	INCLUDE TBase;
	GROUP 	VRAYDISPTAG_GLOBALS
	{			
		DEFAULT 1;
		BOOL VRAYDISPTAG_ON {}
		BOOL VRAYDISPTAG_USEGLOBALS {}
		
		SEPARATOR {}
		
		GROUP
		{
			BOOL VRAYDISPTAG_VIEWDEP {}
			REAL VRAYDISPTAG_EDGELENGTH {MIN 0; STEP 0.1;}
			LONG VRAYDISPTAG_MAXSUBDIV {MIN 2;}
		}
	}
		
	GROUP VRAYDISPTAG_COLOR
	{
		SHADERLINK VRAYDISPTAG_TEXTURE {}
		
		SEPARATOR {}
		
		GROUP
		{
			REAL VRAYDISPTAG_AMOUNT {UNIT METER; STEP 0.01;}
			REAL VRAYDISPTAG_SHIFT { UNIT METER; STEP 0.01;}
			BOOL VRAYDISPTAG_KEEP {}
		}
	}

}
