#ifndef _tVrayFurTag_H_
#define _tVrayFurTag_H_

//#define  tVrayLightTag	20000

enum
{
	VRAYFURTAG_GROUPFUR				= 1100,
	VRAYFURTAG_GROUPBASIC			,
	VRAYFURTAG_GROUPDETAIL			,
	VRAYFURTAG_GROUPVARIATIONS		,
	VRAYFURTAG_GROUPDISTRIBUTION	,


	VRAYFURTAG_LENGTH		= 1150,
	VRAYFURTAG_THICKNESS	,
	VRAYFURTAG_GRAVITY		,
	VRAYFURTAG_BEND			,
	VRAYFURTAG_TAPER		,
	VRAYFURTAG_GRAVITYDIR	,

	VRAYFURTAG_SIDES		= 1200,
	VRAYFURTAG_KNOTS		,
	VRAYFURTAG_FLATNORMALS	,

	VRAYFURTAG_DIRVAR		= 1250,
	VRAYFURTAG_LENGTHVAR	,
	VRAYFURTAG_THICKNESSVAR	,
	VRAYFURTAG_GRAVITYVAR	,

	VRAYFURTAG_DISTRTYPE	= 1300,
	VRAYFURTAG_DISTRTYPE_0	= 0,
	VRAYFURTAG_DISTRTYPE_1	= 1,
	VRAYFURTAG_FACENUM		= 1310,
	VRAYFURTAG_AREANUM		,

	VRAYFURTAG_LENGTH_TEX		= 1400,
	VRAYFURTAG_THICKNESS_TEX	,
	VRAYFURTAG_GRAVITY_TEX		,
	VRAYFURTAG_BEND_TEX			,
	VRAYFURTAG_BENDDIR_TEX		,
	VRAYFURTAG_INITDIR_TEX		,
	VRAYFURTAG_DENSITY_TEX		,

	VRAYFURTAG_TITLEBAR		= 1500,
};

#endif



