CONTAINER tVRaySelectionTag
{
	NAME tVRaySelectionTag;
	
	GROUP
	{
		STRING VRAYSELECTIONTAG_TITLEBAR {ANIM OFF; CUSTOMGUI VRAYBAR_GUI;}
	}
	
	INCLUDE TBase;
	
	GROUP ID_TAGPROPERTIES//VRAYSELECTIONTAG_GROUPTAG
	{
		DEFAULT 1;
		
		LONG VRAYSELECTIONTAG_SORTMODE
		{
			CYCLE
			{
				VRAYSELECTIONTAG_MODE_RANDOM;
				//VRAYSELECTIONTAG_MODE_BOUND;
				VRAYSELECTIONTAG_MODE_NATURAL;
				VRAYSELECTIONTAG_MODE_CYCLIC;
			}
		}
		SEPARATOR {}
		LONG	VRAYSELECTIONTAG_SEED 				{}											
		LONG	VRAYSELECTIONTAG_FACEID_MIN 		{}							
        LONG	VRAYSELECTIONTAG_FACEID_MAX 		{}							
        
        LONG	VRAYSELECTIONTAG_SKIPEVERY	 		{MIN 1;}							
		
        LONG VRAYSELECTIONTAG_EXPORT_MODE  			 		
		{
			CYCLE
			{			
        		VRAYSELECTIONTAG_FACEID_MODE ;	
        		VRAYSELECTIONTAG_OBJECTID_MODE ;	
			}
		}
			
	}
}