CONTAINER tVrayPhysicalCameraTag
{
	NAME tVrayPhysicalCameraTag;

		DEFAULT 1;
		GROUP
		{
			STRING VRAYPHYSICALCAMERATAG_TITLEBAR {ANIM OFF; CUSTOMGUI VRAYBAR_GUI;}
		}

		INCLUDE TBase;


		GROUP VRAYPHYSICALCAMERATAG_CAMERALENS
		{
			DEFAULT 1;

			BOOL VRAYPHYSICALCAMERATAG_ON {}

			SEPARATOR {LINE;}

			LONG VRAYPHYSICALCAMERATAG_TYPE
			{
				CYCLE
				{
					VRAYPHYSICALCAMERATAG_TYPE_0;
					VRAYPHYSICALCAMERATAG_TYPE_1;
					VRAYPHYSICALCAMERATAG_TYPE_2;
				}
			}

			SEPARATOR {LINE;}

			//REAL VRAYPHYSICALCAMERATAG_FILMWIDTH {MIN 0; STEP 0.1; CUSTOMGUI REALSLIDER;}
			//REAL VRAYPHYSICALCAMERATAG_FOCAL {MIN 0; STEP 0.1; CUSTOMGUI REALSLIDER;}

			REAL VRAYPHYSICALCAMERATAG_ZOOM {MIN 0; MAX 12; STEP 0.1; CUSTOMGUI REALSLIDER;}
			
			SEPARATOR {}

			LONG VRAYPHYSICALCAMERATAG_DISTORTION_TYPE
			{
				CYCLE
				{
					VRAYPHYSICALCAMERATAG_DISTORTION_TYPE_0;
					VRAYPHYSICALCAMERATAG_DISTORTION_TYPE_1;
					VRAYPHYSICALCAMERATAG_DISTORTION_TYPE_2;
					VRAYPHYSICALCAMERATAG_DISTORTION_TYPE_3;
				}
			}
			
			SEPARATOR {}
			
			REAL VRAYPHYSICALCAMERATAG_DISTORTION {MINSLIDER -20; MAXSLIDER 20; STEP 0.1; CUSTOMGUI REALSLIDER;}
			FILENAME VRAYPHYSICALCAMERATAG_LENSFILE {}
			TEXTURE VRAYPHYSICALCAMERATAG_LENSDISTTEX {}
			
			SEPARATOR {}
			
			REAL VRAYPHYSICALCAMERATAG_LSHIFT {MINSLIDER -1; MAXSLIDER 1;STEP 0.01; CUSTOMGUI REALSLIDER;}
			REAL VRAYPHYSICALCAMERATAG_HSHIFT {MINSLIDER -1; MAXSLIDER 1;STEP 0.01; CUSTOMGUI REALSLIDER;}
			
			SEPARATOR {}
			
			REAL VRAYPHYSICALCAMERATAG_VIGNETTING {MIN 0; MAX 10;STEP 0.01; CUSTOMGUI REALSLIDER;}
			
			SEPARATOR {LINE;}
			
			LONG VRAYPHYSICALCAMERATAG_WB_PRESETS
			{
				CYCLE
				{
					VRAYPHYSICALCAMERATAG_WB_PRESETS_0;
					VRAYPHYSICALCAMERATAG_WB_PRESETS_1;
					VRAYPHYSICALCAMERATAG_WB_PRESETS_2;
					VRAYPHYSICALCAMERATAG_WB_PRESETS_3;
					VRAYPHYSICALCAMERATAG_WB_PRESETS_4;
					VRAYPHYSICALCAMERATAG_WB_PRESETS_5;
					VRAYPHYSICALCAMERATAG_WB_PRESETS_6;
				}
			}
			
			SEPARATOR {}
			
			COLOR VRAYPHYSICALCAMERATAG_WHITEBALANCE {OPEN;}
			
			SEPARATOR {LINE;}
			
			BOOL VRAYPHYSICALCAMERATAG_EXPOSURE {}
			BOOL VRAYPHYSICALCAMERATAG_FIXED_EXPOSURE {}
			BOOL VRAYPHYSICALCAMERATAG_SHUTTERPRIORITY {}

			SEPARATOR {}
			
			LONG VRAYPHYSICALCAMERATAG_EVSTOPS3 {MIN 1; MAX 11; CUSTOMGUI LONGSLIDER;}
			REAL VRAYPHYSICALCAMERATAG_ISO {MIN 50; MAXSLIDER 102400; STEP 0.1; CUSTOMGUI REALSLIDER;}
			SEPARATOR {}
			LONG VRAYPHYSICALCAMERATAG_EVSTOPS {MIN 0; MAX 27; CUSTOMGUI LONGSLIDER;}
			REAL VRAYPHYSICALCAMERATAG_FSTOP {MIN 0.01; MAX 44; STEP 0.01; CUSTOMGUI REALSLIDER;}
			SEPARATOR {}
			LONG VRAYPHYSICALCAMERATAG_EVSTOPS2 {MIN 1; MAX 40; CUSTOMGUI LONGSLIDER;}
			REAL VRAYPHYSICALCAMERATAG_SHUTTERSPEED {MIN 0.01; MAX 8192; MAXSLIDER 8000; STEP 0.1; CUSTOMGUI REALSLIDER;}
			SEPARATOR {}
			REAL VRAYPHYSICALCAMERATAG_SHUTTERANGLE {UNIT DEGREE; MIN 0; MAX 360; STEP 0.1; CUSTOMGUI REALSLIDER;}
			REAL VRAYPHYSICALCAMERATAG_SHUTTEROFFSET {UNIT DEGREE; MIN -360; MAX 0; STEP 0.1; CUSTOMGUI REALSLIDER;}
			REAL VRAYPHYSICALCAMERATAG_LATENCY {MIN 0; MAX 1; MAXSLIDER 0.1; STEP 0.01; CUSTOMGUI REALSLIDER;}
		}

		GROUP VRAYPHYSICALCAMERATAG_SAMPLING
		{
			//DEFAULT 1;

			BOOL VRAYPHYSICALCAMERATAG_MBLURON {}

			//SEPARATOR {}

			BOOL VRAYPHYSICALCAMERATAG_DOFON {}
			//REAL VRAYPHYSICALCAMERATAG_DOFTHRESHOLD {MIN 0.001; MAX 1; STEP 0.001; CUSTOMGUI REALSLIDER;}

			//SEPARATOR {}

			LONG VRAYPHYSICALCAMERATAG_SUBDIVS {MIN 1; MAX 256;}

			SEPARATOR {}

			BOOL VRAYPHYSICALCAMERATAG_BLADES {}
			LONG VRAYPHYSICALCAMERATAG_BLADESNUM {MIN 0;}
			REAL VRAYPHYSICALCAMERATAG_BLADESROT {MIN 0; MAX 360; STEP 0.1; CUSTOMGUI REALSLIDER;}
			REAL VRAYPHYSICALCAMERATAG_CENTERBIAS {MIN 0; MAX 1; STEP 0.1; CUSTOMGUI REALSLIDER;}
			REAL VRAYPHYSICALCAMERATAG_ANISOTROPY {MIN -1; MAX 1; STEP 0.1; CUSTOMGUI REALSLIDER;}




		}

}
