CONTAINER tVrayCameraDomeTag
{
	NAME tVrayCameraDomeTag;

		
		GROUP
		{
			STRING VRAYCAMERADOME_TITLEBAR {ANIM OFF; CUSTOMGUI VRAYBAR_GUI;}
		}
		
		INCLUDE TBase;
		SEPARATOR {}

		GROUP VRAYCAMERADOME_PROPERTIES
		{
			DEFAULT 1;
			
			REAL VRAYCAMERADOME_FOV {MIN 0; MAX 360; UNIT DEGREE; CUSTOMGUI REALSLIDER;}
			
			SEPARATOR {}
			
			BOOL VRAYCAMERADOME_FLIPX {}
			BOOL VRAYCAMERADOME_FLIPY {}
		}
	
}
