CONTAINER tVrayMblurTag
{
	NAME tVrayMblurTag;
	
	
	GROUP
	{
		STRING VRAYMBLURTAG_TITLEBAR {ANIM OFF; CUSTOMGUI VRAYBAR_GUI;}
	}
	
	INCLUDE TBase;
	
	SEPARATOR {}
	
	GROUP VRAYMBLURTAG_PARAMS
	{
		DEFAULT 1;
		BOOL VRAYMBLURTAG_DEFORMATION { }
		LONG VRAYMBLURTAG_NSAMPLES { MIN 2; MAX 512;}
	}
}