CONTAINER tVrayLightTag
{
	NAME tVrayLightTag;

		FILENAME IESCURRENTPATH {HIDDEN;}
		FILENAME IESCURRENTFILE {HIDDEN;}

		
		GROUP
		{
			STRING VRAYLIGHTTAG_TITLEBAR {ANIM OFF; CUSTOMGUI VRAYBAR_GUI;}
		}

		INCLUDE TBase;

		GROUP VRAYLIGHTTAG_COMMON
		{
			DEFAULT 1;
			
			LONG VRAYLIGHTTAG_COMMON_LIGHTTYPE
			{
				CYCLE
				{
					VRAYLIGHTTAG_COMMON_LIGHTTYPE_0;
					VRAYLIGHTTAG_COMMON_LIGHTTYPE_1;
					VRAYLIGHTTAG_COMMON_LIGHTTYPE_2;
					VRAYLIGHTTAG_COMMON_LIGHTTYPE_3;
					VRAYLIGHTTAG_COMMON_LIGHTTYPE_4;
					VRAYLIGHTTAG_COMMON_LIGHTTYPE_5;
				}
			}

			SEPARATOR {LINE;}

			LONG VRAYLIGHTTAG_COMMON_UNITS
			{
				CYCLE
				{
					VRAYLIGHTTAG_COMMON_UNITS_0;
					VRAYLIGHTTAG_COMMON_UNITS_1;
					VRAYLIGHTTAG_COMMON_UNITS_2;
					VRAYLIGHTTAG_COMMON_UNITS_3;
					VRAYLIGHTTAG_COMMON_UNITS_4;
				}
			}

			REAL VRAYLIGHTTAG_COMMON_DIMMER {MIN 0; HIDDEN;}
			REAL VRAYLIGHTTAG_COMMON_INTENSITY {MIN 0; STEP 0.1; MAXSLIDER 100; CUSTOMGUI REALSLIDER;}
			REAL VRAYLIGHTTAG_COMMON_INTENSITY2 {MIN 0; STEP 0.1; MAXSLIDER 1000; CUSTOMGUI REALSLIDER; HIDDEN;}
			REAL VRAYLIGHTTAG_COMMON_INTENSITY3 {MIN 0; STEP 0.1; MAXSLIDER 1000; CUSTOMGUI REALSLIDER; HIDDEN;}
			REAL VRAYLIGHTTAG_COMMON_INTENSITY4 {MIN 0; STEP 0.1; MAXSLIDER 100; CUSTOMGUI REALSLIDER; HIDDEN;}
			REAL VRAYLIGHTTAG_COMMON_INTENSITY5 {MIN 0; STEP 0.1; MAXSLIDER 100; CUSTOMGUI REALSLIDER; HIDDEN;}
 			SHADERLINK VRAYLIGHTTAG_COMMON_INTENSITYTEX {}

			SEPARATOR {}

			REAL VRAYLIGHTTAG_COMMON_CUTOFF {MIN 0; STEP 0.001;}

			SEPARATOR {LINE;}

			LONG VRAYLIGHTTAG_COLOR_PRESETS
			{
				CYCLE
				{
					VRAYLIGHTTAG_COLOR_PRESETS_0;
					VRAYLIGHTTAG_COLOR_PRESETS_1;
					VRAYLIGHTTAG_COLOR_PRESETS_2;
					VRAYLIGHTTAG_COLOR_PRESETS_3;
					VRAYLIGHTTAG_COLOR_PRESETS_4;
					VRAYLIGHTTAG_COLOR_PRESETS_5;
					VRAYLIGHTTAG_COLOR_PRESETS_6;
					VRAYLIGHTTAG_COLOR_PRESETS_7;
					VRAYLIGHTTAG_COLOR_PRESETS_8;
					VRAYLIGHTTAG_COLOR_PRESETS_9;
					VRAYLIGHTTAG_COLOR_PRESETS_10;
					VRAYLIGHTTAG_COLOR_PRESETS_11;
					VRAYLIGHTTAG_COLOR_PRESETS_12;
					VRAYLIGHTTAG_COLOR_PRESETS_13;
					VRAYLIGHTTAG_COLOR_PRESETS_14;
				}
			}

			SEPARATOR {}

			COLOR VRAYLIGHTTAG_COMMON_COLOR     {}
			SHADERLINK VRAYLIGHTTAG_COMMON_COLORTEX {}

			SEPARATOR {LINE;}

			BOOL VRAYLIGHTTAG_COMMON_AFFECTDIFF {}
			REAL VRAYLIGHTTAG_COMMON_DIFFCONTR {MIN 0; STEP 0.01;}
			SEPARATOR {}
			BOOL VRAYLIGHTTAG_COMMON_AFFECTSPEC {}
			REAL VRAYLIGHTTAG_COMMON_SPECCONTR {MIN 0; STEP 0.01;}
			SEPARATOR {}
			BOOL VRAYLIGHTTAG_COMMON_AREASPEC {}

			SEPARATOR {LINE;}

			BOOL VRAYLIGHTTAG_COMMON_SHDON	{}
			COLOR VRAYLIGHTTAG_COMMON_SHDCOLOR {}
			SHADERLINK VRAYLIGHTTAG_COMMON_SHDCOLORTEX {}
			REAL VRAYLIGHTTAG_COMMON_SHDBIAS {UNIT METER; MIN 0; STEP 0.01; HIDDEN;}
			REAL VRAYLIGHTTAG_COMMON_SUNSHDBIAS {UNIT METER; MIN 0; STEP 0.01; HIDDEN;}
			REAL VRAYLIGHTTAG_COMMON_SHDRADIUS {UNIT METER; MIN 0; STEP 0.01;}
			LONG VRAYLIGHTTAG_COMMON_SHDSUBDIVS {MIN 0;}
			SEPARATOR {LINE;}
			LONG VRAYLIGHTTAG_COMMON_SHDPHOTON {MIN 0;}
			LONG VRAYLIGHTTAG_COMMON_SHDCAUSTIC {MIN 0;}

			SEPARATOR {LINE;}

			REAL VRAYLIGHTTAG_COMMON_BEAMRADIUS {UNIT METER; MIN 0; STEP 0.01;}

			SEPARATOR {LINE;}

			LONG VRAYLIGHTTAG_COMMON_DECAY
			{
				CYCLE
				{
					VRAYLIGHTTAG_COMMON_DECAY_0;
					VRAYLIGHTTAG_COMMON_DECAY_1;
					VRAYLIGHTTAG_COMMON_DECAY_2;
				}
			}

			BOOL VRAYLIGHTTAG_COMMON_NEWTAG {HIDDEN;}

		}

		GROUP VRAYLIGHTTAG_SPOT
		{
			//DEFAULT 1;
			
			REAL VRAYLIGHTTAG_SPOT_CONEANGLE {UNIT DEGREE; MIN 0; MAX 360; STEP 1;}
			REAL VRAYLIGHTTAG_SPOT_PENANGLE {UNIT DEGREE; MIN 0; MAX 360; STEP 1;}

			SEPARATOR {}

			BOOL VRAYLIGHTTAG_SPOT_BARNDOOR { }
			REAL VRAYLIGHTTAG_SPOT_BARNDOOR_LEFT {UNIT DEGREE; MIN 0; MAX 90; STEP 0.1; CUSTOMGUI REALSLIDER;}
			REAL VRAYLIGHTTAG_SPOT_BARNDOOR_RIGHT {UNIT DEGREE; MIN 0; MAX 90; STEP 0.1; CUSTOMGUI REALSLIDER;}
			REAL VRAYLIGHTTAG_SPOT_BARNDOOR_TOP {UNIT DEGREE; MIN 0; MAX 90; STEP 0.1; CUSTOMGUI REALSLIDER;}
			REAL VRAYLIGHTTAG_SPOT_BARNDOOR_BOTTOM {UNIT DEGREE; MIN 0; MAX 90; STEP 0.1; CUSTOMGUI REALSLIDER;}
		}

		GROUP VRAYLIGHTTAG_AREA
		{
			//DEFAULT 1;

			LONG VRAYLIGHTTAG_AREA_TYPE
			{
				CYCLE
				{
					VRAYLIGHTTAG_AREA_TYPE_0;
					VRAYLIGHTTAG_AREA_TYPE_1;
					VRAYLIGHTTAG_AREA_TYPE_2;
					VRAYLIGHTTAG_AREA_TYPE_3;
				}
			}

			SEPARATOR {LINE;}

			REAL VRAYLIGHTTAG_AREA_SIZEX {HIDDEN; UNIT METER; MIN 0; STEP 0.1;}
			REAL VRAYLIGHTTAG_AREA_SIZEY {HIDDEN; UNIT METER; MIN 0; STEP 0.1;}
			REAL VRAYLIGHTTAG_AREA_RADIUS {HIDDEN;UNIT METER; MIN 0; STEP 0.1;}

			SEPARATOR {LINE;}

			BOOL VRAYLIGHTTAG_AREA_AFFECTREFL {}
			BOOL VRAYLIGHTTAG_AREA_INVISIBLE {}
			LONG VRAYLIGHTTAG_AREA_SUBDIVS {MIN 0;}
			BOOL VRAYLIGHTTAG_AREA_NODECAY {}
			BOOL VRAYLIGHTTAG_AREA_STORE {}
			BOOL VRAYLIGHTTAG_AREA_DOUBLE {}
			LONG VRAYLIGHTTAG_AREA_PORTAL
			{
				CYCLE
				{
					VRAYLIGHTTAG_AREA_PORTAL_0;
					VRAYLIGHTTAG_AREA_PORTAL_1;
					VRAYLIGHTTAG_AREA_PORTAL_2;
				}
			}
			BOOL VRAYLIGHTTAG_AREA_NONORMALS {}

			SEPARATOR {LINE;}

			GROUP VRAYLIGHTTAG_AREA_RECTANGLE
			{
				DEFAULT 1; HIDDEN;
				
				REAL VRAYLIGHTTAG_AREA_RECT_DIRECTIONAL { MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER; }
				BOOL VRAYLIGHTTAG_AREA_RECT_USETEX {}
				SHADERLINK VRAYLIGHTTAG_AREA_RECT_TEX {}
				LONG VRAYLIGHTTAG_AREA_RECT_TEXRES {MIN 1;}
				REAL VRAYLIGHTTAG_AREA_RECT_TEXADAPTIVE {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
			}

			GROUP VRAYLIGHTTAG_AREA_DOME
			{
				DEFAULT 1; HIDDEN;

				BOOL VRAYLIGHTTAG_AREA_DOME_SPHERE {}
				SEPARATOR {}
				BOOL VRAYLIGHTTAG_AREA_DOME_USETEX {}
				SHADERLINK VRAYLIGHTTAG_AREA_DOME_TEX {}
				LONG VRAYLIGHTTAG_AREA_DOME_MAPTYPE
				{
					CYCLE
					{
						VRAYLIGHTTAG_AREA_DOME_MAPTYPE_0;
						VRAYLIGHTTAG_AREA_DOME_MAPTYPE_1;
						VRAYLIGHTTAG_AREA_DOME_MAPTYPE_2;
						VRAYLIGHTTAG_AREA_DOME_MAPTYPE_3;
						VRAYLIGHTTAG_AREA_DOME_MAPTYPE_4;
					}
				}
				LONG VRAYLIGHTTAG_AREA_DOME_TEXRES {MIN 1;}
				SEPARATOR {}
				REAL VRAYLIGHTTAG_AREA_DOME_TARGETRADIUS {UNIT METER; MIN 0; STEP 0.1;}
				REAL VRAYLIGHTTAG_AREA_DOME_EMITRADIUS {UNIT METER; MIN 0; STEP 0.1;}
				SEPARATOR {}
			}
			
			GROUP VRAYLIGHTTAG_AREA_MESH
			{
				DEFAULT 1; HIDDEN;

				LINK VRAYLIGHTTAG_AREA_MESH_GEOMETRY {}
				SEPARATOR {}
				BOOL VRAYLIGHTTAG_AREA_MESH_USETEX {}
				SHADERLINK VRAYLIGHTTAG_AREA_MESH_TEX {}
				LONG VRAYLIGHTTAG_AREA_MESH_TEXRES {MIN 1;}			
				SEPARATOR {}
			}
		}

		GROUP VRAYLIGHTTAG_SUN
		{
			//DEFAULT 1;

			GROUP
			{
				BOOL VRAYLIGHTTAG_SUN_ON {}
				BOOL VRAYLIGHTTAG_SUN_INVISIBLE {}
				BOOL VRAYLIGHTTAG_SUN_ATMOSHADOWS {}
			}
			
			SEPARATOR {LINE;}

			GROUP
			{
				//LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					BOOL VRAYLIGHTTAG_SUN_SKY {}
					BOOL VRAYLIGHTTAG_SUN_SKYONLY {}
					LONG VRAYLIGHTTAG_SUN_SKYMODELS
					{
						CYCLE
						{
							VRAYLIGHTTAG_SUN_SKYMODELS_0;
							VRAYLIGHTTAG_SUN_SKYMODELS_1;
							VRAYLIGHTTAG_SUN_SKYMODELS_2;
						}
					}
					REAL VRAYLIGHTTAG_SUN_SKYMULT {MIN 0; UNIT PERCENT; MAXSLIDER 100; CUSTOMGUI REALSLIDER;}
				}	
				SEPARATOR {LINE;} 
				GROUP
				{
					COLUMNS 2;
					//STATICTEXT { JOINEND; } //SEPARATOR {}
					BOOL VRAYLIGHTTAG_SUN_SKYBG {}
					BOOL VRAYLIGHTTAG_SUN_SKYGI {}
					BOOL VRAYLIGHTTAG_SUN_SKYREFL {}
					BOOL VRAYLIGHTTAG_SUN_SKYREFR {}
				}
			}
			
			SEPARATOR {LINE;}
			REAL VRAYLIGHTTAG_SUN_TURB {MIN 0; STEP 0.01;}
			REAL VRAYLIGHTTAG_SUN_OZONE {MIN 0; STEP 0.01;}
			REAL VRAYLIGHTTAG_SUN_WATER {MIN 0; STEP 0.01;}
			REAL VRAYLIGHTTAG_SUN_SIZEMUL {MIN 0; STEP 0.1;}
			COLOR VRAYLIGHTTAG_SUN_FILTERCLR {}
			//SEPARATOR {LINE;}
			REAL VRAYLIGHTTAG_SUN_PHOTONRAD {UNIT METER; MIN 0; STEP 0.1;}
			//REAL VRAYLIGHTTAG_SUN_PHOTONDIST {UNIT METER; MIN 0; STEP 0.1;}
			SEPARATOR {LINE;}
			REAL VRAYLIGHTTAG_SUN_HORIZILLUM_PHYCAM {MIN 0; STEP 100; MAXSLIDER 50000; CUSTOMGUI REALSLIDER;}
			REAL VRAYLIGHTTAG_SUN_HORIZILLUM_STDCAM {MIN 0; STEP 1; MAXSLIDER 1000; CUSTOMGUI REALSLIDER;}
			REAL VRAYLIGHTTAG_SUN_PHYINTMUL {MIN 0; STEP 0.1; UNIT PERCENT; MAXSLIDER 100;  CUSTOMGUI REALSLIDER;}
			REAL VRAYLIGHTTAG_SUN_STDINTMUL {MIN 0; STEP 0.1; UNIT PERCENT; MAXSLIDER 100;  CUSTOMGUI REALSLIDER;}

			SEPARATOR {LINE;}
			GROUP VRAYLIGHTTAG_SUN_COLOR_CORRECT
			{
				DEFAULT 1;
				BOOL VRAYLIGHTTAG_SUN_MONO {}
				REAL VRAYLIGHTTAG_SUN_GAMMA {MIN 0; MAXSLIDER 2.2; STEP 0.01; CUSTOMGUI REALSLIDER;}
				REAL VRAYLIGHTTAG_SUN_CONTRAST {MIN 0; MAXSLIDER 3; STEP 0.01; CUSTOMGUI REALSLIDER;}
				REAL VRAYLIGHTTAG_SUN_HUE_OFFSET {MIN -360; MAX 360; STEP 0.1; CUSTOMGUI REALSLIDER;}
				REAL VRAYLIGHTTAG_SUN_HUE_GAIN {MIN -360; MAX 360; STEP 0.1; CUSTOMGUI REALSLIDER;}		
				REAL VRAYLIGHTTAG_SUN_SATURATION_OFFSET {MINSLIDER -1; MAXSLIDER 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
				REAL VRAYLIGHTTAG_SUN_SATURATION_GAIN {MINSLIDER -5; MAXSLIDER 5; STEP 0.01; CUSTOMGUI REALSLIDER;}
				REAL VRAYLIGHTTAG_SUN_BRIGHTNESS_OFFSET {MIN -360; MAX 360; MINSLIDER -100; MAXSLIDER 100; STEP 0.1; CUSTOMGUI REALSLIDER;}
				REAL VRAYLIGHTTAG_SUN_BRIGHTNESS_GAIN {MIN 0; MAXSLIDER 2; STEP 0.01; CUSTOMGUI REALSLIDER;}
			}
		}

		GROUP VRAYLIGHTTAG_IES
		{
			BOOL VRAYLIGHTTAG_IES_ON          {}

			SEPARATOR {}

			FILENAME VRAYLIGHTTAG_IES_FILE    {}
			REAL VRAYLIGHTTAG_IES_FILTER_MULT { MIN 0.0; STEP 0.1;}

			SEPARATOR {}

			COLOR VRAYLIGHTTAG_IES_FILTER     {}

			SEPARATOR {}

			BOOL VRAYLIGHTTAG_IES_SOFTSHADOWS {}

			SEPARATOR {}

			GROUP VRAYLIGHTTAG_IESPREVIEW	{
				DEFAULT 1; HIDDEN;
				REAL IES_PREVIEW_DISTANCE	{UNIT METER; MIN -500.0; MAX 500.0; STEP 1.0; MINSLIDER -100; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER;}
				REAL IES_LIGHT_HEIGHT	{UNIT METER; MIN 0.0; MAX 100000.0; STEP 1.0; MAXSLIDER 500.0; CUSTOMGUI REALSLIDER;}
				REAL IES_PREVIEW_DISTANCE2	{UNIT METER; MIN -500.0; MAX 500.0; STEP 1.0; MINSLIDER -100; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER;}
				REAL IES_LIGHT_HEIGHT2	{UNIT METER; MIN 0.0; MAX 100000.0; STEP 1.0; MAXSLIDER 500.0; CUSTOMGUI REALSLIDER;}

				BITMAPBUTTON IES_PREVIEW	{}
				BOOL IES_FRONT_PREVIEW		{}

			}
		}

		GROUP VRAYLIGHTTAG_AMBIENT
		{
			LONG VRAYLIGHTTAG_AMBIENT_MODE
			{
				CYCLE
				{
					VRAYLIGHTTAG_AMBIENT_MODE_0;
					VRAYLIGHTTAG_AMBIENT_MODE_1;
					VRAYLIGHTTAG_AMBIENT_MODE_2;
				}
			}

			REAL VRAYLIGHTTAG_AMBIENT_GIMINDISTANCE {MIN 0; STEP 0.1;}
			BOOL VRAYLIGHTTAG_AMBIENT_COMPEXPOSURE {}
		}
}
