CONTAINER tVrmeshExporter
{
	NAME tVrmeshExporter;
	
	DEFAULT 1;
	GROUP
	{
		STRING VRMESHEXPORTER_TITLEBAR		{ANIM OFF; CUSTOMGUI VRAYBAR_GUI;}
	}
	
	INCLUDE Tbase;
	
		
		GROUP VRMESHEXPORTER_PARAMS
		{
			DEFAULT 1;
			
			BOOL		VRMESHEXPORTER_SMOOTH		{}
			FILENAME	VRMESHEXPORTER_FILENAME		{HIDDEN;}
			VECTOR		VRMESHEXPORTER_RAD			{HIDDEN;}
			VECTOR		VRMESHEXPORTER_MP			{HIDDEN;}
			BOOL		VRMESHEXPORTER_DONTDELETE	{}
		}
		
}