#ifndef _tVrmeshExporter_H_
#define _tVrmeshExporter_H_

enum
{
	VRMESHEXPORTER_PARAMS	= 800,

	VRMESHEXPORTER_TITLEBAR	= 500,
	VRMESHEXPORTER_FILENAME	,
	VRMESHEXPORTER_RAD		,
	VRMESHEXPORTER_MP		,
	VRMESHEXPORTER_SMOOTH	,
	VRMESHEXPORTER_DONTDELETE
};

#endif
