 #ifndef _VPvraybridge_H_
#define _VPvraybridge_H_

enum
{

	/// TEMP 
	VP_VRAYBRIDGE_BETA_C4DSHADERS_NEWALLOCATED_FROM_VRSCENE = 18540, // temp ID
	VP_VRAYBRIDGE_USE_APPROXIMATED_OGLPREVIEW 				= 18541, // temp ID

	//CAMERA CLIPPER
	VP_VRAYBRIDGE_CLIPPER					= 1800,
	VP_VRAYBRIDGE_CLIPPER_DISTANCE_FRONT	= 1801,
	VP_VRAYBRIDGE_CLIPPER_DISTANCE_BACK		= 1802,
	VP_VRAYBRIDGE_CLIPPER_STORE_STATUS		= 1803,
	VP_VRAYBRIDGE_CLIPPER_START				= 1804,
	VP_VRAYBRIDGE_CLIPPER_RESTORE_STATUS	= 1805,
	VP_VRAYBRIDGE_CLIPPER_MODIFY_SCENE		= 1806,
	VP_VRAYBRIDGE_CLIPPER_TEXT01			= 1807,
	

	//OPTIONS
	VP_VRAYBRIDGE_OPTIONS				= 800,
	VP_VRAYBRIDGE_GEOMETRY				= 801,
	VP_VRAYBRIDGE_LIGHTING				= 802,
	VP_VRAYBRIDGE_INDIRECT				= 803,
	VP_VRAYBRIDGE_MATERIALS				= 804,
	VP_VRAYBRIDGE_SECONDARYRAYS			= 805,
	VP_VRAYBRIDGE_MISCELLANEUS			= 806,
	VP_VRAYBRIDGE_TITLEBAR				= 807,
	VP_VRAYBRIDGE_VOLUMETRICS			= 808,

	VP_VRAYBRIDGE_FAKEPARAM1			= 13001, //Remo: the same Id as VP_VRAYBRIDGE_TR_FILE_NAME
	VP_VRAYBRIDGE_FAKEPARAM2			= 13002,
	VP_VRAYBRIDGE_FAKEPARAM3			= 13003,

	VP_VRAYBRIDGE_DISP					= 1000,

	VP_VRAYBRIDGE_LIGHTS				= 1001,
	VP_VRAYBRIDGE_DEFAULTLIGHTS			= 1002,
	VP_VRAYBRIDGE_DEFAULTLIGHTS_0 = 0,
	VP_VRAYBRIDGE_DEFAULTLIGHTS_1 = 1,
	VP_VRAYBRIDGE_DEFAULTLIGHTS_2 = 2,
	VP_VRAYBRIDGE_HIDDENLIGHTS			= 1003,
	VP_VRAYBRIDGE_SHADOWS				= 1004,
	VP_VRAYBRIDGE_GIONLY				= 1005,
	VP_VRAYBRIDGE_PHOTOSCALE			= 1221,
	VP_VRAYBRIDGE_MSCALE				= 1225,
	VP_VRAYBRIDGE_MSCALE_0				= 0,
	VP_VRAYBRIDGE_MSCALE_1				= 1,
	VP_VRAYBRIDGE_MSCALE_2				= 2,
	VP_VRAYBRIDGE_MSCALE_3				= 3,
	VP_VRAYBRIDGE_MSCALE_4				= 4,
	VP_VRAYBRIDGE_MSCALE_5				= 5,
	VP_VRAYBRIDGE_C4DSHADOWS			= 1226,


	VP_VRAYBRIDGE_NORENDER				= 1006,

	VP_VRAYBRIDGE_REFLREFR				= 1007,
	VP_VRAYBRIDGE_LIMITDEPTH			= 1017,
	VP_VRAYBRIDGE_MAXDEPTH				= 1008,
	VP_VRAYBRIDGE_MAPS					= 1009,
	VP_VRAYBRIDGE_FILTERMAPS			= 1010,
	VP_VRAYBRIDGE_MAXTRANSPLEVELS		= 1011,
	VP_VRAYBRIDGE_TRANSPCUTOFF			= 1012,
	VP_VRAYBRIDGE_GLOSSY				= 1013,
	VP_VRAYBRIDGE_OTF_CONVERT_C4DMAT	= 1227,

	VP_VRAYBRIDGE_RAYSBIAS				= 1014,
	VP_VRAYBRIDGE_BACKCULL				= 1220,

	VP_VRAYBRIDGE_ENVOPTIMIZED			= 1015,
	VP_VRAYBRIDGE_LOWPRIORITY			= 1016,
	//VP_VRAYBRIDGE_OLDAA					= 1068,
	VP_VRAYBRIDGE_SAVESCENE				= 1018,
	VP_VRAYBRIDGE_SCENEFILE				= 1019,
	VP_VRAYBRIDGE_OVERRIDEMTL			= 1222,
	VP_VRAYBRIDGE_OVERRIDECLR			= 1223,
	VP_VRAYBRIDGE_OVERRIDELINK			= 1224,
	VP_VRAYBRIDGE_ENABLE_VOLUMETRICS	= 1700,
	VP_VRAYBRIDGE_VOLUMERAYDEPTH		,

	//VFB OPTIONS
	VP_VRAYBRIDGE_VFB					= 810,
	VP_VRAYBRIDGE_VFB_ON				= 1290,

	//GLOBAL ILLUMINATION
	VP_VRAYBRIDGE_GI					= 900,
	VP_VRAYBRIDGE_GICAUSTICS			= 901,
	VP_VRAYBRIDGE_POSTPROC				= 902,
	VP_VRAYBRIDGE_PRIMARYBOUNCE			= 903,
	VP_VRAYBRIDGE_SECONDARYBOUNCE		= 904,
	VP_VRAYBRIDGE_GIGENERAL				= 905,
	VP_VRAYBRIDGE_AO                    = 906,
	VP_VRAYBRIDGE_GI_PRESETS_GROUP		= 907,


	VP_VRAYBRIDGE_GI_ON					= 1050,
	VP_VRAYBRIDGE_SAVEGISETTINGS		= 1061,
	VP_VRAYBRIDGE_LOADGISETTINGS		= 1062,
	VP_VRAYBRIDGE_GI_PRESETS			= 1049,
	VP_VRAYBRIDGE_GI_PRESETS_TEXT01		= 1067,


	VP_VRAYBRIDGE_GINETRENDER			= 1351,
	VP_VRAYBRIDGE_GIANIMSTART           = 1355,
	VP_VRAYBRIDGE_GIANIMEND             = 1356,
	VP_VRAYBRIDGE_GIUSERAYDISTANCE		= 1357,
	VP_VRAYBRIDGE_GIRAYDISTANCE			= 1358,

	VP_VRAYBRIDGE_GI_REFLECTIVE			= 1051,
	VP_VRAYBRIDGE_GI_REFRACTIVE			= 1052,

	VP_VRAYBRIDGE_GI_SATURATION			= 1053,
	VP_VRAYBRIDGE_GI_CONTRAST			= 1054,
	VP_VRAYBRIDGE_GI_CONTRASTBASE		= 1055,
	VP_VRAYBRIDGE_GI_SAVEPERFRAME		= 1089,

	VP_VRAYBRIDGE_GIENGINE1_MULTIPLIER	= 1056,
	VP_VRAYBRIDGE_GIENGINE1				= 1057,
	VP_VRAYBRIDGE_GIENGINE_IRRADIANCE		= 0,
	VP_VRAYBRIDGE_GIENGINE_PHOTON1			= 1,
	VP_VRAYBRIDGE_GIENGINE_QUASIMC1			= 2,
	VP_VRAYBRIDGE_GIENGINE_LIGHTCACHE1		= 3,
	VP_VRAYBRIDGE_GIENGINE_SPHERICAL		= 4,

	VP_VRAYBRIDGE_MULTIPLIER2			= 1058,
	VP_VRAYBRIDGE_GIENGINE2				= 1059,
	VP_VRAYBRIDGE_GIENGINE_NONE				= 0,
	VP_VRAYBRIDGE_GIENGINE_PHOTON2			= 1,
	VP_VRAYBRIDGE_GIENGINE_QUASIMC2			= 2,
	VP_VRAYBRIDGE_GIENGINE_LIGHTCACHE2		= 3,

	VP_VRAYBRIDGE_AO_ON                     = 1063,
	VP_VRAYBRIDGE_AO_RADIUS                 = 1064,
	VP_VRAYBRIDGE_AO_SUBDIVS                = 1065,
	VP_VRAYBRIDGE_AO_AMOUNT                 = 1066,


	//IRRADIANCE MAP SETTINGS
	VP_VRAYBRIDGE_IRRADIANCE					= 940,
	VP_VRAYBRIDGE_IRRADBASICPARAMS				= 941,
	VP_VRAYBRIDGE_IRRADOPTIONS					= 942,
	VP_VRAYBRIDGE_IRRADDETAIL					= 943,
	VP_VRAYBRIDGE_IRRADADVANCED					= 944,
	VP_VRAYBRIDGE_IRRADMODE						= 945,
	VP_VRAYBRIDGE_IRRADONRENDEREND				= 946,

	VP_VRAYBRIDGE_IRRADMINRATE					= 1090,
	VP_VRAYBRIDGE_IRRADMAXRATE					= 1091,
	VP_VRAYBRIDGE_IRRADSUBDIV					= 1092,
	VP_VRAYBRIDGE_IRRADINTSAMPLES				= 1093,
	VP_VRAYBRIDGE_IRRADINTFRAMES				= 1350,
	VP_VRAYBRIDGE_IRRADINTTHRESH				= 1094,
	VP_VRAYBRIDGE_IRRADNORMTHRESH				= 1095,
	VP_VRAYBRIDGE_IRRADDISTTHRESH				= 1096,

	VP_VRAYBRIDGE_IRRADSHOWCALC					= 1097,
	VP_VRAYBRIDGE_IRRADSHOWCALCDIRECT			= 1098,
	VP_VRAYBRIDGE_IRRADSHOWSAMPLES				= 1099,
	VP_VRAYBRIDGE_IRRADPREVISMODE				= 1115,
	VP_VRAYBRIDGE_IRRADPREVISMODE_0					= 0,
	VP_VRAYBRIDGE_IRRADPREVISMODE_1					= 1,
	VP_VRAYBRIDGE_IRRADCAMPATH          		= 1125,

	VP_VRAYBRIDGE_IRRADDETAILON					= 1100,
	VP_VRAYBRIDGE_IRRADDETAILSCALE				= 1101,
	VP_VRAYBRIDGE_IRRADDETAILSCALE_SCREEN		= 0,
	VP_VRAYBRIDGE_IRRADDETAILSCALE_WORLD		= 1,

	VP_VRAYBRIDGE_IRRADDETAILRAD				= 1102,
	VP_VRAYBRIDGE_IRRADDETAILRAD2				= 1116,
	VP_VRAYBRIDGE_IRRADDETAILMULT				= 1103,

	VP_VRAYBRIDGE_IRRADINTERPTYPE				= 1104,
	VP_VRAYBRIDGE_IRRADINTERPTYPE_0					= 0,
	VP_VRAYBRIDGE_IRRADINTERPTYPE_1					= 1,
	VP_VRAYBRIDGE_IRRADINTERPTYPE_2					= 2,
	VP_VRAYBRIDGE_IRRADINTERPTYPE_3					= 3,

	VP_VRAYBRIDGE_IRRADSAMPLELOOKUP				= 1105,
	VP_VRAYBRIDGE_IRRADSAMPLELOOKUP_0				= 0,
	VP_VRAYBRIDGE_IRRADSAMPLELOOKUP_1				= 1,
	VP_VRAYBRIDGE_IRRADSAMPLELOOKUP_2				= 2,
	VP_VRAYBRIDGE_IRRADSAMPLELOOKUP_3				= 3,

	VP_VRAYBRIDGE_IRRADCALCINTSAMPLES			= 1106,
	VP_VRAYBRIDGE_IRRADMIXEDRES					= 1107,
	VP_VRAYBRIDGE_IRRADRANDOMIZE				= 1108,
	VP_VRAYBRIDGE_IRRADCHECKSAMPLE				= 1109,

	VP_VRAYBRIDGE_IRRADMAPMODE					= 1110,
	VP_VRAYBRIDGE_IRRADMAPMODE_0					= 0,
	VP_VRAYBRIDGE_IRRADMAPMODE_1					= 1,
	VP_VRAYBRIDGE_IRRADMAPMODE_2					= 2,
	VP_VRAYBRIDGE_IRRADMAPMODE_3					= 3,
	VP_VRAYBRIDGE_IRRADMAPMODE_4					= 4,
	VP_VRAYBRIDGE_IRRADMAPMODE_5					= 5,
	VP_VRAYBRIDGE_IRRADMAPMODE_6					= 6,
	VP_VRAYBRIDGE_IRRADMAPMODE_7					= 7,
	VP_VRAYBRIDGE_IRRADFILE						= 1111,
	VP_VRAYBRIDGE_IRRADFILE2					= 1352,
	VP_VRAYBRIDGE_IRRADSAVEFILE					= 1117,
	VP_VRAYBRIDGE_IRRADSAVEFILE2				= 1353,
	VP_VRAYBRIDGE_IRRADSAVEBUTTON				= 1118,

	VP_VRAYBRIDGE_IRRADNODELETE					= 1112,
	VP_VRAYBRIDGE_IRRADAUTOSAVEMAP				= 1113,
	VP_VRAYBRIDGE_IRRADAUTOSAVEFILE				= 1114,
	VP_VRAYBRIDGE_IRRADAUTOSAVEFILE2			= 1354,
	VP_VRAYBRIDGE_IRRADSWITCHSAVEMAP			= 1119,
	VP_VRAYBRIDGE_SAVEIR						= 1122,

	//QMC GI
	VP_VRAYBRIDGE_QMCGI							= 950,
	VP_VRAYBRIDGE_QMCDEPTH						= 1120,
	VP_VRAYBRIDGE_QMCSUBDIV						= 1121,

	//GLOBAL PHOTON MAP
	VP_VRAYBRIDGE_PHOTONMAP						= 960,
	VP_VRAYBRIDGE_PHOTONMODE					= 961,
	VP_VRAYBRIDGE_PHOTONONRENDEREND				= 962,
	VP_VRAYBRIDGE_PHOTONBOUNCES					= 1130,
	VP_VRAYBRIDGE_AUTODIST						= 1131,
	VP_VRAYBRIDGE_SEARCHDIST					= 1132,
	VP_VRAYBRIDGE_MAXPHOTONS					= 1133,
	VP_VRAYBRIDGE_PHOTONMULT					= 1134,
	VP_VRAYBRIDGE_MAXDENSITY					= 1135,
	VP_VRAYBRIDGE_PHOTONINTSAMPLES				= 1136,
	VP_VRAYBRIDGE_CONVEXHULL					= 1137,
	VP_VRAYBRIDGE_STOREDIRECT					= 1138,
	VP_VRAYBRIDGE_PHOTONRETRACETHRESHOLD		= 1144,
	VP_VRAYBRIDGE_PHOTONRETRACEBOUNCES			= 1145,
	VP_VRAYBRIDGE_PHOTONPREFILTER				= 1146,
	VP_VRAYBRIDGE_PHOTONSHOWCALC				= 1147,

	VP_VRAYBRIDGE_PHOTONMAPMODE					= 1139,
	VP_VRAYBRIDGE_PHOTONMAPMODE_0					= 0,
	VP_VRAYBRIDGE_PHOTONMAPMODE_1					= 1,
	VP_VRAYBRIDGE_PHOTONMAPFILE					= 1140,
	VP_VRAYBRIDGE_PHOTONMAPFILE2				= 1148,

	VP_VRAYBRIDGE_SAVEPM						= 1123,

	VP_VRAYBRIDGE_PHOTONNODELETE				= 1141,
	VP_VRAYBRIDGE_PHOTONAUTOSAVEMAP				= 1142,
	VP_VRAYBRIDGE_PHOTONAUTOSAVEFILE			= 1143,
	VP_VRAYBRIDGE_PHOTONAUTOSAVEFILE2			= 1149,

	//LIGHTCACHE
	VP_VRAYBRIDGE_LIGHTCACHE					= 980,
	VP_VRAYBRIDGE_LIGHTCACHE_CALCULATION		= 981,
	VP_VRAYBRIDGE_LIGHTCACHE_RECONSTRUCTION 	= 982,
	VP_VRAYBRIDGE_LIGHTCACHE_MODE				= 983,
	VP_VRAYBRIDGE_LIGHTCACHE_RENDEREND			= 984,

	VP_VRAYBRIDGE_LIGHTCACHE_OVERRIDE			= 1650,
	VP_VRAYBRIDGE_LIGHTCACHE_RATIO				= 1651,
	VP_VRAYBRIDGE_LIGHTCACHE_RATIO_0			= 0,
	VP_VRAYBRIDGE_LIGHTCACHE_RATIO_1			= 1,
	VP_VRAYBRIDGE_LIGHTCACHE_RATIO_2			= 2,
	VP_VRAYBRIDGE_LIGHTCACHE_RATIO_3			= 3,
	VP_VRAYBRIDGE_LIGHTCACHE_RATIO_4			= 4,
	VP_VRAYBRIDGE_LIGHTCACHE_RATIO_5			= 5,
	VP_VRAYBRIDGE_LIGHTCACHE_RATIO_6			= 6,

	VP_VRAYBRIDGE_LIGHTCACHE_SUBDIV				= 1171,
	VP_VRAYBRIDGE_LIGHTCACHE_SAMPLESIZE			= 1172,
	VP_VRAYBRIDGE_LIGHTCACHE_SAMPLESIZE2		= 1179,
	VP_VRAYBRIDGE_LIGHTCACHE_MINPATH			= 1660,
	VP_VRAYBRIDGE_LIGHTCACHE_SCALE				= 1173,
	VP_VRAYBRIDGE_LIGHTCACHE_SCALE_0				= 0,
	VP_VRAYBRIDGE_LIGHTCACHE_SCALE_1				= 1,
	VP_VRAYBRIDGE_LIGHTCACHE_PASSES				= 1174,
	VP_VRAYBRIDGE_LIGHTCACHE_STOREDIRECT		= 1175,
	VP_VRAYBRIDGE_LIGHTCACHE_SHOWCALCPHASE		= 1176,
	VP_VRAYBRIDGE_LIGHTCACHE_ADAPTIVE			= 1177,
	VP_VRAYBRIDGE_LIGHTCACHE_ADAPTIVEDIRONLY	= 1178,
	VP_VRAYBRIDGE_LIGHTCACHE_CAMPATH            = 1661,

	VP_VRAYBRIDGE_LIGHTCACHE_PREFILTER			= 1160,
	VP_VRAYBRIDGE_LIGHTCACHE_PREFILTERSAMPLES	= 1161,
	VP_VRAYBRIDGE_LIGHTCACHE_DOGLOSSIES			= 1162,
	VP_VRAYBRIDGE_LIGHTCACHE_FILTERTYPE			= 1163,
	VP_VRAYBRIDGE_LIGHTCACHE_FILTERTYPE_0			= 0,
	VP_VRAYBRIDGE_LIGHTCACHE_FILTERTYPE_1			= 1,
	VP_VRAYBRIDGE_LIGHTCACHE_FILTERTYPE_2			= 2,
	VP_VRAYBRIDGE_LIGHTCACHE_FILTERSIZE			= 1164,
	VP_VRAYBRIDGE_LIGHTCACHE_INTERPSAMPLES		= 1165,
	VP_VRAYBRIDGE_LIGHTCACHE_LIGHTMAPMODE		= 1166,
	VP_VRAYBRIDGE_LIGHTCACHE_LIGHTMAPMODE_0			= 0,
	VP_VRAYBRIDGE_LIGHTCACHE_LIGHTMAPMODE_1			= 1,
	VP_VRAYBRIDGE_LIGHTCACHE_LIGHTMAPMODE_2			= 2,
	VP_VRAYBRIDGE_LIGHTCACHE_LIGHTMAPMODE_3			= 3,
	VP_VRAYBRIDGE_LIGHTCACHE_DEPTH				= 1127,
	VP_VRAYBRIDGE_LIGHTCACHE_RETRACE			= 1670,
	VP_VRAYBRIDGE_LIGHTCACHE_RETRACETHRESHOLD	= 1671,

	VP_VRAYBRIDGE_SAVELC						= 1124,

	VP_VRAYBRIDGE_LIGHTCACHE_LIGHTMAPFILE		= 1167,
	VP_VRAYBRIDGE_LIGHTCACHE_LIGHTMAPFILE2		= 1450,
	VP_VRAYBRIDGE_LIGHTCACHE_NODELETE			= 1168,
	VP_VRAYBRIDGE_LIGHTCACHE_AUTOSAVEMAP		= 1169,
	VP_VRAYBRIDGE_LIGHTCACHE_AUTOSAVEFILE		= 1170,
	VP_VRAYBRIDGE_LIGHTCACHE_AUTOSAVEFILE2		= 1451,
	VP_VRAYBRIDGE_LIGHTCACHE_FRAMEFROM			= 1452,
	VP_VRAYBRIDGE_LIGHTCACHE_FRAMETO			= 1453,


	// SPHERICAL HARMONICS

	VP_VRAYBRIDGE_SPHERICALHARMONICS				= 985,
	VP_VRAYBRIDGE_SPHERICALHARMONICS_SUBDIVS		= 1230,
	VP_VRAYBRIDGE_SPHERICALHARMONICS_HEMISPHERICAL	= 1231,
	VP_VRAYBRIDGE_SPHERICALHARMONICS_PRECALC		= 1232,
	VP_VRAYBRIDGE_SPHERICALHARMONICS_SAMPLEENV		= 1233,
	VP_VRAYBRIDGE_SPHERICALHARMONICS_FILTERING		= 1234,
	VP_VRAYBRIDGE_SPHERICALHARMONICS_FILTERSTRENGHT	= 1235,


	//PHOTON CAUSTICS

	VP_VRAYBRIDGE_CAUSTICS				= 970,
	VP_VRAYBRIDGE_CAUSTICSMODE			= 971,
	VP_VRAYBRIDGE_CAUSTICSONRENDEREND	= 972,

	VP_VRAYBRIDGE_CAUSTICSON			= 1150,
	VP_VRAYBRIDGE_CAUSTICSSEARCHDIST	= 1152,
	VP_VRAYBRIDGE_CAUSTICSMAXPHOTONS	= 1153,
	VP_VRAYBRIDGE_CAUSTICSMULT			= 1154,
	VP_VRAYBRIDGE_CAUSTICSMAXDENSITY	= 1155,
	VP_VRAYBRIDGE_CAUSTICSSHOWCALC		= 1456,

	VP_VRAYBRIDGE_CAUSTICSMAPMODE		= 1156,
	VP_VRAYBRIDGE_CAUSTICSMAPMODE_0		= 0,
	VP_VRAYBRIDGE_CAUSTICSMAPMODE_1		= 1,
	VP_VRAYBRIDGE_CAUSTICSMAPFILE		= 1157,
	VP_VRAYBRIDGE_CAUSTICSMAPFILE2		= 1454,

	VP_VRAYBRIDGE_SAVECA				= 1126,

	VP_VRAYBRIDGE_CAUSTICSNODELETE		= 1158,
	VP_VRAYBRIDGE_CAUSTICSAUTOSAVEMAP	= 1159,
	VP_VRAYBRIDGE_CAUSTICSAUTOSAVEFILE	= 1151,
	VP_VRAYBRIDGE_CAUSTICSAUTOSAVEFILE2	= 1455,



	//DISPLACEMENT

	VP_VRAYBRIDGE_DISPLACEMENT			= 995,

	VP_VRAYBRIDGE_DISPLACEMENT_VIEWDEP	= 1400,
	VP_VRAYBRIDGE_DISPLACEMENT_RELATIVE = 1401,
	VP_VRAYBRIDGE_DISPLACEMENT_BOUNDS	= 1402,
	VP_VRAYBRIDGE_DISPLACEMENT_EDGE		= 1403,
	VP_VRAYBRIDGE_DISPLACEMENT_SUBDIVS	= 1404,
	VP_VRAYBRIDGE_DISPLACEMENT_AMOUNT	= 1405,


	//ENVIRONMENT

	VP_VRAYBRIDGE_ENVIRONMENT			= 990,
	VP_VRAYBRIDGE_ENVIRONMENT_OPTIONS	= 993,
	VP_VRAYBRIDGE_ENVIRONMENT_BGTAB		= 996,
	VP_VRAYBRIDGE_ENVIRONMENT_GITAB		= 997,
	VP_VRAYBRIDGE_ENVIRONMENT_REFLTAB	= 998,
	VP_VRAYBRIDGE_ENVIRONMENT_REFRTAB	= 999,

	VP_VRAYBRIDGE_ENVIRONMENT_FOGTEX = 1330,

	VP_VRAYBRIDGE_ENVIRONMENT_AMBIENT			= 1180,
	VP_VRAYBRIDGE_ENVIRONMENT_BACKGROUND		= 1181,
	VP_VRAYBRIDGE_ENVIRONMENT_GIBACKGROUND		= 1182,
	VP_VRAYBRIDGE_ENVIRONMENT_REFLBACKGROUND	= 1183,
	VP_VRAYBRIDGE_ENVIRONMENT_REFRBACKGROUND	= 1184,

	VP_VRAYBRIDGE_ENVIRONMENT_AMBIENTTEX		= 1185,
	VP_VRAYBRIDGE_ENVIRONMENT_BACKGROUNDTEX		= 1186,
	VP_VRAYBRIDGE_ENVIRONMENT_GIBACKGROUNDTEX	= 1187,
	VP_VRAYBRIDGE_ENVIRONMENT_REFLBACKGROUNDTEX	= 1188,
	VP_VRAYBRIDGE_ENVIRONMENT_REFRBACKGROUNDTEX	= 1189,

	VP_VRAYBRIDGE_ENVIRONMENT_BGMAPTYPE			= 1300,
	VP_VRAYBRIDGE_ENVIRONMENT_BGMAPTYPE_0		= 0,
	VP_VRAYBRIDGE_ENVIRONMENT_BGMAPTYPE_1		= 1,
	VP_VRAYBRIDGE_ENVIRONMENT_BGMAPTYPE_2		= 2,
	VP_VRAYBRIDGE_ENVIRONMENT_BGMAPTYPE_3		= 3,
	VP_VRAYBRIDGE_ENVIRONMENT_BGMAPTYPE_4		= 4,
	VP_VRAYBRIDGE_ENVIRONMENT_BGMAPROTH			= 1301,
	VP_VRAYBRIDGE_ENVIRONMENT_BGMAPROTP			= 1320,
	VP_VRAYBRIDGE_ENVIRONMENT_BGMAPMUL			= 1302,
	VP_VRAYBRIDGE_ENVIRONMENT_BGCOLORMULT		= 1303,

	VP_VRAYBRIDGE_ENVIRONMENT_GIMAPTYPE			= 1306,
	VP_VRAYBRIDGE_ENVIRONMENT_GIMAPTYPE_0		= 0,
	VP_VRAYBRIDGE_ENVIRONMENT_GIMAPTYPE_1		= 1,
	VP_VRAYBRIDGE_ENVIRONMENT_GIMAPTYPE_2		= 2,
	VP_VRAYBRIDGE_ENVIRONMENT_GIMAPTYPE_3		= 3,
	VP_VRAYBRIDGE_ENVIRONMENT_GIMAPTYPE_4		= 4,
	VP_VRAYBRIDGE_ENVIRONMENT_GIMAPROTH			= 1307,
	VP_VRAYBRIDGE_ENVIRONMENT_GIMAPROTP			= 1322,
	VP_VRAYBRIDGE_ENVIRONMENT_GIMAPMUL			= 1308,
	VP_VRAYBRIDGE_ENVIRONMENT_GICOLORMULT		= 1309,

	VP_VRAYBRIDGE_ENVIRONMENT_REFLMAPTYPE		= 1311,
	VP_VRAYBRIDGE_ENVIRONMENT_REFLMAPTYPE_0		= 0,
	VP_VRAYBRIDGE_ENVIRONMENT_REFLMAPTYPE_1		= 1,
	VP_VRAYBRIDGE_ENVIRONMENT_REFLMAPTYPE_2		= 2,
	VP_VRAYBRIDGE_ENVIRONMENT_REFLMAPTYPE_3		= 3,
	VP_VRAYBRIDGE_ENVIRONMENT_REFLMAPTYPE_4		= 4,
	VP_VRAYBRIDGE_ENVIRONMENT_REFLMAPROTH		= 1312,
	VP_VRAYBRIDGE_ENVIRONMENT_REFLMAPROTP		= 1324,
	VP_VRAYBRIDGE_ENVIRONMENT_REFLMAPMUL		= 1313,
	VP_VRAYBRIDGE_ENVIRONMENT_REFLCOLORMULT		= 1314,

	VP_VRAYBRIDGE_ENVIRONMENT_REFRMAPTYPE		= 1316,
	VP_VRAYBRIDGE_ENVIRONMENT_REFRMAPTYPE_0		= 0,
	VP_VRAYBRIDGE_ENVIRONMENT_REFRMAPTYPE_1		= 1,
	VP_VRAYBRIDGE_ENVIRONMENT_REFRMAPTYPE_2		= 2,
	VP_VRAYBRIDGE_ENVIRONMENT_REFRMAPTYPE_3		= 3,
	VP_VRAYBRIDGE_ENVIRONMENT_REFRMAPTYPE_4		= 4,
	VP_VRAYBRIDGE_ENVIRONMENT_REFRMAPROTH		= 1317,
	VP_VRAYBRIDGE_ENVIRONMENT_REFRMAPROTP		= 1326,
	VP_VRAYBRIDGE_ENVIRONMENT_REFRMAPMUL		= 1318,
	VP_VRAYBRIDGE_ENVIRONMENT_REFRCOLORMULT		= 1319,

	VP_VRAYBRIDGE_ENVIRONMENT_BGNOGI			= 1327,
	VP_VRAYBRIDGE_ENVIRONMENT_BGNOREFL		= 1328,
	VP_VRAYBRIDGE_ENVIRONMENT_BGNOREFR		= 1329,


	//ENVIRONMENT FOG
	VP_VRAYBRIDGE_ENVIRONMENTFOG					= 994,

	VP_VRAYBRIDGE_ENVIRONMENTFOG_ON					= 1470,
	VP_VRAYBRIDGE_ENVIRONMENTFOG_COLOR				,
	VP_VRAYBRIDGE_ENVIRONMENTFOG_DISTANCE			,
	VP_VRAYBRIDGE_ENVIRONMENTFOG_DENSITY			,
	VP_VRAYBRIDGE_ENVIRONMENTFOG_EMITCOLOR			,
	VP_VRAYBRIDGE_ENVIRONMENTFOG_USEHEIGHT			,
	VP_VRAYBRIDGE_ENVIRONMENTFOG_HEIGHT				,
	VP_VRAYBRIDGE_ENVIRONMENTFOG_SCATTERGI			,
	VP_VRAYBRIDGE_ENVIRONMENTFOG_SCATTERBOUNCES		,
	VP_VRAYBRIDGE_ENVIRONMENTFOG_SUBDIVS			,
	VP_VRAYBRIDGE_ENVIRONMENTFOG_STEPSIZE			,
	VP_VRAYBRIDGE_ENVIRONMENTFOG_TEXSAMPLES			,
	VP_VRAYBRIDGE_ENVIRONMENTFOG_SIMPLEGI			,
	VP_VRAYBRIDGE_ENVIRONMENTFOG_CUTOFF				,
	VP_VRAYBRIDGE_ENVIRONMENTFOG_MAXSTEPS			,
	VP_VRAYBRIDGE_ENVIRONMENTFOG_AFFECTBG			,
    VP_VRAYBRIDGE_ENVIRONMENTFOG_AFFECTREFL			= 2500,
    VP_VRAYBRIDGE_ENVIRONMENTFOG_AFFECTREFR			,
    VP_VRAYBRIDGE_ENVIRONMENTFOG_AFFECTSHD			,
    VP_VRAYBRIDGE_ENVIRONMENTFOG_AFFECTGI			,
    VP_VRAYBRIDGE_ENVIRONMENTFOG_AFFECTCAM			,


	VP_VRAYBRIDGE_ENVIRONMENTFOG_FADERADIUS			= 1486,
	VP_VRAYBRIDGE_ENVIRONMENTFOG_FADEMODE			,
	VP_VRAYBRIDGE_ENVIRONMENTFOG_FADEMODE_0			= 0,
	VP_VRAYBRIDGE_ENVIRONMENTFOG_FADEMODE_1			= 1,
	VP_VRAYBRIDGE_ENVIRONMENTFOG_FADEOUTEDGE		= 1488,

	VP_VRAYBRIDGE_ENVIRONMENTFOG_COLORTEX			= 1490,
	VP_VRAYBRIDGE_ENVIRONMENTFOG_EMITTEX			,
	VP_VRAYBRIDGE_ENVIRONMENTFOG_DENSITYTEX			,
	VP_VRAYBRIDGE_ENVIRONMENTFOG_FADEOUTTEX			,

	VP_VRAYBRIDGE_ENVIRONMENTFOG_OBJINCLUDE_LIST 	= 1495,
	VP_VRAYBRIDGE_ENVIRONMENTFOG_LIGHTINCLUDE_LIST 	,


	//QMC SAMPLER

	VP_VRAYBRIDGE_QMCSAMPLER			= 991,

	VP_VRAYBRIDGE_QMCSAMPLER_ADAPTIVE	= 1190,
	VP_VRAYBRIDGE_QMCSAMPLER_ADAPTTHR	= 1191,
	VP_VRAYBRIDGE_QMCSAMPLER_ADAPSAMP	= 1192,
	VP_VRAYBRIDGE_QMCSAMPLER_SUBDIVMULT	= 1193,
	VP_VRAYBRIDGE_QMCSAMPLER_TIMEDEP	= 1194,
	VP_VRAYBRIDGE_QMCSAMPLER_PATHSAMPLER = 1195,
	VP_VRAYBRIDGE_QMCSAMPLER_PATHSAMPLER_0 = 0,
	VP_VRAYBRIDGE_QMCSAMPLER_PATHSAMPLER_1 = 1,
	VP_VRAYBRIDGE_QMCSAMPLER_PATHSAMPLER_2 = 2,



	//COLOR MAPPING

	VP_VRAYBRIDGE_COLORMAPPING			= 992,

	VP_VRAYBRIDGE_COLORMAPPING_TYPE		= 1200,
	VP_VRAYBRIDGE_COLORMAPPING_TYPE_0	= 0,
	VP_VRAYBRIDGE_COLORMAPPING_TYPE_1	= 1,
	VP_VRAYBRIDGE_COLORMAPPING_TYPE_2	= 2,
	VP_VRAYBRIDGE_COLORMAPPING_TYPE_3	= 3,
	VP_VRAYBRIDGE_COLORMAPPING_TYPE_4	= 4,
	VP_VRAYBRIDGE_COLORMAPPING_TYPE_5	= 5,
	VP_VRAYBRIDGE_COLORMAPPING_TYPE_6	= 6,
	VP_VRAYBRIDGE_COLORMAPPING_DARKMUL	= 1201,
	VP_VRAYBRIDGE_COLORMAPPING_BRIGHTMUL = 1202,
	VP_VRAYBRIDGE_COLORMAPPING_GAMMA	= 1203,
	VP_VRAYBRIDGE_COLORMAPPING_SUBPIXEL	= 1204,
	VP_VRAYBRIDGE_COLORMAPPING_CLAMP	= 1205,
	VP_VRAYBRIDGE_COLORMAPPING_AFFECTBG = 1206,
	VP_VRAYBRIDGE_COLORMAPPING_ADAPTATION = 1207,
	VP_VRAYBRIDGE_COLORMAPPING_MULTIPLIER	= 1208,
	VP_VRAYBRIDGE_COLORMAPPING_INVERSEGAMMA = 1209,
	VP_VRAYBRIDGE_COLORMAPPING_BURN			= 1210,
	VP_VRAYBRIDGE_COLORMAPPING_CLAMPLEVEL	= 1211,
	VP_VRAYBRIDGE_COLORMAPPING_LWF      = 1212,
	VP_VRAYBRIDGE_COLORMAPPING_ADAPTATION_NOVIEWPORT = 1213,



	//ANTIALIASING

	VP_VRAYBRIDGE_ANTIALIASING			= 910,
	VP_VRAYBRIDGE_IMGSAMPLER			= 911,
	VP_VRAYBRIDGE_IMGFILTER				= 912,
	VP_VRAYBRIDGE_TYPEFIXED				= 913,
	VP_VRAYBRIDGE_TYPEQMC				= 914,
	VP_VRAYBRIDGE_TYPEADAPTIVE			= 915,

	VP_VRAYBRIDGE_SAMPLER				= 1020,
	VP_VRAYBRIDGE_SAMPLER_FIXED			= 0,
	VP_VRAYBRIDGE_SAMPLER_ADAPTIVEQMC	= 1,
	VP_VRAYBRIDGE_SAMPLER_ADAPTIVESUBD	= 2,

	VP_VRAYBRIDGE_FILTERON				= 1021,
	VP_VRAYBRIDGE_FILTER				= 1022,
	VP_VRAYBRIDGE_FILTER_BOX			= 0,
	VP_VRAYBRIDGE_FILTER_DISC			= 1,
	VP_VRAYBRIDGE_FILTER_TRIANGLE		= 2,
	VP_VRAYBRIDGE_FILTER_WELCH			= 3,
	VP_VRAYBRIDGE_FILTER_PARZEN			= 4,
	VP_VRAYBRIDGE_FILTER_HANN			= 5,
	VP_VRAYBRIDGE_FILTER_BLACKMAN		= 6,
	VP_VRAYBRIDGE_FILTER_LANCZOS		= 7,
	VP_VRAYBRIDGE_FILTER_SINC			= 8,
	VP_VRAYBRIDGE_FILTER_MITCHELL		= 9,
	VP_VRAYBRIDGE_FILTER_AREA			= 10,
	VP_VRAYBRIDGE_FILTER_CATMULL		= 11,
	VP_VRAYBRIDGE_FILTER_GAUSSIAN		= 12,
	VP_VRAYBRIDGE_FILTERSIZE			= 1023,
	VP_VRAYBRIDGE_BLURSIZE				= 1037,
	VP_VRAYBRIDGE_RINGSIZE				= 1038,

	VP_VRAYBRIDGE_SUBDIV1				= 1024,

	VP_VRAYBRIDGE_MINSUBDIV				= 1025,
	VP_VRAYBRIDGE_MAXSUBDIV				= 1026,
	VP_VRAYBRIDGE_THRESHOLD				= 1030,
	VP_VRAYBRIDGE_LOCKTHRESHOLD			= 1270,
	VP_VRAYBRIDGE_DMCSHOWSAMPLES		= 1271,

	VP_VRAYBRIDGE_MINRATE				= 1027,
	VP_VRAYBRIDGE_MAXRATE				= 1028,
	VP_VRAYBRIDGE_THRESH				= 1029,
	VP_VRAYBRIDGE_AAEDGES				= 1031,
	VP_VRAYBRIDGE_AANORMALS				= 1032,
	VP_VRAYBRIDGE_AAMTLID				= 1033,
	VP_VRAYBRIDGE_AAZVALUE				= 1034,
	VP_VRAYBRIDGE_NMLTHRESH				= 1035,
	VP_VRAYBRIDGE_ZTHRESH				= 1036,
	VP_VRAYBRIDGE_JITTER				= 1039,
	VP_VRAYBRIDGE_ADAPTSHOWSAMPLES		= 1272,


	//SYSTEM

	VP_VRAYBRIDGE_SYSTEM				= 920,
	VP_VRAYBRIDGE_RAYCASTER				= 921,
	VP_VRAYBRIDGE_RENDERREGION			= 922,
	VP_VRAYBRIDGE_GROUP_REGIONSPLIT		= 923,
	VP_VRAYBRIDGE_GROUP_PATH			= 924,

	VP_VRAYBRIDGE_MAXLEVELS 			= 1040,
	VP_VRAYBRIDGE_MINLEAFSIZE			= 1041,
	VP_VRAYBRIDGE_FACELEVELCOEF			= 1042,
	VP_VRAYBRIDGE_MEMLIMIT				= 1043,
	VP_VRAYBRIDGE_OPTLEVEL				= 1360,

	VP_VRAYBRIDGE_BUCKETX				= 1044,
	VP_VRAYBRIDGE_BUCKETY				= 1045,
	VP_VRAYBRIDGE_VIEWPORTBUCKETX		= 1370,
	VP_VRAYBRIDGE_VIEWPORTBUCKETY		= 1371,
	VP_VRAYBRIDGE_XYMEANS				= 1046,
	VP_VRAYBRIDGE_XYMEANS_REGIONWH		= 0,
	VP_VRAYBRIDGE_XYMEANS_REGIONCOUNT	= 1,
	VP_VRAYBRIDGE_SEQTYPE				= 1047,
	VP_VRAYBRIDGE_SEQTYPE_TOPBOTTOM		= 0,
	VP_VRAYBRIDGE_SEQTYPE_LEFTRIGHT		= 1,
	VP_VRAYBRIDGE_SEQTYPE_CHECKER		= 2,
	VP_VRAYBRIDGE_SEQTYPE_SPIRAL		= 3,
	VP_VRAYBRIDGE_SEQTYPE_TRIANGULATION	= 4,
	VP_VRAYBRIDGE_SEQTYPE_HILBERT		= 5,
	VP_VRAYBRIDGE_SEQTYPE_FOLLOWMOUSE	= 6,
	VP_VRAYBRIDGE_SEQTYPE_SMART			= 7,

	VP_VRAYBRIDGE_REVERSE				= 1048,
	VP_VRAYBRIDGE_PREVIOUS_PICTURE_OPACITY = 1274,

	VP_VRAYBRIDGE_REGIONON				= 1500,
	VP_VRAYBRIDGE_REGIONRENDER_X1		,
	VP_VRAYBRIDGE_REGIONRENDER_X2		,
	VP_VRAYBRIDGE_REGIONRENDER_Y1		,
	VP_VRAYBRIDGE_REGIONRENDER_Y2		,
	VP_VRAYBRIDGE_SPLIT					,
	VP_VRAYBRIDGE_SPLITON				,
	VP_VRAYBRIDGE_GETLASTREGION			,
	VP_VRAYBRIDGE_STAMP					,
	VP_VRAYBRIDGE_SPLITPIXELS			,

	// STAMP FIELD
	VP_VRAYBRDIGE_STAMP_CPU_TYPE		,
	VP_VRAYBRDIGE_STAMP_OS				,
	VP_VRAYBRDIGE_STAMP_GHZ				,
	VP_VRAYBRDIGE_STAMP_TIME			,
	VP_VRAYBRDIGE_STAMP_PRIMITIVE		,
	VP_VRAYBRIDGE_STAMP_STRING			,



	//CAMERA

	VP_VRAYBRIDGE_CAMERA				= 930,
	VP_VRAYBRIDGE_DOF					= 931,
	VP_VRAYBRIDGE_MBLUR					= 932,

	VP_VRAYBRIDGE_CAMTYPE				= 1070,
	VP_VRAYBRIDGE_CAMTYPE_STANDARD		= 0,
	VP_VRAYBRIDGE_CAMTYPE_SPHERICAL		= 1,
	VP_VRAYBRIDGE_CAMTYPE_CYLINDRICAL	= 2,
	VP_VRAYBRIDGE_CAMTYPE_CYLORTHO		= 3,
	VP_VRAYBRIDGE_CAMTYPE_BOX		= 4,
	VP_VRAYBRIDGE_CAMTYPE_FISHEYE		= 5,
	VP_VRAYBRIDGE_CAMTYPE_WARPED		= 6,
	VP_VRAYBRIDGE_CAMTYPE_ORTHOGONAL        = 7,
	VP_VRAYBRIDGE_CAMTYPE_PINHOLE           = 8,

	VP_VRAYBRIDGE_CAMTYPE_CYLINDRICAL_HEIGHT = 1250,
	VP_VRAYBRIDGE_CAMTYPE_FISHEYE_AUTO	= 1251,
	VP_VRAYBRIDGE_CAMTYPE_FISHEYE_DELTA = 1252,
	VP_VRAYBRIDGE_CAMTYPE_FISHEYE_CURVE = 1253,
	VP_VRAYBRIDGE_CAMTYPE_ORTHO_ZOOM	= 1254,

	VP_VRAYBRIDGE_DOFON					= 1071,
	VP_VRAYBRIDGE_DOFAPERTURE			= 1088,
	VP_VRAYBRIDGE_DOFSUBDIV				= 1072,
	VP_VRAYBRIDGE_DOFBIAS				= 1073,
	VP_VRAYBRIDGE_DOFSIDESON			= 1074,
	VP_VRAYBRIDGE_DOFSIDESNUM			= 1075,
	VP_VRAYBRIDGE_DOFROT				= 1087,
	VP_VRAYBRIDGE_DOFANISO				= 1076,
	VP_VRAYBRIDGE_MBLURON				= 1077,
	VP_VRAYBRIDGE_MBLURGEOMSAMPLES		= 1078,
	VP_VRAYBRIDGE_MBLURGEOMSAMPLEOFFSET	= 1079,
	VP_VRAYBRIDGE_MBLURMINSAMPLES		= 1080,
	VP_VRAYBRIDGE_MBLURMAXSAMPLES		= 1081,
	VP_VRAYBRIDGE_MBLURDURATION			= 1082,
	VP_VRAYBRIDGE_MBLURINTERVAL			= 1083,
	VP_VRAYBRIDGE_MBLURBIAS				= 1084,
	VP_VRAYBRIDGE_MBLURPARTICLES		= 1085,
	VP_VRAYBRIDGE_MBLURLOWSAMPLES		= 1086,
	VP_VRAYBRIDGE_MBLUR_NOCAMERA		= 6985,

	VP_VRAYBRIDGE_CLIPPING				= 1255,
	VP_VRAYBRIDGE_CLIPNEAR				= 1256,
	VP_VRAYBRIDGE_CLIPFAR				= 1257,

	VP_VRAYBRIDGE_ACTIVE_CAMERA			= 1273,

	VP_VRAYBRIDGE_CAMTYPE_PARALLEL		= 1258,
	VP_VRAYBRIDGE_CAMTYPE_PARALLEL_ADJUST = 1259,
	VP_VRAYBRIDGE_CAMTYPE_PARALLEL_ZOOM	= 1260,
	VP_VRAYBRIDGE_OVERRIDEFOV			= 1261,
	VP_VRAYBRIDGE_VRAYFOV				= 1262,



	//MULTIPASS

	VP_VRAYBRIDGE_MULTIPASS				= 850,
	VP_VRAYBRIDGE_MULTIPASS_ATMOSPHERE	= 1600,
	VP_VRAYBRIDGE_MULTIPASS_DIFFUSE		,
	VP_VRAYBRIDGE_MULTIPASS_REFLECT		,
	VP_VRAYBRIDGE_MULTIPASS_REFRACT		,
	VP_VRAYBRIDGE_MULTIPASS_SELFILLUM	,
	VP_VRAYBRIDGE_MULTIPASS_SHADOW		,
	VP_VRAYBRIDGE_MULTIPASS_SPECULAR	,
	VP_VRAYBRIDGE_MULTIPASS_LIGHTING	,
	VP_VRAYBRIDGE_MULTIPASS_GI			,
	VP_VRAYBRIDGE_MULTIPASS_CAUSTICS	,
	VP_VRAYBRIDGE_MULTIPASS_RAWGI		,
	VP_VRAYBRIDGE_MULTIPASS_RAWLIGHT	,
	VP_VRAYBRIDGE_MULTIPASS_RAWSHADOW	,
	VP_VRAYBRIDGE_MULTIPASS_VELOCITY	,
	VP_VRAYBRIDGE_MULTIPASS_RENDERID	,
	VP_VRAYBRIDGE_MULTIPASS_MTLID		,
	VP_VRAYBRIDGE_MULTIPASS_NODEID		,
	VP_VRAYBRIDGE_MULTIPASS_ZDEPTH		,
	VP_VRAYBRIDGE_MULTIPASS_REFLECTION_FILTER	,
	VP_VRAYBRIDGE_MULTIPASS_RAW_REFLECTION		,
	VP_VRAYBRIDGE_MULTIPASS_REFRACTION_FILTER	,
	VP_VRAYBRIDGE_MULTIPASS_RAW_REFRACTION		,
	VP_VRAYBRIDGE_MULTIPASS_REALCOLOR	,
	VP_VRAYBRIDGE_MULTIPASS_NORMAL		,
	VP_VRAYBRIDGE_MULTIPASS_BACKGROUND	,
	VP_VRAYBRIDGE_MULTIPASS_ALPHA		,
	VP_VRAYBRIDGE_MULTIPASS_COLOR		,
	VP_VRAYBRIDGE_MULTIPASS_RAWSHADING	,
	//VP_VRAYBRIDGE_MULTIPASS_WIRECOLOR	,
	VP_VRAYBRIDGE_MULTIPASS_MATTESHADOW	,
	VP_VRAYBRIDGE_MULTIPASS_TOTALLIGHT	,
	VP_VRAYBRIDGE_MULTIPASS_RAWTOTALLIGHT	,

	VP_VRAYBRIDGE_MULTIPASS_ZDEPTH_NEAR ,
	VP_VRAYBRIDGE_MULTIPASS_ZDEPTH_FAR	,

	VP_VRAYBRIDGE_GROUP_STANDARD		= 1750,
	VP_VRAYBRIDGE_GROUP_ADVANCED		,
	VP_VRAYBRIDGE_GROUP_DEPTH			,
	VP_VRAYBRIDGE_GROUP_ID				,

	// New Data
	VP_VRAYBRIDGE_HORIZONTAL_SPLIT		,

	VP_VRAYBRIDGE_IESPATH				,
	VP_VRAYBRIDGE_FAKEBITMAP			,

	// Info
	VP_VRAYBRIDGE_VERBOSE				= 1900,
	
	/// VrScene Export
	VP_VRAYBRIDGE_EXPORT_BUTTON			= 1950,

	
	//DR
	
	VP_VRAYBRIDGE_DR                    = 820,
	
	VP_VRAYBRIDGE_DR_ENABLEDR           = 19000,
	VP_VRAYBRIDGE_DR_ASSLAVE			,
	VP_VRAYBRIDGE_DR_STANDALONE			,
	VP_VRAYBRIDGE_DR_TYPE				,
	VP_VRAYBRIDGE_DR_TO_CINEMA_4D		,
	VP_VRAYBRIDGE_DR_TO_VRAY_STANDALONE	,
	VP_VRAYBRIDGE_DR_ASSETS_ON			,

	VP_VRAYBRIDGE_TEMP_PATH				,
	VP_VRAYBRIDGE_ASK_FILE_KNOWN_PATH	,

	VP_VRAYBRIDGE_RAW_IMAGE_SAVE		,
	VP_VRAYBRIDGE_RAW_IMAGE_DIR			,
	VP_VRAYBRIDGE_RAW_IMAGE_FILE		,

	VP_VRAYBRIDGE_USE_UVW_SWITCH		,
	VP_VRAYBRIDGE_USE_NEW_MAT_SYSTEM	,
    VP_VRAYBRIDGE_ALOW_VOLUME_RAFRACTION,

	VP_VRAYBRIDGE_CONVERT_C4D_BITMAP	= 19020,
	VP_VRAYBRIDGE_CONVERT_C4D_BITMAP_0	= 0,	
	VP_VRAYBRIDGE_CONVERT_C4D_BITMAP_1	= 1,	
	VP_VRAYBRIDGE_CONVERT_C4D_BITMAP_2	= 2,	
	VP_VRAYBRIDGE_CONVERT_C4D_BITMAP_3	= 3,	

	VP_VRAYBRIDGE_BACKE_C4D_SHADERS		= 19021,
	VP_VRAYBRIDGE_BACKE_C4D_SHADERS_0	= 0,
	VP_VRAYBRIDGE_BACKE_C4D_SHADERS_1	= 1,
	VP_VRAYBRIDGE_BACKE_C4D_SHADERS_2	= 2,
	VP_VRAYBRIDGE_BACKE_C4D_SHADERS_3	= 3,

	VP_VRAYBRIDGE_BACKE_RESOLUTION		= 19022,
	VP_VRAYBRIDGE_BACKE_RESOLUTION_0	= 0,
	VP_VRAYBRIDGE_BACKE_RESOLUTION_1	= 1,
	VP_VRAYBRIDGE_BACKE_RESOLUTION_2	= 2,
	VP_VRAYBRIDGE_BACKE_RESOLUTION_3	= 3,
	VP_VRAYBRIDGE_BACKE_RESOLUTION_4	= 4,
	VP_VRAYBRIDGE_BACKE_RESOLUTION_5	= 5,

	VP_VRAYBRIDGE_BACKE_RESOLUTION_10	= 10,
	VP_VRAYBRIDGE_BACKE_RESOLUTION_11	= 11,
	VP_VRAYBRIDGE_BACKE_RESOLUTION_12	= 12,
	VP_VRAYBRIDGE_BACKE_RESOLUTION_13	= 13,
	VP_VRAYBRIDGE_BACKE_RESOLUTION_14	= 14,
	VP_VRAYBRIDGE_BACKE_RESOLUTION_15	= 15,

	VP_VRAYBRIDGE_BACKE_RESOLUTION_20	= 20,
	VP_VRAYBRIDGE_BACKE_RESOLUTION_21	= 21,
	VP_VRAYBRIDGE_BACKE_RESOLUTION_22	= 22,
	VP_VRAYBRIDGE_BACKE_RESOLUTION_23	= 23,
	VP_VRAYBRIDGE_BACKE_RESOLUTION_24	= 24,
	VP_VRAYBRIDGE_BACKE_RESOLUTION_25	= 25,

	VP_VRAYBRIDGE_BAKE_GAMMA_CORRECTION = 19023,

	VP_VRAYBRIDGE_DR_ENABLEIP0          = 19100,
	VP_VRAYBRIDGE_DR_IPADDRESS0         = 19200,
	VP_VRAYBRIDGE_DR_PORT0				= 19300,
	VP_VRAYBRIDGE_DR_IPCOLOR0       = 19400,
	//VP_VRAYBRIDGE_DR_IPADDRESS4       = 19500,
	//VP_VRAYBRIDGE_DR_IPCOLOR0           = 19600,
	//VP_VRAYBRIDGE_DR_HOSTNAME0          = 19700,
	
	VP_VRAYBRIDGE_DR_GRUPPODINAMICO		= 19800,
	VP_VRAYBRIDGE_DR_GRUPPO_ON			,
	VP_VRAYBRIDGE_DR_GRUPPO_IP			,
	VP_VRAYBRIDGE_DR_GRUPPO_IP1			,
	VP_VRAYBRIDGE_DR_GRUPPO_IP2			,
	VP_VRAYBRIDGE_DR_GRUPPO_IP3			,
	VP_VRAYBRIDGE_DR_GRUPPO_IP4			,
	VP_VRAYBRIDGE_DR_GRUPPO_HOSTNAME	,
	VP_VRAYBRIDGE_DR_GRUPPO_COLOR		,	
	VP_VRAYBRIDGE_DR_4COLONNE 			,
	VP_VRAYBRIDGE_DR_SAVEIPLIST			,
	VP_VRAYBRIDGE_DR_LOADIPLIST			,
	VP_VRAYBRIDGE_DR_SLAVELISTLASTDGT	,
	VP_VRAYBRIDGE_DR_SAVEIPLISTFLAG		,
	VP_VRAYBRIDGE_DR_ADD_ALL_NET		,

	VP_VRAYBRIDGE_DR_GETHOSTNAME		= 19900,

	POINTERBASEDOC					= 2000,
	GLOBALILLUM						= 2001,


	VP_VRAYBRIDGE_TRANSLATOR_GROUP		= 3000,
	VP_VRAYBRIDGE_TR_FILE_NAME			,
	VP_VRAYBRIDGE_TR_RENDER				,
	VP_VRAYBRIDGE_TR_EXPORT				,
	VP_VRAYBRIDGE_TR_SEPARATE_FILES		,
	VP_VRAYBRIDGE_TR_EXPORT_LIGHT		,
	VP_VRAYBRIDGE_TR_EXPORT_NODES		,
	VP_VRAYBRIDGE_TR_EXPORT_GEOM		,
	VP_VRAYBRIDGE_TR_EXPORT_MATS		,
	VP_VRAYBRIDGE_TR_EXPORT_TEXTURES	,
	VP_VRAYBRIDGE_TR_EXPORT_BITMAPS		,
	VP_VRAYBRIDGE_TR_PER_FRAME			,
	VP_VRAYBRIDGE_TR_MESH_HEX			,
	VP_VRAYBRIDGE_TR_TRANS_HEX			,
	VP_VRAYBRIDGE_TR_COMPRESSED			,
	
	VP_VRAYBRIDGE_BUCKETDESIGN						= 2319960, //why do we use this strange big number here ?
	VP_VRAYBRIDGE_BUCKETBORDER								,
	VP_VRAYBRIDGE_BUCKETGRAD_TOP_MASTER		,
	VP_VRAYBRIDGE_BUCKETGRAD_BOT_MASTER	,
	VP_VRAYBRIDGE_BUCKETGRAD_TOP1_SLAVE	,
	VP_VRAYBRIDGE_BUCKETGRAD_BOT1_SLAVE	,
	VP_VRAYBRIDGE_BUCKETGRAD_TOP2_SLAVE	,
	VP_VRAYBRIDGE_BUCKETGRAD_BOT2_SLAVE   	,
	VP_VRAYBRIDGE_BUCKET_TRASPARENCY					,
	VP_VRAYBRIDGE_BUCKETGRAD_CLIENT_PREVIEW	,
	VP_VRAYBRIDGE_BUCKETGRAD_SLAVE1_PREVIEW	,
	VP_VRAYBRIDGE_BUCKETGRAD_SLAVE2_PREVIEW	,
	VP_VRAYBRIDGE_BUCKET_MASTER_TITLE		,
	VP_VRAYBRIDGE_BUCKET_SLAVE_TITLE			,
	VP_VRAYBRIDGE_BUCKET_RAMPON					,
	VP_VRAYBRIDGE_BUCKET_OLD_STYLE				,
	VP_VRAYBRIDGE_BUCKET_TRASPARENCY_RAMP ,
	VP_VRAYBRIDGE_BUCKET_SAVE_SETTINGS 			,
	VP_VRAYBRIDGE_BUCKET_LOAD_SETTINGS			,


};

#endif
