CONTAINER VPvraybridge
{
	NAME VPvraybridge;

	//DEFAULT 1;
	
	GROUP
	{
		STRING VP_VRAYBRIDGE_TITLEBAR {ANIM OFF; CUSTOMGUI VRAYBAR_GUI;}
	}
	
	INCLUDE VPbase;

	/// OPTIONS ///

	GROUP VP_VRAYBRIDGE_OPTIONS
	{
		DEFAULT 1;

		GROUP VP_VRAYBRIDGE_GEOMETRY
		{
			DEFAULT 1;

			//BOOL VP_VRAYBRIDGE_BETA_C4DSHADERS_NEWALLOCATED_FROM_VRSCENE {}
			//BOOL VP_VRAYBRIDGE_USE_APPROXIMATED_OGLPREVIEW {}
			BOOL VP_VRAYBRIDGE_DISP		{}
			
			SEPARATOR {}
			
			LONG VP_VRAYBRIDGE_MSCALE
			{
				CYCLE
				{
					VP_VRAYBRIDGE_MSCALE_0;
					VP_VRAYBRIDGE_MSCALE_1;
					VP_VRAYBRIDGE_MSCALE_2;
					VP_VRAYBRIDGE_MSCALE_3;
					VP_VRAYBRIDGE_MSCALE_4;
					VP_VRAYBRIDGE_MSCALE_5;
				}
			}
		}

		SEPARATOR {LINE;}

		GROUP VP_VRAYBRIDGE_LIGHTING
		{
			DEFAULT 1;

			GROUP
			{
				LAYOUTGROUP; COLUMNS 3;
				GROUP
				{
					BOOL VP_VRAYBRIDGE_LIGHTS	{}
					LONG VP_VRAYBRIDGE_DEFAULTLIGHTS
					{
						CYCLE
						{
							VP_VRAYBRIDGE_DEFAULTLIGHTS_0;
							VP_VRAYBRIDGE_DEFAULTLIGHTS_1;
							VP_VRAYBRIDGE_DEFAULTLIGHTS_2;
						}
					}
					REAL VP_VRAYBRIDGE_PHOTOSCALE {MIN 0.001; STEP 0.001;}
				}
				GROUP
				{
					BOOL VP_VRAYBRIDGE_SHADOWS	{}
					BOOL VP_VRAYBRIDGE_GIONLY	{}
				}
				GROUP
				{
					BOOL VP_VRAYBRIDGE_C4DSHADOWS	{}
				}
			}
			//BOOL VP_VRAYBRIDGE_HIDDENLIGHTS	{HIDDEN;}
		}

		SEPARATOR {LINE;}

		GROUP VP_VRAYBRIDGE_INDIRECT
		{
			DEFAULT 1;

			BOOL VP_VRAYBRIDGE_NORENDER	{}
		}

		SEPARATOR {LINE;}

		GROUP VP_VRAYBRIDGE_MATERIALS
		{
			DEFAULT	1;

			GROUP
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					BOOL VP_VRAYBRIDGE_REFLREFR	{}
					
					BOOL VP_VRAYBRIDGE_LIMITDEPTH {}
					
					BOOL VP_VRAYBRIDGE_MAPS	{}					
					
					LONG VP_VRAYBRIDGE_MAXTRANSPLEVELS	{MIN 0;}				
					SEPARATOR {}

					BOOL VP_VRAYBRIDGE_GLOSSY {}

					//BOOL VP_VRAYBRIDGE_OVERRIDEMTL {}
					//LINK VP_VRAYBRIDGE_OVERRIDELINK {}
					
					//SEPARATOR {}
			
					COLOR VP_VRAYBRIDGE_OVERRIDECLR {}
					SEPARATOR {}

				}
				GROUP
				{
					STATICTEXT VP_VRAYBRIDGE_FAKEPARAM1 {}
					
					LONG VP_VRAYBRIDGE_MAXDEPTH {MIN 0;}
					
					BOOL VP_VRAYBRIDGE_FILTERMAPS	{}	
					
					REAL VP_VRAYBRIDGE_TRANSPCUTOFF	{UNIT REAL; MIN 0.001; STEP 0.001;}

					SEPARATOR {}
					SEPARATOR {}
					SEPARATOR {}
					SEPARATOR {}
				}		
			}
			GROUP
			{
				SEPARATOR {}//SEPARATOR {LINE;}
				BOOL VP_VRAYBRIDGE_OVERRIDEMTL {}
				LINK VP_VRAYBRIDGE_OVERRIDELINK {}
				
				SEPARATOR {}//SEPARATOR {LINE;}
				BOOL VP_VRAYBRIDGE_OTF_CONVERT_C4DMAT {}
				SEPARATOR {}

				BOOL VP_VRAYBRIDGE_USE_APPROXIMATED_OGLPREVIEW {}
				SEPARATOR { LINE; }
				BOOL VP_VRAYBRIDGE_USE_NEW_MAT_SYSTEM {}
                SEPARATOR { LINE; }
				//BOOL VP_VRAYBRIDGE_ALOW_VOLUME_RAFRACTION {}
				SEPARATOR { LINE; }
				LONG VP_VRAYBRIDGE_CONVERT_C4D_BITMAP {
					CYCLE {
						VP_VRAYBRIDGE_CONVERT_C4D_BITMAP_0;
						VP_VRAYBRIDGE_CONVERT_C4D_BITMAP_1;
						VP_VRAYBRIDGE_CONVERT_C4D_BITMAP_2;
					}
				}
				LONG VP_VRAYBRIDGE_BACKE_C4D_SHADERS {
					CYCLE {
						VP_VRAYBRIDGE_BACKE_C4D_SHADERS_0;
						VP_VRAYBRIDGE_BACKE_C4D_SHADERS_1;
						VP_VRAYBRIDGE_BACKE_C4D_SHADERS_2;
						VP_VRAYBRIDGE_BACKE_C4D_SHADERS_3;
					}
				}

				LONG VP_VRAYBRIDGE_BACKE_RESOLUTION	{
					CYCLE {
						VP_VRAYBRIDGE_BACKE_RESOLUTION_0;
						VP_VRAYBRIDGE_BACKE_RESOLUTION_1;
						VP_VRAYBRIDGE_BACKE_RESOLUTION_2;
						VP_VRAYBRIDGE_BACKE_RESOLUTION_3;
						VP_VRAYBRIDGE_BACKE_RESOLUTION_4;
						//VP_VRAYBRIDGE_BACKE_RESOLUTION_5;
						-1;
						VP_VRAYBRIDGE_BACKE_RESOLUTION_10;	
						VP_VRAYBRIDGE_BACKE_RESOLUTION_11;	
						VP_VRAYBRIDGE_BACKE_RESOLUTION_12;	
						VP_VRAYBRIDGE_BACKE_RESOLUTION_13;	
						VP_VRAYBRIDGE_BACKE_RESOLUTION_14;	
						//VP_VRAYBRIDGE_BACKE_RESOLUTION_15;	
						-1;
						VP_VRAYBRIDGE_BACKE_RESOLUTION_20;	
						VP_VRAYBRIDGE_BACKE_RESOLUTION_21;
						VP_VRAYBRIDGE_BACKE_RESOLUTION_22;
						VP_VRAYBRIDGE_BACKE_RESOLUTION_23;	
						VP_VRAYBRIDGE_BACKE_RESOLUTION_24;	
						VP_VRAYBRIDGE_BACKE_RESOLUTION_25;	
					}
				}
				BOOL VP_VRAYBRIDGE_BAKE_GAMMA_CORRECTION {}

			}
		}

		SEPARATOR {LINE;}

		GROUP VP_VRAYBRIDGE_SECONDARYRAYS
		{
			DEFAULT 1;

			REAL VP_VRAYBRIDGE_RAYSBIAS {UNIT REAL; MIN 0; STEP 0.001;}
			BOOL VP_VRAYBRIDGE_BACKCULL {}
		}

		SEPARATOR {LINE;}

		GROUP VP_VRAYBRIDGE_VOLUMETRICS
		{
			HIDDEN ;

			DEFAULT 1;

			GROUP 
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP 
				{
					BOOL VP_VRAYBRIDGE_ENABLE_VOLUMETRICS {}
				}
				GROUP 
				{
					LONG VP_VRAYBRIDGE_VOLUMERAYDEPTH {MIN 1; MAX 24; HIDDEN;}
				}
			}
		}

		GROUP VP_VRAYBRIDGE_MISCELLANEUS
		{
			DEFAULT 1;

			BOOL VP_VRAYBRIDGE_ENVOPTIMIZED {}

			BOOL VP_VRAYBRIDGE_LOWPRIORITY {}
			
			//BOOL VP_VRAYBRIDGE_OLDAA {}


			SEPARATOR {}

			BOOL VP_VRAYBRIDGE_STAMP				{}
			BOOL	VP_VRAYBRDIGE_STAMP_PRIMITIVE	{}
			STRING	VP_VRAYBRIDGE_STAMP_STRING		{}

			//BOOL VP_VRAYBRIDGE_SAVESCENE {}
			//FILENAME VP_VRAYBRIDGE_SCENEFILE {SAVE;}
			SEPARATOR {}
			BOOL VP_VRAYBRIDGE_VERBOSE {}

			SEPARATOR {}
			//BUTTON VP_VRAYBRIDGE_EXPORT_BUTTON {}
		}

		//GROUP VP_VRAYBRIDGE_VFB
		//{
			//BOOL VP_VRAYBRIDGE_VFB_ON {}
		//}
	}



	/// ANTIALIASING ///

	GROUP VP_VRAYBRIDGE_ANTIALIASING
	{
		GROUP VP_VRAYBRIDGE_IMGSAMPLER
		{
			DEFAULT 1;

			LONG VP_VRAYBRIDGE_SAMPLER
			{
				CYCLE
				{
					VP_VRAYBRIDGE_SAMPLER_FIXED;
					VP_VRAYBRIDGE_SAMPLER_ADAPTIVEQMC;
					VP_VRAYBRIDGE_SAMPLER_ADAPTIVESUBD;
				}
			}
		}

		SEPARATOR {LINE;}

		GROUP VP_VRAYBRIDGE_IMGFILTER
		{
			DEFAULT 1;

			GROUP
			{
				LAYOUTGROUP; COLUMNS 3;
				GROUP
				{
					BOOL VP_VRAYBRIDGE_FILTERON	{}
					REAL VP_VRAYBRIDGE_FILTERSIZE {UNIT REAL; MIN 0.1; STEP 0.01;}
				}
				GROUP
				{
					LONG VP_VRAYBRIDGE_FILTER
					{
						CYCLE
						{
							VP_VRAYBRIDGE_FILTER_BOX;
							VP_VRAYBRIDGE_FILTER_DISC;
							VP_VRAYBRIDGE_FILTER_TRIANGLE;
							VP_VRAYBRIDGE_FILTER_WELCH;
							VP_VRAYBRIDGE_FILTER_PARZEN;
							VP_VRAYBRIDGE_FILTER_HANN;
							VP_VRAYBRIDGE_FILTER_BLACKMAN;
							VP_VRAYBRIDGE_FILTER_LANCZOS;
							VP_VRAYBRIDGE_FILTER_SINC;
							VP_VRAYBRIDGE_FILTER_MITCHELL;
							VP_VRAYBRIDGE_FILTER_AREA;
							VP_VRAYBRIDGE_FILTER_CATMULL;
							VP_VRAYBRIDGE_FILTER_GAUSSIAN;

						}
					}
					REAL VP_VRAYBRIDGE_BLURSIZE	{UNIT REAL; MIN 0; STEP 0.01;}
				}
				GROUP
				{
					STATICTEXT VP_VRAYBRIDGE_FAKEPARAM2 {}
					REAL VP_VRAYBRIDGE_RINGSIZE	{UNIT REAL; MIN 0; STEP 0.01;}
				}
			}
		}

		SEPARATOR {LINE;}

		GROUP VP_VRAYBRIDGE_TYPEFIXED
		{
			DEFAULT 1; HIDDEN;

			LONG VP_VRAYBRIDGE_SUBDIV1	{MIN 1;}
		}

		SEPARATOR {LINE;}

		GROUP VP_VRAYBRIDGE_TYPEQMC
		{
			DEFAULT 1; HIDDEN;

			GROUP
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					LONG VP_VRAYBRIDGE_MINSUBDIV {MIN 1;}
					BOOL VP_VRAYBRIDGE_LOCKTHRESHOLD {}
					BOOL VP_VRAYBRIDGE_DMCSHOWSAMPLES {}
				}
				GROUP
				{
					LONG VP_VRAYBRIDGE_MAXSUBDIV {MIN 1;}
					REAL VP_VRAYBRIDGE_THRESHOLD {MIN 0; STEP 0.01;}
				}
			}
		}

		SEPARATOR {LINE;}

		GROUP VP_VRAYBRIDGE_TYPEADAPTIVE
		{
			DEFAULT 1; HIDDEN;

			GROUP
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					LONG VP_VRAYBRIDGE_MINRATE	{MIN -3; MAX 8;}
					BOOL VP_VRAYBRIDGE_JITTER	{}
					BOOL VP_VRAYBRIDGE_AAEDGES	{}
					BOOL VP_VRAYBRIDGE_AANORMALS {}
					BOOL VP_VRAYBRIDGE_AAZVALUE {}
					BOOL VP_VRAYBRIDGE_ADAPTSHOWSAMPLES {}
				}
				GROUP
				{
					LONG VP_VRAYBRIDGE_MAXRATE	{MIN -3; MAX 8;}
					REAL VP_VRAYBRIDGE_THRESH	{MIN 0; STEP 0.01;}
					BOOL VP_VRAYBRIDGE_AAMTLID {}
					REAL VP_VRAYBRIDGE_NMLTHRESH {MIN 0; MAX 1; STEP 0.01;}
					REAL VP_VRAYBRIDGE_ZTHRESH {MIN 0; MAX 1; STEP 0.01;}
				}
			}
		}
	}


	/// QMC SAMPLER ///

	GROUP VP_VRAYBRIDGE_QMCSAMPLER
	{
		GROUP
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					REAL VP_VRAYBRIDGE_QMCSAMPLER_ADAPTIVE {MIN 0; MAX 1; STEP 0.1;}
					REAL VP_VRAYBRIDGE_QMCSAMPLER_ADAPTTHR {MIN 0; MAX 1; STEP 0.1;}
					BOOL VP_VRAYBRIDGE_QMCSAMPLER_TIMEDEP {}
				}
				GROUP
				{
					LONG VP_VRAYBRIDGE_QMCSAMPLER_ADAPSAMP {MIN 2; MAX 1000;}
					REAL VP_VRAYBRIDGE_QMCSAMPLER_SUBDIVMULT {MIN 0; STEP 0.1;}
				}
			}
	}


	/// GI ///

	GROUP VP_VRAYBRIDGE_GI
	{	
		GROUP
		{
			GROUP 
			{
				COLUMNS 2;
				
				BOOL VP_VRAYBRIDGE_GI_ON {}
				//LONG VP_VRAYBRIDGE_GI_PRESETS {}
			}
		   
			SEPARATOR {LINE;}
			GROUP VP_VRAYBRIDGE_GI_PRESETS_GROUP
			{
				//COLUMNS 2;
				STATICTEXT { NAME VP_VRAYBRIDGE_GI_PRESETS_TEXT01; }
			}
			SEPARATOR {LINE;}
			GROUP 
			{
				COLUMNS 2;
			   
				BUTTON VP_VRAYBRIDGE_SAVEGISETTINGS {}  
				STRING VP_VRAYBRIDGE_LOADGISETTINGS {SCALE_H;}
			}
		}

		SEPARATOR {LINE;}

		GROUP VP_VRAYBRIDGE_GIGENERAL
		{
			DEFAULT 0;

			BOOL VP_VRAYBRIDGE_GINETRENDER {}
			
			SEPARATOR {}

			GROUP
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					LONG VP_VRAYBRIDGE_GIANIMSTART {MIN 0;}
				}
				GROUP
				{
					LONG VP_VRAYBRIDGE_GIANIMEND {MIN 0;}
				}
			}
			
			SEPARATOR {}
			
			GROUP
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					BOOL VP_VRAYBRIDGE_GIUSERAYDISTANCE {PARENTID VP_VRAYBRIDGE_GI;PARENTID VP_VRAYBRIDGE_GI;}
				}
				GROUP
				{
					REAL VP_VRAYBRIDGE_GIRAYDISTANCE {UNIT METER; MIN 0; STEP 0.1;PARENTID VP_VRAYBRIDGE_GI;PARENTID VP_VRAYBRIDGE_GI;}
				}
			}

			SEPARATOR {LINE;}

			GROUP VP_VRAYBRIDGE_GICAUSTICS
			{
				DEFAULT 1;

				BOOL VP_VRAYBRIDGE_GI_REFLECTIVE	{PARENTID VP_VRAYBRIDGE_GI;}
				BOOL VP_VRAYBRIDGE_GI_REFRACTIVE	{PARENTID VP_VRAYBRIDGE_GI;}
			}

			SEPARATOR {LINE;}

			GROUP VP_VRAYBRIDGE_POSTPROC
			{
				DEFAULT 1;

				REAL VP_VRAYBRIDGE_GI_SATURATION	{UNIT REAL; MIN 0; STEP 0.01;PARENTID VP_VRAYBRIDGE_GI;}
				REAL VP_VRAYBRIDGE_GI_CONTRAST		{UNIT REAL; MIN 0; STEP 0.01;PARENTID VP_VRAYBRIDGE_GI;}
				REAL VP_VRAYBRIDGE_GI_CONTRASTBASE	{UNIT REAL; MIN 0; STEP 0.01;PARENTID VP_VRAYBRIDGE_GI;}
				BOOL VP_VRAYBRIDGE_GI_SAVEPERFRAME	{ HIDDEN;PARENTID VP_VRAYBRIDGE_GI;}
			}

			SEPARATOR {LINE;}

			GROUP VP_VRAYBRIDGE_PRIMARYBOUNCE
			{
				DEFAULT 1;

				GROUP
				{
					LAYOUTGROUP; COLUMNS 2;
					GROUP
					{
						REAL VP_VRAYBRIDGE_GIENGINE1_MULTIPLIER {UNIT REAL; STEP 0.01;PARENTID VP_VRAYBRIDGE_GI;}
					}
					GROUP
					{
						LONG VP_VRAYBRIDGE_GIENGINE1
						{
							PARENTID VP_VRAYBRIDGE_GI;
							CYCLE
							{
								VP_VRAYBRIDGE_GIENGINE_IRRADIANCE;
								VP_VRAYBRIDGE_GIENGINE_PHOTON1;
								VP_VRAYBRIDGE_GIENGINE_QUASIMC1;
								VP_VRAYBRIDGE_GIENGINE_LIGHTCACHE1;
								//VP_VRAYBRIDGE_GIENGINE_SPHERICAL;
							}
						}
					}
				}
			}

			SEPARATOR {LINE;}

			GROUP VP_VRAYBRIDGE_SECONDARYBOUNCE
			{
				DEFAULT 1;

				GROUP 
				{
					LAYOUTGROUP; COLUMNS 2;
					GROUP 
					{
						REAL VP_VRAYBRIDGE_MULTIPLIER2 {UNIT REAL; STEP 0.01;PARENTID VP_VRAYBRIDGE_GI;}
					}
					GROUP 
					{
						LONG VP_VRAYBRIDGE_GIENGINE2
						{
							PARENTID VP_VRAYBRIDGE_GI;
							CYCLE
							{
								VP_VRAYBRIDGE_GIENGINE_NONE;
								VP_VRAYBRIDGE_GIENGINE_PHOTON2;
								VP_VRAYBRIDGE_GIENGINE_QUASIMC2;
								VP_VRAYBRIDGE_GIENGINE_LIGHTCACHE2;
							}
						}
					}
				}
			}
			
			SEPARATOR {LINE;}
			
			GROUP VP_VRAYBRIDGE_AO
			{
				DEFAULT 1;
				
				//GROUP
				//{
					BOOL VP_VRAYBRIDGE_AO_ON {PARENTID VP_VRAYBRIDGE_GI;}
					REAL VP_VRAYBRIDGE_AO_AMOUNT {MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;PARENTID VP_VRAYBRIDGE_GI;}
					REAL VP_VRAYBRIDGE_AO_RADIUS {MIN 0; STEP 0.1; MAXSLIDER 100; CUSTOMGUI REALSLIDER;PARENTID VP_VRAYBRIDGE_GI;}
					LONG VP_VRAYBRIDGE_AO_SUBDIVS {MIN 0; MAXSLIDER 32; CUSTOMGUI LONGSLIDER;PARENTID VP_VRAYBRIDGE_GI;}				
				//}
			}	
		}

		SEPARATOR {LINE;}

		/// IRRADIANCE MAP ///

		GROUP VP_VRAYBRIDGE_IRRADIANCE
		{
			DEFAULT 0; HIDDEN;

			GROUP VP_VRAYBRIDGE_IRRADBASICPARAMS
			{
				DEFAULT 1;

				GROUP
				{
					LAYOUTGROUP; COLUMNS 2;
					GROUP
					{
						LONG VP_VRAYBRIDGE_IRRADMINRATE	{MIN -100; MAX 100;PARENTID VP_VRAYBRIDGE_GI;}
						LONG VP_VRAYBRIDGE_IRRADMAXRATE	{MIN -100; MAX 100;PARENTID VP_VRAYBRIDGE_GI;}
						LONG VP_VRAYBRIDGE_IRRADSUBDIV	{MIN 1; MAX 1000;PARENTID VP_VRAYBRIDGE_GI;}
						LONG VP_VRAYBRIDGE_IRRADINTSAMPLES	{MIN 1;PARENTID VP_VRAYBRIDGE_GI;}
					}
					GROUP
					{
						REAL VP_VRAYBRIDGE_IRRADINTTHRESH	{MIN 0; STEP 0.01;PARENTID VP_VRAYBRIDGE_GI;}
						REAL VP_VRAYBRIDGE_IRRADNORMTHRESH	{MIN 0; STEP 0.01;PARENTID VP_VRAYBRIDGE_GI;}
						REAL VP_VRAYBRIDGE_IRRADDISTTHRESH	{MIN 0; STEP 0.01;PARENTID VP_VRAYBRIDGE_GI;}
						LONG VP_VRAYBRIDGE_IRRADINTFRAMES	{MIN 1;PARENTID VP_VRAYBRIDGE_GI;}
					}
				}
			}

			SEPARATOR {LINE;}

			GROUP VP_VRAYBRIDGE_IRRADOPTIONS
			{
				DEFAULT 1;

				BOOL VP_VRAYBRIDGE_IRRADSHOWCALC	{PARENTID VP_VRAYBRIDGE_GI;}
				BOOL VP_VRAYBRIDGE_IRRADSHOWCALCDIRECT {PARENTID VP_VRAYBRIDGE_GI;}
				BOOL VP_VRAYBRIDGE_IRRADSHOWSAMPLES {PARENTID VP_VRAYBRIDGE_GI;}
				BOOL VP_VRAYBRIDGE_IRRADCAMPATH {PARENTID VP_VRAYBRIDGE_GI;}

				SEPARATOR {}

				LONG VP_VRAYBRIDGE_IRRADPREVISMODE
				{
					PARENTID VP_VRAYBRIDGE_GI;
					CYCLE
					{
						VP_VRAYBRIDGE_IRRADPREVISMODE_0;
						VP_VRAYBRIDGE_IRRADPREVISMODE_1;
					}
				}	
			}

			SEPARATOR {LINE;}

			GROUP VP_VRAYBRIDGE_IRRADDETAIL
			{
				DEFAULT 1;

				GROUP
				{
					LAYOUTGROUP; COLUMNS 2;
					GROUP
					{
						BOOL VP_VRAYBRIDGE_IRRADDETAILON {PARENTID VP_VRAYBRIDGE_GI;}
						LONG VP_VRAYBRIDGE_IRRADDETAILSCALE
						{
							PARENTID VP_VRAYBRIDGE_GI;
							CYCLE
							{
								VP_VRAYBRIDGE_IRRADDETAILSCALE_SCREEN;
								VP_VRAYBRIDGE_IRRADDETAILSCALE_WORLD;
							}
						}
						REAL VP_VRAYBRIDGE_IRRADDETAILMULT {MIN 0; STEP 0.1;PARENTID VP_VRAYBRIDGE_GI;}
					}
					GROUP
					{
						REAL VP_VRAYBRIDGE_IRRADDETAILRAD {HIDDEN; MIN 0; STEP 0.01;PARENTID VP_VRAYBRIDGE_GI;}
						REAL VP_VRAYBRIDGE_IRRADDETAILRAD2 {HIDDEN; UNIT METER; MIN 0; STEP 0.01;PARENTID VP_VRAYBRIDGE_GI;}
					}
				}
			}

			SEPARATOR {LINE;}

			GROUP VP_VRAYBRIDGE_IRRADADVANCED
			{
				DEFAULT 1;

				GROUP
				{
					LAYOUTGROUP; COLUMNS 2;

					GROUP
					{			
						LONG VP_VRAYBRIDGE_IRRADINTERPTYPE
						{
							PARENTID VP_VRAYBRIDGE_GI;
							CYCLE
							{
								VP_VRAYBRIDGE_IRRADINTERPTYPE_0;
								VP_VRAYBRIDGE_IRRADINTERPTYPE_1;
								VP_VRAYBRIDGE_IRRADINTERPTYPE_2;
								VP_VRAYBRIDGE_IRRADINTERPTYPE_3;
							}
						}

						LONG VP_VRAYBRIDGE_IRRADSAMPLELOOKUP
						{
							PARENTID VP_VRAYBRIDGE_GI;
							CYCLE
							{
								VP_VRAYBRIDGE_IRRADSAMPLELOOKUP_0;
								VP_VRAYBRIDGE_IRRADSAMPLELOOKUP_1;
								VP_VRAYBRIDGE_IRRADSAMPLELOOKUP_2;
								VP_VRAYBRIDGE_IRRADSAMPLELOOKUP_3;
							}
						}
					
						LONG VP_VRAYBRIDGE_IRRADCALCINTSAMPLES {MIN 1; MAX 1000;PARENTID VP_VRAYBRIDGE_GI;}
					}

					GROUP
					{
						BOOL VP_VRAYBRIDGE_IRRADMIXEDRES {PARENTID VP_VRAYBRIDGE_GI;}
						BOOL VP_VRAYBRIDGE_IRRADRANDOMIZE {PARENTID VP_VRAYBRIDGE_GI;}
						BOOL VP_VRAYBRIDGE_IRRADCHECKSAMPLE {PARENTID VP_VRAYBRIDGE_GI;}
					}
				}
			}

			SEPARATOR {LINE;}

			GROUP VP_VRAYBRIDGE_IRRADMODE
			{
				DEFAULT 1;

				GROUP
				{
					COLUMNS 2;

					LONG VP_VRAYBRIDGE_IRRADMAPMODE
					{
						PARENTID VP_VRAYBRIDGE_GI;
						CYCLE
						{
							VP_VRAYBRIDGE_IRRADMAPMODE_0;
							VP_VRAYBRIDGE_IRRADMAPMODE_1;
							VP_VRAYBRIDGE_IRRADMAPMODE_2;
							VP_VRAYBRIDGE_IRRADMAPMODE_3;
							VP_VRAYBRIDGE_IRRADMAPMODE_4;
							VP_VRAYBRIDGE_IRRADMAPMODE_5;
							VP_VRAYBRIDGE_IRRADMAPMODE_6;
							VP_VRAYBRIDGE_IRRADMAPMODE_7;
						}
					}
					BUTTON VP_VRAYBRIDGE_SAVEIR {}
				}
				SEPARATOR {}
				FILENAME VP_VRAYBRIDGE_IRRADFILE2 {HIDDEN;PARENTID VP_VRAYBRIDGE_GI;}
				STRING VP_VRAYBRIDGE_IRRADFILE {HIDDEN;PARENTID VP_VRAYBRIDGE_GI;}
				BOOL VP_VRAYBRIDGE_IRRADSAVEBUTTON {HIDDEN;}
				STRING VP_VRAYBRIDGE_IRRADSAVEFILE {HIDDEN;}
				FILENAME VP_VRAYBRIDGE_IRRADSAVEFILE2 {SAVE; HIDDEN;}
			}

			SEPARATOR {LINE;}

			GROUP VP_VRAYBRIDGE_IRRADONRENDEREND
			{
				DEFAULT 1;

				BOOL VP_VRAYBRIDGE_IRRADNODELETE {PARENTID VP_VRAYBRIDGE_GI;}
				BOOL VP_VRAYBRIDGE_IRRADAUTOSAVEMAP {}
				STRING VP_VRAYBRIDGE_IRRADAUTOSAVEFILE {HIDDEN;}
				FILENAME VP_VRAYBRIDGE_IRRADAUTOSAVEFILE2 {SAVE; HIDDEN;}
				BOOL VP_VRAYBRIDGE_IRRADSWITCHSAVEMAP {HIDDEN;PARENTID VP_VRAYBRIDGE_GI;}
				
			}
		}

		SEPARATOR {LINE;}

		/// QMC GI ///

		GROUP VP_VRAYBRIDGE_QMCGI
		{
			DEFAULT 0; HIDDEN;

			GROUP
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					LONG VP_VRAYBRIDGE_QMCSUBDIV {MIN 1;PARENTID VP_VRAYBRIDGE_GI;}
				}
				GROUP
				{
					LONG VP_VRAYBRIDGE_QMCDEPTH {MIN 1; MAX 500;PARENTID VP_VRAYBRIDGE_GI;}
				}
			}
		}

		SEPARATOR {LINE;}

		/// GLOBAL PHOTON MAP ///

		GROUP VP_VRAYBRIDGE_PHOTONMAP
		{
			DEFAULT 0; HIDDEN;

			GROUP
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					LONG VP_VRAYBRIDGE_PHOTONBOUNCES {MIN 0; MAX 100;PARENTID VP_VRAYBRIDGE_GI;}
					BOOL VP_VRAYBRIDGE_AUTODIST {PARENTID VP_VRAYBRIDGE_GI;}
					REAL VP_VRAYBRIDGE_SEARCHDIST {UNIT METER; MIN 0; STEP 0.1;PARENTID VP_VRAYBRIDGE_GI;}
					LONG VP_VRAYBRIDGE_MAXPHOTONS {MIN 0;PARENTID VP_VRAYBRIDGE_GI;}
					REAL VP_VRAYBRIDGE_PHOTONMULT {MIN 0; STEP 0.01;PARENTID VP_VRAYBRIDGE_GI;}
					REAL VP_VRAYBRIDGE_MAXDENSITY {MIN 0; STEP 1;PARENTID VP_VRAYBRIDGE_GI;}
					BOOL VP_VRAYBRIDGE_PHOTONSHOWCALC {PARENTID VP_VRAYBRIDGE_GI;}
				}
				GROUP
				{
					BOOL VP_VRAYBRIDGE_PHOTONPREFILTER	{PARENTID VP_VRAYBRIDGE_GI;}
					LONG VP_VRAYBRIDGE_PHOTONINTSAMPLES	{MIN 1;PARENTID VP_VRAYBRIDGE_GI;}
					BOOL VP_VRAYBRIDGE_CONVEXHULL {PARENTID VP_VRAYBRIDGE_GI;}
					BOOL VP_VRAYBRIDGE_STOREDIRECT {PARENTID VP_VRAYBRIDGE_GI;}
					REAL VP_VRAYBRIDGE_PHOTONRETRACETHRESHOLD {MIN 0; STEP 0.01;PARENTID VP_VRAYBRIDGE_GI;}
					LONG VP_VRAYBRIDGE_PHOTONRETRACEBOUNCES {MIN 0; MAX 100;PARENTID VP_VRAYBRIDGE_GI;}
				}
			}

			SEPARATOR {}

			GROUP VP_VRAYBRIDGE_PHOTONMODE
			{
				DEFAULT 1;
				
				GROUP
				{
					LAYOUTGROUP; COLUMNS 2;
					GROUP
					{
						LONG VP_VRAYBRIDGE_PHOTONMAPMODE
						{
							PARENTID VP_VRAYBRIDGE_GI;
							CYCLE
							{
								VP_VRAYBRIDGE_PHOTONMAPMODE_0;
								VP_VRAYBRIDGE_PHOTONMAPMODE_1;
							}
						}
					}
					GROUP
					{
						BUTTON VP_VRAYBRIDGE_SAVEPM {}
					}
				}

				STRING VP_VRAYBRIDGE_PHOTONMAPFILE {HIDDEN;}
				FILENAME VP_VRAYBRIDGE_PHOTONMAPFILE2 {HIDDEN;}
			}

			SEPARATOR {}

			GROUP VP_VRAYBRIDGE_PHOTONONRENDEREND
			{
				DEFAULT 1;

				BOOL VP_VRAYBRIDGE_PHOTONNODELETE {PARENTID VP_VRAYBRIDGE_GI;}
				BOOL VP_VRAYBRIDGE_PHOTONAUTOSAVEMAP {}
				STRING VP_VRAYBRIDGE_PHOTONAUTOSAVEFILE {HIDDEN;}
				FILENAME VP_VRAYBRIDGE_PHOTONAUTOSAVEFILE2 {SAVE;}
			}
		}

		SEPARATOR {LINE;}

		/// LIGHT CACHE ///
		GROUP VP_VRAYBRIDGE_LIGHTCACHE
		{
			DEFAULT 0; HIDDEN;

			GROUP VP_VRAYBRIDGE_LIGHTCACHE_CALCULATION
			{
				DEFAULT 1;

				GROUP
				{
					LAYOUTGROUP; COLUMNS 2;
					GROUP
					{
						BOOL VP_VRAYBRIDGE_LIGHTCACHE_OVERRIDE {PARENTID VP_VRAYBRIDGE_GI;}
						
						SEPARATOR {}
						
						LONG VP_VRAYBRIDGE_LIGHTCACHE_SUBDIV {MIN 1;PARENTID VP_VRAYBRIDGE_GI;}
						REAL VP_VRAYBRIDGE_LIGHTCACHE_SAMPLESIZE {MIN 0; STEP 0.01; HIDDEN;PARENTID VP_VRAYBRIDGE_GI;}
						REAL VP_VRAYBRIDGE_LIGHTCACHE_SAMPLESIZE2 {UNIT METER; MIN 0; STEP 0.01; HIDDEN;PARENTID VP_VRAYBRIDGE_GI;}
						LONG VP_VRAYBRIDGE_LIGHTCACHE_SCALE
						{
							PARENTID VP_VRAYBRIDGE_GI;
							CYCLE
							{
								VP_VRAYBRIDGE_LIGHTCACHE_SCALE_0;
								VP_VRAYBRIDGE_LIGHTCACHE_SCALE_1;
							}
						}
						
						SEPARATOR {}
						
						LONG VP_VRAYBRIDGE_LIGHTCACHE_PASSES {MIN 1; MAX 256;PARENTID VP_VRAYBRIDGE_GI;}
						LONG VP_VRAYBRIDGE_LIGHTCACHE_MINPATH {HIDDEN; MIN 1;PARENTID VP_VRAYBRIDGE_GI;}
					}
					GROUP
					{
						LONG VP_VRAYBRIDGE_LIGHTCACHE_RATIO
						{
							PARENTID VP_VRAYBRIDGE_GI;
							CYCLE
							{
								VP_VRAYBRIDGE_LIGHTCACHE_RATIO_6;
								VP_VRAYBRIDGE_LIGHTCACHE_RATIO_5;
								VP_VRAYBRIDGE_LIGHTCACHE_RATIO_4;
								VP_VRAYBRIDGE_LIGHTCACHE_RATIO_0;
								VP_VRAYBRIDGE_LIGHTCACHE_RATIO_1;
								VP_VRAYBRIDGE_LIGHTCACHE_RATIO_2;
								VP_VRAYBRIDGE_LIGHTCACHE_RATIO_3;
							}
						}
						
						SEPARATOR {}
						
						BOOL VP_VRAYBRIDGE_LIGHTCACHE_STOREDIRECT {PARENTID VP_VRAYBRIDGE_GI;}
						BOOL VP_VRAYBRIDGE_LIGHTCACHE_SHOWCALCPHASE {PARENTID VP_VRAYBRIDGE_GI;}
						BOOL VP_VRAYBRIDGE_LIGHTCACHE_CAMPATH {PARENTID VP_VRAYBRIDGE_GI;}
						BOOL VP_VRAYBRIDGE_LIGHTCACHE_ADAPTIVE {PARENTID VP_VRAYBRIDGE_GI;}
						BOOL VP_VRAYBRIDGE_LIGHTCACHE_ADAPTIVEDIRONLY {PARENTID VP_VRAYBRIDGE_GI;}				
					}
				}
			}

			SEPARATOR {LINE;}

			GROUP VP_VRAYBRIDGE_LIGHTCACHE_RECONSTRUCTION
			{
				DEFAULT 1;

				GROUP
				{
					LAYOUTGROUP; COLUMNS 2;
					GROUP
					{
						BOOL VP_VRAYBRIDGE_LIGHTCACHE_PREFILTER {PARENTID VP_VRAYBRIDGE_GI;}
						LONG VP_VRAYBRIDGE_LIGHTCACHE_FILTERTYPE
						{
							PARENTID VP_VRAYBRIDGE_GI;
							CYCLE
							{
								VP_VRAYBRIDGE_LIGHTCACHE_FILTERTYPE_0;
								VP_VRAYBRIDGE_LIGHTCACHE_FILTERTYPE_1;
								VP_VRAYBRIDGE_LIGHTCACHE_FILTERTYPE_2;
							}
						}
						BOOL VP_VRAYBRIDGE_LIGHTCACHE_DOGLOSSIES {PARENTID VP_VRAYBRIDGE_GI;}
						
						BOOL VP_VRAYBRIDGE_LIGHTCACHE_RETRACE {PARENTID VP_VRAYBRIDGE_GI;}
					}
					GROUP
					{
						LONG VP_VRAYBRIDGE_LIGHTCACHE_PREFILTERSAMPLES {MIN 2; MAX 1000;PARENTID VP_VRAYBRIDGE_GI;}
						REAL VP_VRAYBRIDGE_LIGHTCACHE_FILTERSIZE {HIDDEN; MIN 0; STEP 0.01;PARENTID VP_VRAYBRIDGE_GI;}
						LONG VP_VRAYBRIDGE_LIGHTCACHE_INTERPSAMPLES {HIDDEN; MIN 1;PARENTID VP_VRAYBRIDGE_GI;}
						LONG VP_VRAYBRIDGE_LIGHTCACHE_DEPTH {MIN 0;PARENTID VP_VRAYBRIDGE_GI;}
						REAL VP_VRAYBRIDGE_LIGHTCACHE_RETRACETHRESHOLD {MIN 0; STEP 0.01; PARENTID VP_VRAYBRIDGE_GI;}
					}
				}
			}

			SEPARATOR {LINE;}

			GROUP VP_VRAYBRIDGE_LIGHTCACHE_MODE
			{
				DEFAULT 1;
				
				GROUP
				{
					COLUMNS 2;

						LONG VP_VRAYBRIDGE_LIGHTCACHE_LIGHTMAPMODE
						{
							PARENTID VP_VRAYBRIDGE_GI;
							CYCLE
							{
								VP_VRAYBRIDGE_LIGHTCACHE_LIGHTMAPMODE_0;
								VP_VRAYBRIDGE_LIGHTCACHE_LIGHTMAPMODE_1;
								VP_VRAYBRIDGE_LIGHTCACHE_LIGHTMAPMODE_2;
								VP_VRAYBRIDGE_LIGHTCACHE_LIGHTMAPMODE_3;
							}
						}
						BUTTON VP_VRAYBRIDGE_SAVELC {}
				}
				SEPARATOR {}
				STRING VP_VRAYBRIDGE_LIGHTCACHE_LIGHTMAPFILE {HIDDEN;}
				FILENAME VP_VRAYBRIDGE_LIGHTCACHE_LIGHTMAPFILE2 {HIDDEN;}

				GROUP
				{
					COLUMNS 2;
						
					LONG VP_VRAYBRIDGE_LIGHTCACHE_FRAMEFROM {MIN 0; HIDDEN;}
					LONG VP_VRAYBRIDGE_LIGHTCACHE_FRAMETO {MIN 0; HIDDEN;}
				}
			}

			SEPARATOR {LINE;}

			GROUP VP_VRAYBRIDGE_LIGHTCACHE_RENDEREND
			{
				DEFAULT 1;

				BOOL VP_VRAYBRIDGE_LIGHTCACHE_NODELETE {PARENTID VP_VRAYBRIDGE_GI;}
				BOOL VP_VRAYBRIDGE_LIGHTCACHE_AUTOSAVEMAP {}
				STRING VP_VRAYBRIDGE_LIGHTCACHE_AUTOSAVEFILE {HIDDEN;}
				FILENAME VP_VRAYBRIDGE_LIGHTCACHE_AUTOSAVEFILE2 {SAVE;}
			}
		}
		
		/// SPHERICAL HARMONICS ///
		GROUP VP_VRAYBRIDGE_SPHERICALHARMONICS
		{
			HIDDEN;

			GROUP
			{
				LONG VP_VRAYBRIDGE_SPHERICALHARMONICS_SUBDIVS {MIN 0;PARENTID VP_VRAYBRIDGE_GI;}
				BOOL VP_VRAYBRIDGE_SPHERICALHARMONICS_HEMISPHERICAL {PARENTID VP_VRAYBRIDGE_GI;}
				LONG VP_VRAYBRIDGE_SPHERICALHARMONICS_PRECALC {MIN 0;PARENTID VP_VRAYBRIDGE_GI;}
				LONG VP_VRAYBRIDGE_SPHERICALHARMONICS_SAMPLEENV {MIN 0;PARENTID VP_VRAYBRIDGE_GI;}
				BOOL VP_VRAYBRIDGE_SPHERICALHARMONICS_FILTERING {PARENTID VP_VRAYBRIDGE_GI;}
				REAL VP_VRAYBRIDGE_SPHERICALHARMONICS_FILTERSTRENGHT {MIN 0; STEP 0.01;PARENTID VP_VRAYBRIDGE_GI;}
			}
		}
	}



	/// PHOTON CAUSTICS ///

	GROUP VP_VRAYBRIDGE_CAUSTICS
	{
		BOOL VP_VRAYBRIDGE_CAUSTICSON {}

		SEPARATOR {}
		
		REAL VP_VRAYBRIDGE_CAUSTICSMULT {MIN 0; STEP 0.01;}
		REAL VP_VRAYBRIDGE_CAUSTICSSEARCHDIST {UNIT METER; MIN 0; STEP 0.1;}
		LONG VP_VRAYBRIDGE_CAUSTICSMAXPHOTONS {MIN 0;}
		REAL VP_VRAYBRIDGE_CAUSTICSMAXDENSITY {MIN 0.001; STEP 1;}
		BOOL VP_VRAYBRIDGE_CAUSTICSSHOWCALC {}

		SEPARATOR {LINE;}

		GROUP VP_VRAYBRIDGE_CAUSTICSMODE
		{
			DEFAULT 1;
			
			GROUP
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					LONG VP_VRAYBRIDGE_CAUSTICSMAPMODE
					{
						CYCLE
						{
							VP_VRAYBRIDGE_CAUSTICSMAPMODE_0;
							VP_VRAYBRIDGE_CAUSTICSMAPMODE_1;
						}
					}
				}
				GROUP
				{
					BUTTON VP_VRAYBRIDGE_SAVECA {}
				}
			}
		
			STRING VP_VRAYBRIDGE_CAUSTICSMAPFILE {HIDDEN;}
			FILENAME VP_VRAYBRIDGE_CAUSTICSMAPFILE2 {HIDDEN;}
		}

		SEPARATOR {LINE;}

		GROUP VP_VRAYBRIDGE_CAUSTICSONRENDEREND
		{
			DEFAULT 1;

			BOOL VP_VRAYBRIDGE_CAUSTICSNODELETE {}
			BOOL VP_VRAYBRIDGE_CAUSTICSAUTOSAVEMAP {}
			STRING VP_VRAYBRIDGE_CAUSTICSAUTOSAVEFILE {HIDDEN;}
			FILENAME VP_VRAYBRIDGE_CAUSTICSAUTOSAVEFILE2 {SAVE; HIDDEN;}
		}
	}



	/// DISPLACEMENT ///

	GROUP VP_VRAYBRIDGE_DISPLACEMENT
	{
		GROUP
		{
			LAYOUTGROUP; COLUMNS 2;
			GROUP
			{
				REAL VP_VRAYBRIDGE_DISPLACEMENT_AMOUNT {UNIT METER; STEP 0.01;};
				REAL VP_VRAYBRIDGE_DISPLACEMENT_EDGE {MIN 0; STEP 0.1;}
				LONG VP_VRAYBRIDGE_DISPLACEMENT_SUBDIVS {MIN 0;}
			}
			GROUP
			{
				BOOL VP_VRAYBRIDGE_DISPLACEMENT_VIEWDEP {}
				BOOL VP_VRAYBRIDGE_DISPLACEMENT_RELATIVE {}
				BOOL VP_VRAYBRIDGE_DISPLACEMENT_BOUNDS {}
			}
			GROUP
			{
				
			}
		}
	}


	/// ENVIRONMENT ///

	GROUP VP_VRAYBRIDGE_ENVIRONMENT
	{
		GROUP VP_VRAYBRIDGE_ENVIRONMENT_OPTIONS
		{
			DEFAULT 1;
			
			GROUP
			{
				LAYOUTGROUP; COLUMNS 3;
				GROUP
				{
					BOOL VP_VRAYBRIDGE_ENVIRONMENT_BGNOGI {}
					BOOL VP_VRAYBRIDGE_ENVIRONMENTFOG_ON {}
				}
				GROUP
				{
					BOOL VP_VRAYBRIDGE_ENVIRONMENT_BGNOREFL {}
				}
				GROUP
				{
					BOOL VP_VRAYBRIDGE_ENVIRONMENT_BGNOREFR {}
				}
			}
		}
		
		SEPARATOR {LINE;}
		
		GROUP VP_VRAYBRIDGE_ENVIRONMENT_BGTAB
		{
			DEFAULT 1;

			COLOR VP_VRAYBRIDGE_ENVIRONMENT_BACKGROUND {OPEN;}
			REAL VP_VRAYBRIDGE_ENVIRONMENT_BGCOLORMULT {MIN 0; STEP 0.01; MAXSLIDER 1; CUSTOMGUI REALSLIDER;}
			SEPARATOR {}
			SHADERLINK VP_VRAYBRIDGE_ENVIRONMENT_BACKGROUNDTEX {}
			REAL VP_VRAYBRIDGE_ENVIRONMENT_BGMAPMUL {MIN 0; STEP 0.01; MAXSLIDER 1; CUSTOMGUI REALSLIDER;}
			LONG VP_VRAYBRIDGE_ENVIRONMENT_BGMAPTYPE
			{
				CYCLE
				{
					VP_VRAYBRIDGE_ENVIRONMENT_BGMAPTYPE_0;
					VP_VRAYBRIDGE_ENVIRONMENT_BGMAPTYPE_1;
					VP_VRAYBRIDGE_ENVIRONMENT_BGMAPTYPE_2;
					VP_VRAYBRIDGE_ENVIRONMENT_BGMAPTYPE_3;
					VP_VRAYBRIDGE_ENVIRONMENT_BGMAPTYPE_4;
				}
			}
			GROUP
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					REAL VP_VRAYBRIDGE_ENVIRONMENT_BGMAPROTH {UNIT DEGREE; STEP 0.1;}
				}
				GROUP
				{
					REAL VP_VRAYBRIDGE_ENVIRONMENT_BGMAPROTP {UNIT DEGREE; STEP 0.1;}
				}
			}
		}
		
		SEPARATOR {LINE;}

		GROUP VP_VRAYBRIDGE_ENVIRONMENT_GITAB
		{
			HIDDEN; DEFAULT 1;
			
			COLOR VP_VRAYBRIDGE_ENVIRONMENT_GIBACKGROUND {OPEN;}
			REAL VP_VRAYBRIDGE_ENVIRONMENT_GICOLORMULT {MIN 0; STEP 0.01; MAXSLIDER 1; CUSTOMGUI REALSLIDER;}
			SEPARATOR {}
			SHADERLINK VP_VRAYBRIDGE_ENVIRONMENT_GIBACKGROUNDTEX {}
			REAL VP_VRAYBRIDGE_ENVIRONMENT_GIMAPMUL {MIN 0; STEP 0.01; MAXSLIDER 1; CUSTOMGUI REALSLIDER;}
			LONG VP_VRAYBRIDGE_ENVIRONMENT_GIMAPTYPE
			{
				CYCLE
				{
					VP_VRAYBRIDGE_ENVIRONMENT_GIMAPTYPE_0;
					VP_VRAYBRIDGE_ENVIRONMENT_GIMAPTYPE_1;
					VP_VRAYBRIDGE_ENVIRONMENT_GIMAPTYPE_2;
					VP_VRAYBRIDGE_ENVIRONMENT_GIMAPTYPE_3;
					VP_VRAYBRIDGE_ENVIRONMENT_GIMAPTYPE_4;
				}
			}
			GROUP
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					REAL VP_VRAYBRIDGE_ENVIRONMENT_GIMAPROTH {UNIT DEGREE; STEP 0.1;}
				}
				GROUP
				{
					REAL VP_VRAYBRIDGE_ENVIRONMENT_GIMAPROTP {UNIT DEGREE; STEP 0.1;}

				}
			}
		}
		
		SEPARATOR {LINE;}
		
		GROUP VP_VRAYBRIDGE_ENVIRONMENT_REFLTAB
		{
			HIDDEN; DEFAULT 1;
			
			COLOR VP_VRAYBRIDGE_ENVIRONMENT_REFLBACKGROUND {OPEN;}
			REAL VP_VRAYBRIDGE_ENVIRONMENT_REFLCOLORMULT {MIN 0; STEP 0.01; MAXSLIDER 1; CUSTOMGUI REALSLIDER;}
			SEPARATOR {}
			SHADERLINK VP_VRAYBRIDGE_ENVIRONMENT_REFLBACKGROUNDTEX {}
			REAL VP_VRAYBRIDGE_ENVIRONMENT_REFLMAPMUL {MIN 0; STEP 0.01; MAXSLIDER 1; CUSTOMGUI REALSLIDER;}
			LONG VP_VRAYBRIDGE_ENVIRONMENT_REFLMAPTYPE
			{
				CYCLE
				{
					VP_VRAYBRIDGE_ENVIRONMENT_REFLMAPTYPE_0;
					VP_VRAYBRIDGE_ENVIRONMENT_REFLMAPTYPE_1;
					VP_VRAYBRIDGE_ENVIRONMENT_REFLMAPTYPE_2;
					VP_VRAYBRIDGE_ENVIRONMENT_REFLMAPTYPE_3;
					VP_VRAYBRIDGE_ENVIRONMENT_REFLMAPTYPE_4;
				}
			}
			GROUP
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					REAL VP_VRAYBRIDGE_ENVIRONMENT_REFLMAPROTH {UNIT DEGREE; STEP 0.1;}
				}
				GROUP
				{
					REAL VP_VRAYBRIDGE_ENVIRONMENT_REFLMAPROTP {UNIT DEGREE; STEP 0.1;}

				}
			}
		}
		
		SEPARATOR {LINE;}

		GROUP VP_VRAYBRIDGE_ENVIRONMENT_REFRTAB
		{
			HIDDEN; DEFAULT 1;
			
			COLOR VP_VRAYBRIDGE_ENVIRONMENT_REFRBACKGROUND {OPEN;}
			REAL VP_VRAYBRIDGE_ENVIRONMENT_REFRCOLORMULT {MIN 0; STEP 0.01; MAXSLIDER 1; CUSTOMGUI REALSLIDER;}
			SEPARATOR {}
			SHADERLINK VP_VRAYBRIDGE_ENVIRONMENT_REFRBACKGROUNDTEX {}
			REAL VP_VRAYBRIDGE_ENVIRONMENT_REFRMAPMUL {MIN 0; STEP 0.01; MAXSLIDER 1; CUSTOMGUI REALSLIDER;}
			LONG VP_VRAYBRIDGE_ENVIRONMENT_REFRMAPTYPE
			{
				CYCLE
				{
					VP_VRAYBRIDGE_ENVIRONMENT_REFRMAPTYPE_0;
					VP_VRAYBRIDGE_ENVIRONMENT_REFRMAPTYPE_1;
					VP_VRAYBRIDGE_ENVIRONMENT_REFRMAPTYPE_2;
					VP_VRAYBRIDGE_ENVIRONMENT_REFRMAPTYPE_3;
					VP_VRAYBRIDGE_ENVIRONMENT_REFRMAPTYPE_4;
				}
			}
			GROUP
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					REAL VP_VRAYBRIDGE_ENVIRONMENT_REFRMAPROTH {UNIT DEGREE; STEP 0.1;}
				}
				GROUP
				{
					REAL VP_VRAYBRIDGE_ENVIRONMENT_REFRMAPROTP {UNIT DEGREE; STEP 0.1;}

				}
			}
		}
		
		SEPARATOR {LINE;}
		
		/// ENVIRONMENT FOG
	
		GROUP VP_VRAYBRIDGE_ENVIRONMENTFOG
		{
			HIDDEN; DEFAULT 1;
			
			GROUP
			{	
				COLOR VP_VRAYBRIDGE_ENVIRONMENTFOG_COLOR {}
				SHADERLINK VP_VRAYBRIDGE_ENVIRONMENTFOG_COLORTEX {}
				SEPARATOR {}
				REAL VP_VRAYBRIDGE_ENVIRONMENTFOG_DISTANCE {UNIT METER; MIN 0; STEP 0.1;}
				SEPARATOR {}
				COLOR VP_VRAYBRIDGE_ENVIRONMENTFOG_EMITCOLOR {}
				SHADERLINK VP_VRAYBRIDGE_ENVIRONMENTFOG_EMITTEX {}
				SEPARATOR {}
				REAL VP_VRAYBRIDGE_ENVIRONMENTFOG_DENSITY {MIN 0; STEP 0.01;}
				SHADERLINK VP_VRAYBRIDGE_ENVIRONMENTFOG_DENSITYTEX {}
				SEPARATOR {}
				BOOL VP_VRAYBRIDGE_ENVIRONMENTFOG_SCATTERGI {}
				LONG VP_VRAYBRIDGE_ENVIRONMENTFOG_SCATTERBOUNCES {MIN 0;}
				BOOL VP_VRAYBRIDGE_ENVIRONMENTFOG_USEHEIGHT {}
				REAL VP_VRAYBRIDGE_ENVIRONMENTFOG_HEIGHT {UNIT METER; STEP 0.1;}
				SEPARATOR {}
				LONG VP_VRAYBRIDGE_ENVIRONMENTFOG_SUBDIVS {MIN 0;}
				REAL VP_VRAYBRIDGE_ENVIRONMENTFOG_STEPSIZE {UNIT METER; MIN 0; STEP 0.1;}
				LONG VP_VRAYBRIDGE_ENVIRONMENTFOG_TEXSAMPLES {MIN 0;}
				BOOL VP_VRAYBRIDGE_ENVIRONMENTFOG_SIMPLEGI {}		
				REAL VP_VRAYBRIDGE_ENVIRONMENTFOG_CUTOFF {MIN 0; STEP 0.001;}			
				LONG VP_VRAYBRIDGE_ENVIRONMENTFOG_MAXSTEPS {MIN 0;}
				SEPARATOR {}
				REAL VP_VRAYBRIDGE_ENVIRONMENTFOG_FADERADIUS {UNIT METER; MIN 0; STEP 0.01;}
				SHADERLINK VP_VRAYBRIDGE_ENVIRONMENTFOG_FADEOUTTEX {HIDDEN;}
				REAL VP_VRAYBRIDGE_ENVIRONMENTFOG_FADEOUTEDGE {HIDDEN; MIN 0; MAX 1; STEP 0.01;}
				LONG VP_VRAYBRIDGE_ENVIRONMENTFOG_FADEMODE
				{
					CYCLE
					{
						VP_VRAYBRIDGE_ENVIRONMENTFOG_FADEMODE_0;
						VP_VRAYBRIDGE_ENVIRONMENTFOG_FADEMODE_1;
					}
				}
				SEPARATOR {}
				BOOL VP_VRAYBRIDGE_ENVIRONMENTFOG_AFFECTBG {}
				BOOL VP_VRAYBRIDGE_ENVIRONMENTFOG_AFFECTREFL {}
				BOOL VP_VRAYBRIDGE_ENVIRONMENTFOG_AFFECTREFR {}
				BOOL VP_VRAYBRIDGE_ENVIRONMENTFOG_AFFECTSHD {}
				BOOL VP_VRAYBRIDGE_ENVIRONMENTFOG_AFFECTGI {}
				BOOL VP_VRAYBRIDGE_ENVIRONMENTFOG_AFFECTCAM {}
			}
			
			SEPARATOR {}
			
			GROUP
			{
				SCALE_V; COLUMNS 2;
	
				IN_EXCLUDE VP_VRAYBRIDGE_ENVIRONMENTFOG_OBJINCLUDE_LIST { SCALE_V; SCALE_H; INIT_STATE 15; ACCEPT { Obase; }; }
				IN_EXCLUDE VP_VRAYBRIDGE_ENVIRONMENTFOG_LIGHTINCLUDE_LIST { SCALE_V; SCALE_H; INIT_STATE 15; ACCEPT { Olight; }; }
			}
		}
	}
	
	



	/// COLOR MAPPING ///

	GROUP VP_VRAYBRIDGE_COLORMAPPING
	{
		

		SEPARATOR {}

		GROUP
		{
			LAYOUTGROUP; COLUMNS 2;
			GROUP
			{
				LONG VP_VRAYBRIDGE_COLORMAPPING_TYPE
				{
					CYCLE
					{
						VP_VRAYBRIDGE_COLORMAPPING_TYPE_0;
						VP_VRAYBRIDGE_COLORMAPPING_TYPE_1;
						VP_VRAYBRIDGE_COLORMAPPING_TYPE_2;
						VP_VRAYBRIDGE_COLORMAPPING_TYPE_3;
						VP_VRAYBRIDGE_COLORMAPPING_TYPE_4;
						VP_VRAYBRIDGE_COLORMAPPING_TYPE_5;
						VP_VRAYBRIDGE_COLORMAPPING_TYPE_6;
					}
				}
				REAL VP_VRAYBRIDGE_COLORMAPPING_DARKMUL {STEP 0.1; HIDDEN;}
				REAL VP_VRAYBRIDGE_COLORMAPPING_MULTIPLIER {STEP 0.1; HIDDEN;}
				REAL VP_VRAYBRIDGE_COLORMAPPING_BRIGHTMUL {STEP 0.1; HIDDEN;}
				REAL VP_VRAYBRIDGE_COLORMAPPING_INVERSEGAMMA {STEP 0.1; HIDDEN;}
				REAL VP_VRAYBRIDGE_COLORMAPPING_BURN {STEP 0.1; HIDDEN;}
				REAL VP_VRAYBRIDGE_COLORMAPPING_GAMMA {MIN 0; STEP 0.1;}
			}
			GROUP
			{
				BOOL VP_VRAYBRIDGE_COLORMAPPING_SUBPIXEL {}
				BOOL VP_VRAYBRIDGE_COLORMAPPING_CLAMP {}
				REAL VP_VRAYBRIDGE_COLORMAPPING_CLAMPLEVEL {MIN 0; STEP 0.01;}
				BOOL VP_VRAYBRIDGE_COLORMAPPING_ADAPTATION {}
				BOOL VP_VRAYBRIDGE_COLORMAPPING_ADAPTATION_NOVIEWPORT {}
				BOOL VP_VRAYBRIDGE_COLORMAPPING_AFFECTBG {}
				BOOL VP_VRAYBRIDGE_COLORMAPPING_LWF {}
			}
		}
	}



	/// CAMERA ///

	GROUP VP_VRAYBRIDGE_CAMERA
	{
		LONG VP_VRAYBRIDGE_CAMTYPE
		{
			CYCLE
			{
				VP_VRAYBRIDGE_CAMTYPE_STANDARD;
				VP_VRAYBRIDGE_CAMTYPE_SPHERICAL;
				VP_VRAYBRIDGE_CAMTYPE_CYLINDRICAL;
				VP_VRAYBRIDGE_CAMTYPE_CYLORTHO;
				VP_VRAYBRIDGE_CAMTYPE_BOX;
				VP_VRAYBRIDGE_CAMTYPE_FISHEYE;
				VP_VRAYBRIDGE_CAMTYPE_WARPED;
				VP_VRAYBRIDGE_CAMTYPE_ORTHOGONAL;
				VP_VRAYBRIDGE_CAMTYPE_PINHOLE;
			}
		}
		SEPARATOR {LINE;}
		REAL VP_VRAYBRIDGE_CAMTYPE_CYLINDRICAL_HEIGHT {MIN 0; STEP 0.01; UNIT METER;}
		GROUP
		{
			//LAYOUTGROUP; 
			COLUMNS 3;
				
			BOOL VP_VRAYBRIDGE_CAMTYPE_FISHEYE_AUTO {}
			REAL VP_VRAYBRIDGE_CAMTYPE_FISHEYE_DELTA {MIN 0; STEP 0.01;}
			REAL VP_VRAYBRIDGE_CAMTYPE_FISHEYE_CURVE {MIN 0; STEP 0.01;}
		}
		SEPARATOR {LINE;}
		GROUP
		{
			COLUMNS 2;
				
			BOOL VP_VRAYBRIDGE_OVERRIDEFOV {}
			REAL VP_VRAYBRIDGE_VRAYFOV {MIN 0; MAX 360; UNIT DEGREE;}
		}
		SEPARATOR {LINE;}
		BOOL VP_VRAYBRIDGE_ACTIVE_CAMERA {} 
		GROUP
		{
			COLUMNS 3;

			BOOL VP_VRAYBRIDGE_CLIPPING {}
			REAL VP_VRAYBRIDGE_CLIPNEAR {MIN 0; STEP 0.1; MAXSLIDER 100; UNIT METER;}
			REAL VP_VRAYBRIDGE_CLIPFAR {MIN 0; STEP 0.1; MAXSLIDER 100; UNIT METER;}
		}

		SEPARATOR {LINE;}

		GROUP
		{
			LAYOUTGROUP; COLUMNS 3;
			GROUP
			{
				BOOL VP_VRAYBRIDGE_CAMTYPE_PARALLEL { HIDDEN; }
			}
			GROUP
			{
				BOOL VP_VRAYBRIDGE_CAMTYPE_PARALLEL_ADJUST { HIDDEN;}
			}
			GROUP
			{
				REAL VP_VRAYBRIDGE_CAMTYPE_PARALLEL_ZOOM {MIN 0; STEP 0.01; HIDDEN; }
			}
		}

		GROUP VP_VRAYBRIDGE_DOF
		{
			DEFAULT 1;

			BOOL VP_VRAYBRIDGE_DOFON	{}

			SEPARATOR {}

			GROUP
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					REAL VP_VRAYBRIDGE_DOFAPERTURE {UNIT METER; MIN 0; STEP 0.1;}
					REAL VP_VRAYBRIDGE_DOFBIAS	{STEP 0.1;}
					LONG VP_VRAYBRIDGE_DOFSUBDIV	{MIN 0;}
				}
				GROUP
				{
					BOOL VP_VRAYBRIDGE_DOFSIDESON {}
					LONG VP_VRAYBRIDGE_DOFSIDESNUM	{MIN 3; MAX 12;}
					REAL VP_VRAYBRIDGE_DOFROT	{MIN 0; STEP 1;}
					REAL VP_VRAYBRIDGE_DOFANISO {MIN -1; MAX 1; STEP 1;}
				}
			}
		}

		SEPARATOR {LINE;}

		GROUP VP_VRAYBRIDGE_MBLUR
		{
			DEFAULT 1;

			BOOL VP_VRAYBRIDGE_MBLURON {}

			SEPARATOR {}

			GROUP
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					REAL VP_VRAYBRIDGE_MBLURDURATION	{MIN 0; STEP 0.1;}
					REAL VP_VRAYBRIDGE_MBLURINTERVAL	{MIN 0; MAX 1; STEP 0.1;}
					REAL VP_VRAYBRIDGE_MBLURBIAS	{STEP 0.1;}
				}
				GROUP
				{
					LONG VP_VRAYBRIDGE_MBLURGEOMSAMPLES	{MIN 1;}
					LONG VP_VRAYBRIDGE_MBLURLOWSAMPLES	{MIN 1;}
					LONG VP_VRAYBRIDGE_MBLURMINSAMPLES	{MIN 1; MAX 256;}
				}
			}
			BOOL VP_VRAYBRIDGE_MBLUR_NOCAMERA {}
			//LONG VP_VRAYBRIDGE_MBLURMAXSAMPLES	{MIN 1; MAX 100;}
			//LONG VP_VRAYBRIDGE_MBLURGEOMSAMPLEOFFSET	{MIN 0;}
			//BOOL VP_VRAYBRIDGE_MBLURPARTICLES {}

		}

	}


	/// SYSTEM ///

	GROUP VP_VRAYBRIDGE_SYSTEM
	{
		GROUP VP_VRAYBRIDGE_RAYCASTER
		{
			DEFAULT 1;

			LONG VP_VRAYBRIDGE_MAXLEVELS {MIN 1; MAX 100;}
			REAL VP_VRAYBRIDGE_MINLEAFSIZE {MIN 0; STEP 0.01;}
			REAL VP_VRAYBRIDGE_FACELEVELCOEF {MIN 0; MAX 100; STEP 0.1;}
			LONG VP_VRAYBRIDGE_MEMLIMIT {MIN 0; STEP 1;}
			LONG VP_VRAYBRIDGE_OPTLEVEL {MIN 0; MAX 6; HIDDEN;}
		}

		SEPARATOR {LINE;}
			
		GROUP VP_VRAYBRIDGE_BUCKETDESIGN
		{
			DEFAULT 1;

				GROUP /// Save buckets settings
				{
					LAYOUTGROUP; COLUMNS 2;
					GROUP
					{
						BUTTON VP_VRAYBRIDGE_BUCKET_SAVE_SETTINGS {}
					}
					GROUP
					{
						BUTTON VP_VRAYBRIDGE_BUCKET_LOAD_SETTINGS {}
					}
				}
			
			SEPARATOR {LINE;}
			
			GROUP
			{
				//LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					COLOR VP_VRAYBRIDGE_BUCKETBORDER { PARENTID VP_VRAYBRIDGE_BUCKETDESIGN; }
				}
				GROUP
				{
					REAL VP_VRAYBRIDGE_BUCKET_TRASPARENCY  {UNIT PERCENT; MIN 0; MAX 100; STEP 1; PARENTID VP_VRAYBRIDGE_BUCKETDESIGN;}
					REAL VP_VRAYBRIDGE_BUCKET_TRASPARENCY_RAMP  {UNIT PERCENT; MIN 0; MAX 100; STEP 1; PARENTID VP_VRAYBRIDGE_BUCKETDESIGN;}
					BOOL VP_VRAYBRIDGE_BUCKET_RAMPON {PARENTID VP_VRAYBRIDGE_BUCKETDESIGN;}
					BOOL VP_VRAYBRIDGE_BUCKET_OLD_STYLE {PARENTID VP_VRAYBRIDGE_BUCKETDESIGN;}
				}
			
			SEPARATOR {LINE;} // CLIENT GROUP
			
			GROUP VP_VRAYBRIDGE_BUCKET_MASTER_TITLE
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					COLOR VP_VRAYBRIDGE_BUCKETGRAD_TOP_MASTER {PARENTID VP_VRAYBRIDGE_BUCKETDESIGN;}
					COLOR VP_VRAYBRIDGE_BUCKETGRAD_BOT_MASTER {PARENTID VP_VRAYBRIDGE_BUCKETDESIGN;}
				}
				GROUP
				{
					BITMAPBUTTON VP_VRAYBRIDGE_BUCKETGRAD_CLIENT_PREVIEW	{}
				}
			}
			
			SEPARATOR {LINE;} 
			
			GROUP VP_VRAYBRIDGE_BUCKET_SLAVE_TITLE
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP 
				{
					COLOR VP_VRAYBRIDGE_BUCKETGRAD_TOP1_SLAVE {PARENTID VP_VRAYBRIDGE_BUCKETDESIGN;}
					COLOR VP_VRAYBRIDGE_BUCKETGRAD_BOT1_SLAVE {PARENTID VP_VRAYBRIDGE_BUCKETDESIGN;}
					SEPARATOR {LINE;}
					COLOR VP_VRAYBRIDGE_BUCKETGRAD_TOP2_SLAVE {PARENTID VP_VRAYBRIDGE_BUCKETDESIGN;}
					COLOR VP_VRAYBRIDGE_BUCKETGRAD_BOT2_SLAVE {PARENTID VP_VRAYBRIDGE_BUCKETDESIGN;}
				}
				GROUP
				{
					BITMAPBUTTON VP_VRAYBRIDGE_BUCKETGRAD_SLAVE1_PREVIEW	{}
					SEPARATOR {LINE;}
					SEPARATOR {LINE;}
					BITMAPBUTTON VP_VRAYBRIDGE_BUCKETGRAD_SLAVE2_PREVIEW	{}
				}
			}
		}
	}
		SEPARATOR {LINE;}
		

		GROUP VP_VRAYBRIDGE_RENDERREGION
		{
			DEFAULT 1;

			GROUP
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					LONG VP_VRAYBRIDGE_BUCKETX {MIN 1; MAX 1000;}
					LONG VP_VRAYBRIDGE_BUCKETY {MIN 1; MAX 1000;}
					LONG VP_VRAYBRIDGE_VIEWPORTBUCKETX {MIN 1; MAX 1000;}
					LONG VP_VRAYBRIDGE_VIEWPORTBUCKETY {MIN 1; MAX 1000;}
				}
				GROUP
				{
					LONG VP_VRAYBRIDGE_XYMEANS
					{
						CYCLE
						{
							VP_VRAYBRIDGE_XYMEANS_REGIONWH;
							VP_VRAYBRIDGE_XYMEANS_REGIONCOUNT;
						}
					}
					LONG VP_VRAYBRIDGE_SEQTYPE
					{
						CYCLE
						{
							VP_VRAYBRIDGE_SEQTYPE_TOPBOTTOM;
							VP_VRAYBRIDGE_SEQTYPE_LEFTRIGHT;
							VP_VRAYBRIDGE_SEQTYPE_CHECKER;
							VP_VRAYBRIDGE_SEQTYPE_SPIRAL;
							VP_VRAYBRIDGE_SEQTYPE_TRIANGULATION;
							VP_VRAYBRIDGE_SEQTYPE_HILBERT;
							//VP_VRAYBRIDGE_SEQTYPE_FOLLOWMOUSE;
							//VP_VRAYBRIDGE_SEQTYPE_SMART;												
						}
					}
					BOOL VP_VRAYBRIDGE_REVERSE {}	
					REAL VP_VRAYBRIDGE_PREVIOUS_PICTURE_OPACITY { UNIT PERCENT; MIN 0.0; MAX 100.0; }
				}
			}

			SEPARATOR {LINE;}

			GROUP VP_VRAYBRIDGE_GROUP_REGIONSPLIT
			{
				DEFAULT 1;
				
				GROUP
				{
					LAYOUTGROUP; COLUMNS 2;
					GROUP
					{
						BOOL VP_VRAYBRIDGE_SPLITON {}
						BOOL VP_VRAYBRIDGE_HORIZONTAL_SPLIT {}
						LONG VP_VRAYBRIDGE_SPLIT {MIN 1;}
						LONG VP_VRAYBRIDGE_SPLITPIXELS {MIN -10; MAX 10;}
					}
					GROUP
					{
						BOOL VP_VRAYBRIDGE_REGIONON			{}
						REAL VP_VRAYBRIDGE_REGIONRENDER_X1	{UNIT PERCENT;}
						REAL VP_VRAYBRIDGE_REGIONRENDER_Y1	{UNIT PERCENT;}
						REAL VP_VRAYBRIDGE_REGIONRENDER_X2	{UNIT PERCENT;}
						REAL VP_VRAYBRIDGE_REGIONRENDER_Y2	{UNIT PERCENT;}
						BUTTON VP_VRAYBRIDGE_GETLASTREGION	{}
					}
				}
			}

			SEPARATOR {}

			LONG POINTERBASEDOC	{HIDDEN;}
			LONG GLOBALILLUM	{HIDDEN;}
		}
		SEPARATOR {}
		GROUP VP_VRAYBRIDGE_GROUP_PATH
		{
			DEFAULT 1;
			BOOL	 VP_VRAYBRIDGE_ASK_FILE_KNOWN_PATH {}
			SEPARATOR {LINE;}

			FILENAME VP_VRAYBRIDGE_TEMP_PATH { DIRECTORY; }

			SEPARATOR {LINE;}
			BOOL	 VP_VRAYBRIDGE_RAW_IMAGE_SAVE	 {}
			FILENAME VP_VRAYBRIDGE_RAW_IMAGE_DIR	 { DIRECTORY; }
			FILENAME VP_VRAYBRIDGE_RAW_IMAGE_FILE	 {  }
		}
	}


	/// MULTIPASS

	GROUP VP_VRAYBRIDGE_MULTIPASS
	{
		HIDDEN;

		GROUP VP_VRAYBRIDGE_GROUP_STANDARD
		{
			//HIDDEN;
			DEFAULT 1;
			BOOL VP_VRAYBRIDGE_MULTIPASS_SELFILLUM {}
			BOOL VP_VRAYBRIDGE_MULTIPASS_ATMOSPHERE {}
			BOOL VP_VRAYBRIDGE_MULTIPASS_CAUSTICS {}
			BOOL VP_VRAYBRIDGE_MULTIPASS_SPECULAR {}
			BOOL VP_VRAYBRIDGE_MULTIPASS_REFRACT {}
			BOOL VP_VRAYBRIDGE_MULTIPASS_REFLECT {}
			BOOL VP_VRAYBRIDGE_MULTIPASS_SHADOW {}
			BOOL VP_VRAYBRIDGE_MULTIPASS_GI {}
			BOOL VP_VRAYBRIDGE_MULTIPASS_LIGHTING {}
		}
		
		SEPARATOR {LINE;}

		GROUP VP_VRAYBRIDGE_GROUP_ADVANCED
		{
			//HIDDEN;
			//DEFAULT 1;
			BOOL VP_VRAYBRIDGE_MULTIPASS_MATTESHADOW {}
			BOOL VP_VRAYBRIDGE_MULTIPASS_DIFFUSE {}
			BOOL VP_VRAYBRIDGE_MULTIPASS_BACKGROUND {}

			BOOL VP_VRAYBRIDGE_MULTIPASS_RAWGI {}
			BOOL VP_VRAYBRIDGE_MULTIPASS_RAWLIGHT {}
			BOOL VP_VRAYBRIDGE_MULTIPASS_RAWSHADOW {}
			BOOL VP_VRAYBRIDGE_MULTIPASS_REFLECTION_FILTER {}
			BOOL VP_VRAYBRIDGE_MULTIPASS_RAW_REFLECTION {}
			BOOL VP_VRAYBRIDGE_MULTIPASS_REFRACTION_FILTER {}
			BOOL VP_VRAYBRIDGE_MULTIPASS_RAW_REFRACTION {}
			BOOL VP_VRAYBRIDGE_MULTIPASS_REALCOLOR {}
			BOOL VP_VRAYBRIDGE_MULTIPASS_TOTALLIGHT {}
			BOOL VP_VRAYBRIDGE_MULTIPASS_RAWTOTALLIGHT {}
			BOOL VP_VRAYBRIDGE_MULTIPASS_RAWSHADING {}
		}
		
		SEPARATOR {LINE;}

		GROUP VP_VRAYBRIDGE_GROUP_DEPTH
		{
			//DEFAULT 1;
			GROUP
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					BOOL VP_VRAYBRIDGE_MULTIPASS_ZDEPTH {}
					REAL VP_VRAYBRIDGE_MULTIPASS_ZDEPTH_NEAR {MIN 0; STEP 0.01;}
					REAL VP_VRAYBRIDGE_MULTIPASS_ZDEPTH_FAR {MIN 0; STEP 0.01;}
				}
				GROUP
				{
					
					BOOL VP_VRAYBRIDGE_MULTIPASS_NORMAL {}
					BOOL VP_VRAYBRIDGE_MULTIPASS_VELOCITY {}
				}
			}

			//BOOL VP_VRAYBRIDGE_MULTIPASS_WIRECOLOR {} OLD DELETED
		}
		
		SEPARATOR {LINE;}

		GROUP VP_VRAYBRIDGE_GROUP_ID
		{
			//DEFAULT 1;
			//HIDDEN;
			BOOL VP_VRAYBRIDGE_MULTIPASS_RENDERID {}
			BOOL VP_VRAYBRIDGE_MULTIPASS_MTLID {}
			BOOL VP_VRAYBRIDGE_MULTIPASS_NODEID {}
		}

		//BOOL VP_VRAYBRIDGE_MULTIPASS_ALPHA {}
		//BOOL VP_VRAYBRIDGE_MULTIPASS_COLOR {}
	}

	GROUP VP_VRAYBRIDGE_CLIPPER
	{

		STATICTEXT { NAME VP_VRAYBRIDGE_CLIPPER_TEXT01; }

		GROUP
		{
			LAYOUTGROUP; COLUMNS 3;
			GROUP
			{
				BUTTON	 VP_VRAYBRIDGE_CLIPPER_START	 {}
				REAL VP_VRAYBRIDGE_CLIPPER_DISTANCE_FRONT	{ MIN 0.0;}
				REAL VP_VRAYBRIDGE_CLIPPER_DISTANCE_BACK	{ MIN 0.0;}
				BUTTON VP_VRAYBRIDGE_CLIPPER_MODIFY_SCENE {}
			}
			GROUP
			{
				BUTTON	VP_VRAYBRIDGE_CLIPPER_STORE_STATUS	 {}
			}
			GROUP
			{
				BUTTON	VP_VRAYBRIDGE_CLIPPER_RESTORE_STATUS {}
			}
		}
	}

/// DR ///

	GROUP VP_VRAYBRIDGE_DR
	{
		//BOOL VP_VRAYBRIDGE_DR_ASSLAVE {}
		BOOL VP_VRAYBRIDGE_DR_ENABLEDR	{}
		BOOL VP_VRAYBRIDGE_DR_ASSETS_ON {}
		LONG VP_VRAYBRIDGE_DR_TYPE
		{
			CYCLE
			{
				VP_VRAYBRIDGE_DR_TO_CINEMA_4D;
				VP_VRAYBRIDGE_DR_TO_VRAY_STANDALONE;
			}
		}
		

		SEPARATOR {LINE;}
		GROUP 
		{
			COLUMNS 3;
			LONG VP_VRAYBRIDGE_DR_SLAVELISTLASTDGT {}
			BUTTON VP_VRAYBRIDGE_DR_SAVEIPLIST {}
			BUTTON VP_VRAYBRIDGE_DR_LOADIPLIST {}
		}
		SEPARATOR {LINE;}
		//BUTTON VP_VRAYBRIDGE_DR_SAVEIPLIST {}
		//LONG VP_VRAYBRIDGE_DR_SLAVELISTLASTDGT {}
		BUTTON VP_VRAYBRIDGE_DR_ADD_ALL_NET {}
		SEPARATOR {LINE;}

		GROUP VP_VRAYBRIDGE_DR_4COLONNE
		{	
			COLUMNS 2;
		}
	
	}


	GROUP VP_VRAYBRIDGE_TRANSLATOR_GROUP
	{
		BOOL VP_VRAYBRIDGE_TR_RENDER			{}			
		BOOL VP_VRAYBRIDGE_TR_EXPORT			{}	
		SEPARATOR {LINE;}
		BOOL VP_VRAYBRIDGE_TR_SEPARATE_FILES	{}			
		BOOL VP_VRAYBRIDGE_TR_EXPORT_LIGHT		{}			
		//BOOL VP_VRAYBRIDGE_TR_EXPORT_NODES		{}			
		BOOL VP_VRAYBRIDGE_TR_EXPORT_GEOM		{}			
		BOOL VP_VRAYBRIDGE_TR_EXPORT_MATS		{}			
		BOOL VP_VRAYBRIDGE_TR_EXPORT_TEXTURES	{}		
		//BOOL VP_VRAYBRIDGE_TR_EXPORT_BITMAPS	{}	
		SEPARATOR {LINE;}
		BOOL VP_VRAYBRIDGE_TR_PER_FRAME			{}				
		BOOL VP_VRAYBRIDGE_TR_MESH_HEX			{}				
		BOOL VP_VRAYBRIDGE_TR_TRANS_HEX			{}				
		BOOL VP_VRAYBRIDGE_TR_COMPRESSED		{}			
		SEPARATOR {LINE;}
		FILENAME VP_VRAYBRIDGE_TR_FILE_NAME		{ SAVE; }		
	}
}
