CONTAINER Xcustombuffershader
{
	NAME Xcustombuffershader;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		GROUP CUSTOMBUFSH_RGBGROUP
		{ 
		DEFAULT 1;
		BOOL CUSTOMBUFSH_USECHANNELCOLOR { } 
		SHADERLINK CUSTOMBUFSH_RGBSH { }
		}
		
		GROUP CUSTOMBUFSH_FOLDER
		{ 
		DEFAULT 1;
		BOOL CUSTOMBUFSH_ENABCUSTOM1{}
		SHADERLINK CUSTOMBUFSH_CUSTOM1{ }
		LONG CUSTOMBUFSH_CUSTOM1BUF{MIN 1; MAX 10000;}
		SEPARATOR{LINE;}
		BOOL CUSTOMBUFSH_ENABCUSTOM2{}
		SHADERLINK CUSTOMBUFSH_CUSTOM2{ }
		LONG CUSTOMBUFSH_CUSTOM2BUF{MIN 1; MAX 10000;}
		SEPARATOR{LINE;}
		BOOL CUSTOMBUFSH_ENABCUSTOM3{}
		SHADERLINK CUSTOMBUFSH_CUSTOM3{ }
		LONG CUSTOMBUFSH_CUSTOM3BUF{MIN 1; MAX 10000;}
		SEPARATOR{LINE;}
		BOOL CUSTOMBUFSH_ENABCUSTOM4{}
		SHADERLINK CUSTOMBUFSH_CUSTOM4{ }
		LONG CUSTOMBUFSH_CUSTOM4BUF{MIN 1; MAX 10000;}
		SEPARATOR{LINE;}
		BOOL CUSTOMBUFSH_ENABCUSTOM5{}
		SHADERLINK CUSTOMBUFSH_CUSTOM5{ }
		LONG CUSTOMBUFSH_CUSTOM5BUF{MIN 1; MAX 10000;}
		SEPARATOR{LINE;}
		BOOL CUSTOMBUFSH_ENABCUSTOM6{}
		SHADERLINK CUSTOMBUFSH_CUSTOM6{ }
		LONG CUSTOMBUFSH_CUSTOM6BUF{MIN 1; MAX 10000;}
		SEPARATOR{LINE;}
		BOOL CUSTOMBUFSH_ENABCUSTOM7{}
		SHADERLINK CUSTOMBUFSH_CUSTOM7{ }
		LONG CUSTOMBUFSH_CUSTOM7BUF{MIN 1; MAX 10000;}
		SEPARATOR{LINE;}
		BOOL CUSTOMBUFSH_ENABCUSTOM8{}
		SHADERLINK CUSTOMBUFSH_CUSTOM8{ }
		LONG CUSTOMBUFSH_CUSTOM8BUF{MIN 1; MAX 10000;}
		SEPARATOR{LINE;}
		BOOL CUSTOMBUFSH_ENABCUSTOM9{}
		SHADERLINK CUSTOMBUFSH_CUSTOM9{ }
		LONG CUSTOMBUFSH_CUSTOM9BUF{MIN 1; MAX 10000;}
		SEPARATOR{LINE;}
		BOOL CUSTOMBUFSH_ENABCUSTOM10{}
		SHADERLINK CUSTOMBUFSH_CUSTOM10{ }
		LONG CUSTOMBUFSH_CUSTOM10BUF{MIN 1; MAX 10000;}
		SEPARATOR{LINE;}
		}
		}
}
