CONTAINER XFF_SHADER
{
	NAME XFF_SHADER;

	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		DEFAULT 1;
		COLOR 	FASTFUR_TIPCOLOR		{}
		COLOR	FASTFUR_ROOTCOLOR		{}
		SEPARATOR { LINE; }
		BOOL	FASTFUR_DERIVECOLOR		{}
		//LINK	FASTFUR_FFLINK			{}
		REAL	FASTFUR_MIXCOLOR		{MIN 0.0; MAX 1.0; STEP 0.01; CUSTOMGUI REALSLIDER;}
		SEPARATOR { LINE; }
	}
}