#ifndef _xVrayBitmap_H_
#define _xVrayBitmap_H_

enum
{
	VRAY_BITMAP				= 1000,
	VRAY_BITMAP_FILTERTYPE	= 1001,
	VRAY_BITMAP_FILTERTYPE_0	= 0,
	VRAY_BITMAP_FILTERTYPE_1	= 1,
	VRAY_BITMAP_FILTERTYPE_2	= 2,
	VRAY_BITMAP_FILTERBLUR	= 1002,
	VRAY_BITMAP_TILE		= 1003,
	VRAY_BITMAP_WRAPU		= 1004,
	VRAY_BITMAP_WRAPV		= 1005
};

#endif