#ifndef _xVrayNoise_H_
#define _xVrayNoise_H_

enum
{		
	TEXNOISE_PERSISTENCE = 1000,	
	TEXNOISE_AMPLITUDERATIO,		
	TEXNOISE_FREQUENCYRATIO,	
	TEXNOISE_FREQUENCY1,		
	TEXNOISE_AMPLITUDE1,
	TEXNOISE_OCTAVES,

	TEXNOISE_NOISETYPE = 1010,
	TEXNOISE_NOISETYPE_0 = 0,
	TEXNOISE_NOISETYPE_1 = 1,
	TEXNOISE_NOISETYPE_2 = 2,
	TEXNOISE_NOISETYPE_3 = 3,

	TEXNOISE_SIZE	= 1015,

	TEXNOISE_INFLECTION = 1020,
	TEXNOISE_INFLECTION_0 = 0,
	TEXNOISE_INFLECTION_1 = 1,

	TEXNOISE_MIXRATIO	= 1025,
	TEXNOISE_BIAS,
	TEXNOISE_COLOR1,
	TEXNOISE_COLOR1TEX,
	TEXNOISE_COLOR1TEXMUL,
	TEXNOISE_COLOR2,
	TEXNOISE_COLOR2TEX,
	TEXNOISE_COLOR2TEXMUL,

	TEXNOISE_USE3D,

	VRAY_TEXNOISE_SHADER_NAME	= 3000			
};

#endif