CONTAINER Xvraynoise
{
	NAME Xvraynoise;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		STRING		VRAY_TEXNOISE_SHADER_NAME {HIDDEN;} ;
		REAL		TEXNOISE_PERSISTENCE		{ MIN 0; STEP 0.01;}
		REAL		TEXNOISE_AMPLITUDERATIO	{MIN 0; STEP 0.01;}				
		REAL		TEXNOISE_FREQUENCYRATIO		{ MIN 0; STEP 0.01;}
		REAL		TEXNOISE_FREQUENCY1	{MIN 0; STEP 0.01;}
		REAL		TEXNOISE_AMPLITUDE1 {MIN 0; STEP 0.01;}
		LONG		TEXNOISE_OCTAVES {MIN 1;}
		
		LONG		TEXNOISE_NOISETYPE
		{
			CYCLE
			{
				TEXNOISE_NOISETYPE_0;
				TEXNOISE_NOISETYPE_1;
				TEXNOISE_NOISETYPE_2;
				TEXNOISE_NOISETYPE_3;
			}
		}
								
		REAL TEXNOISE_SIZE {MIN 0; STEP 0.01;}
		
		LONG TEXNOISE_INFLECTION
		{
			CYCLE
			{
				TEXNOISE_INFLECTION_0;
				TEXNOISE_INFLECTION_1;
			}
		}
		
		REAL TEXNOISE_MIXRATIO {MIN 0; MAX 1; STEP 0.01;}
		REAL TEXNOISE_BIAS {MIN 0; STEP 0.01;}
		
		COLOR TEXNOISE_COLOR1 {OPEN;}
		SHADERLINK TEXNOISE_COLOR1TEX {}
		REAL TEXNOISE_COLOR1TEXMUL {MIN 0; STEP 0.01;}
		
		COLOR TEXNOISE_COLOR2 {OPEN;}
		SHADERLINK TEXNOISE_COLOR2TEX {}
		REAL TEXNOISE_COLOR2TEXMUL {MIN 0; STEP 0.01;}
		
		BOOL TEXNOISE_USE3D	{}
	}
}
