CONTAINER Xvraychecker
{
	NAME Xvraychecker;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		STRING	VRAY_TEXCHECKER_SHADER_NAME {HIDDEN;} ;
		COLOR		TEXCHECKER_WHITECOLOR		{ OPEN; }	;	
		SHADERLINK	TEXCHECKER_WHITECOLOR_TEX	{};				
		COLOR		TEXCHECKER_BLACKCOLOR		{ OPEN; };				
		SHADERLINK	TEXCHECKER_BLACKCOLOR_TEX	{};
		BOOL		TEXCHECKER_TILE_U			{};
		BOOL		TEXCHECKER_TILE_V			{};						
	}
}
