CONTAINER xVrayShader
{
	NAME xVrayShader;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		//GRADIENT SDKGRADIENTSHADER_COLOR { COLOR; }
		//LONG	SDKGRADIENTSHADER_MODE
		//{
		//	CYCLE
		//	{
		//		SDKGRADIENTSHADER_MODE_U;
		//		SDKGRADIENTSHADER_MODE_V;
		//		SDKGRADIENTSHADER_MODE_DIAGONAL;
		//		SDKGRADIENTSHADER_MODE_RADIAL;
		//		SDKGRADIENTSHADER_MODE_CIRCULAR;
		//		SDKGRADIENTSHADER_MODE_BOX;
		//		SDKGRADIENTSHADER_MODE_STAR;
		//		SDKGRADIENTSHADER_MODE_CORNER;
		//	}
		//}
		//REAL SDKGRADIENTSHADER_ANGLE { UNIT DEGREE; }
		//BOOL SDKGRADIENTSHADER_CYCLE { }
		//SEPARATOR { LINE; }
		//REAL SDKGRADIENTSHADER_TURBULENCE { UNIT PERCENT; MIN 0.0; MAX 100.0; }
		//REAL SDKGRADIENTSHADER_OCTAVES	 { MIN 0.0; MAX 10.0; STEP 0.1; }
		//REAL SDKGRADIENTSHADER_SCALE		 { UNIT PERCENT; MIN 0.0; MAX 1000.0; }
		//REAL SDKGRADIENTSHADER_FREQ		 { MIN 0.0; MAX 1000.0; STEP 0.1; }
		//BOOL SDKGRADIENTSHADER_ABSOLUTE { }
	}
}