#ifndef _xVrayChecker_H_
#define _xVrayChecker_H_

enum
{
	TEXCHECKER_WHITECOLOR = 1000,		
	TEXCHECKER_WHITECOLOR_TEX,	
	TEXCHECKER_BLACKCOLOR,		
	TEXCHECKER_BLACKCOLOR_TEX,	
	TEXCHECKER_TILE_U,		
	TEXCHECKER_TILE_V,
	VRAY_TEXCHECKER_SHADER_NAME	= 3000			
};

#endif