CONTAINER tool_KyamaSlide
{
	NAME tool_KyamaSlide;
	INCLUDE ToolBase;
	GROUP MDATA_MAINGROUP
	{
		GROUP
		{
			DEFAULT 1;
			COLUMNS	2;

			COLOR 	Kyama_MSLIDE_CLR1 {}
			BOOL Kyama_MSLIDE_PROL {}
			COLOR 	Kyama_MSLIDE_CLR2 {}
			BOOL Kyama_MSLIDE_REL {}
			BOOL Kyama_MSLIDE_CLAMP {}
			REAL Kyama_MSLIDE_CTOL { MIN 0.01; MAX 100.0; STEP 0.1;}
			REAL Kyama_MSLIDE_DIST { STEP 0.1;}
		}
		REAL Kyama_MSLIDE_DSCALE { UNIT REAL; MIN 0.01; MAX 2.0; MINSLIDER 0.01; MAXSLIDER 2.0; STEP 0.01; CUSTOMGUI REALSLIDER; FIT_H;  SCALE_H;}
	}
	GROUP Kyama_MSLIDE_COMMANDS
	{
		DEFAULT 1;
		BUTTON	Kyama_MSLIDE_CNTR_SMTH		{ FIT_H; }
		BUTTON	Kyama_MSLIDE_CNTR_SHRP		{ FIT_H; }
		BUTTON	Kyama_MSLIDE_CNTR_MIXD		{ FIT_H; }
		BUTTON	Kyama_MSLIDE_CNTR_FLTN		{ FIT_H; }
	}
	HIDE MDATA_COMMANDGROUP;
}
