enum
{
	// string table definitions
	IDS_RHINO	= 10000,
	IDS_RHINO_SERIAL,
	IDS_RHINOEXPORT_APPNAME,
	IDS_RHINOEXPORT_APPURL,
	IDS_RHINOEXPORT_APPDETAILS,
	IDS_REGISTERRHINO,
	IDS_REGISTERWWW,
	IDS_MERGEUPDATE,
	IDS_RHINOTAG,
	IDS_BLOCKDEFINITIONS,
	IDS_RENDERMESHESMISSING,
	IDS_UNKNOWNENTITIESFOUND,
	IDS_DEFAULTLAYERNAME,

// End of symbol definition
  _DUMMY_ELEMENT_
};
