CONTAINER Frhinoimport
{
	NAME Frhinoimport;
	INCLUDE Fbase;

	GROUP RHINOIMPORT_GROUP
	{
		LONG RHINOIMPORT_DOCSCALEMODE
		{
			CYCLE
			{
			    	RHINOIMPORT_DOCSCALEMODE_FROMRHINO;
			    	RHINOIMPORT_DOCSCALEMODE_CUSTOM;
			}
		}

		UNITSCALE RHINOIMPORT_DOCSCALE { }
		
		SEPARATOR { LINE; }
	
		LONG RHINOIMPORT_LAYERMODE
		{
			CYCLE
			{
				RHINOIMPORT_LAYERMODE_OFF;
				RHINOIMPORT_LAYERMODE_LAYER;
				RHINOIMPORT_LAYERMODE_GROUP;
			}
		}
		//BOOL RHINOIMPORT_DROPEMPTYLAYERS { }
		
		SEPARATOR { LINE; }
		
		LONG RHINOIMPORT_MATERIALMODE
		{
			CYCLE
			{
				RHINOIMPORT_MATERIALMODE_OFF;
				RHINOIMPORT_MATERIALMODE_MATERIALS;
				RHINOIMPORT_MATERIALMODE_LAYERCOLORS;
			}
		}
		BOOL RHINOIMPORT_CLEANUPMATERIALS { }

		SEPARATOR { LINE; }
		
		GROUP
		{
			COLUMNS 2;
		
			BOOL RHINOIMPORT_IMPORTMESHOBJECTS { }
			BOOL RHINOIMPORT_IMPORTCAMERAS { }

			BOOL RHINOIMPORT_IMPORTRENDERMESHES { }
			BOOL RHINOIMPORT_IMPORTLIGHTS { }

			BOOL RHINOIMPORT_IMPORTGROUPS { }
			BOOL RHINOIMPORT_SKIPINVISIBLE { }

			BOOL RHINOIMPORT_IMPORTSPLINES { }
			LONG RHINOIMPORT_SPLINESUBDIV { MIN 0; MAX 2000; }
		}
		
		SEPARATOR { LINE; }
		
		GROUP
		{
			COLUMNS 2;

			BOOL RHINOIMPORT_OPTIMIZE { }
			REAL RHINOIMPORT_OPTIMIZETHRESHOLD { MIN 0; MAX 10000; UNIT METER; }
			BOOL RHINOIMPORT_AXISCENTER { }
		}


		SEPARATOR { LINE; }
		
		BUTTON RHINOIMPORT_HELP { }
		//BUTTON RHINOIMPORT_REGISTER { }
	}
}
