#ifndef _Frhinoimport_H_
#define _Frhinoimport_H_

enum
{
	RHINOIMPORT_GROUP					= 999,
    RHINOIMPORT_DOCSCALEMODE			= 1000,
    	RHINOIMPORT_DOCSCALEMODE_FROMRHINO	= 0,
    	RHINOIMPORT_DOCSCALEMODE_CUSTOM		= 1,
    RHINOIMPORT_DOCSCALE			= 1001,
    RHINOIMPORT_LAYERMODE			= 1002,
    	RHINOIMPORT_LAYERMODE_OFF		= 0,
    	RHINOIMPORT_LAYERMODE_LAYER		= 1,
    	RHINOIMPORT_LAYERMODE_GROUP		= 2,
    RHINOIMPORT_MATERIALMODE			= 1003,
    	RHINOIMPORT_MATERIALMODE_OFF		= 0,
    	RHINOIMPORT_MATERIALMODE_MATERIALS	= 1,
    	RHINOIMPORT_MATERIALMODE_LAYERCOLORS	= 2,
    RHINOIMPORT_IMPORTGROUPS			= 1004,
    RHINOIMPORT_AXISCENTER			= 1005,
    RHINOIMPORT_CLEANUPMATERIALS		= 1006,
    RHINOIMPORT_IMPORTCAMERAS			= 1007,
    RHINOIMPORT_IMPORTLIGHTS			= 1008,
    RHINOIMPORT_DROPEMPTYLAYERS			= 1009,	// BOOL
    RHINOIMPORT_IMPORTSPLINES			= 1010,	// BOOL
    RHINOIMPORT_IMPORTMESHOBJECTS		= 1011, // BOOL
    RHINOIMPORT_IMPORTRENDERMESHES		= 1012, // BOOL
    RHINOIMPORT_SKIPINVISIBLE			= 1013, // BOOL
    RHINOIMPORT_OPTIMIZE				= 1014, // BOOL
    RHINOIMPORT_OPTIMIZETHRESHOLD		= 1015, // Real
    RHINOIMPORT_SPLINESUBDIV			= 1016, // LONG

    RHINOIMPORT_HELP				= 2000, // BUTTON
    RHINOIMPORT_REGISTER			= 2001	// BUTTON
};

#endif